<a href="https://colab.research.google.com/github/romerocruzsa/cp-anemia-detection/blob/main/notebooks/capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Import necessary libraries for file handling, data manipulation, and visualization
import os
import random
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Import libraries for working with images and transformations
from PIL import Image
import cv2 as cv

# Import PyTorch modules for model building, data handling, and evaluation
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torch.nn.functional as F
import torchvision.models as models
import torchvision.models.quantization as quant_models
from torch.utils.checkpoint import checkpoint
from torch.utils.data import Dataset, DataLoader, Subset
from timm import create_model

from torchinfo import summary

# Import libraries for machine learning metrics and model evaluation
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, r2_score, confusion_matrix
# import torchmetric
from tqdm import tqdm
from datetime import datetime
import json
import csv

import warnings
warnings.filterwarnings('ignore')
import gc

# Set the seed.
seed = 42
torch.manual_seed(seed)

In [16]:
data_dir="/home/sebastian-cruz6/cp-anemia-detection/data/cp-anemia/"
weights_dir="/home/sebastian-cruz6/cp-anemia-detection/data/notebooks/weights/"
metrics_dir="/home/sebastian-cruz6/cp-anemia-detection/data/notebooks/metrics/"

# data_dir = "/content/drive/MyDrive/CAWT_Sebastian_202425/CP-AnemiC/"
# weights_dir = "/content/drive/MyDrive/CAWT_Sebastian_202425/Weights/"
anemic_dir=data_dir+"/Anemic/"
non_anemic_dir=data_dir+"/Non-anemic/"
signature = "BENCHMARK"

In [17]:
data_sheet_path = data_dir+"Anemia_Data_Collection_Sheet.csv"
data_sheet = pd.read_csv(data_sheet_path)
display(data_sheet)

,IMAGE_ID,HB_LEVEL,Severity,Age(Months),GENDER,REMARK,HOSPITAL,CITY/TOWN,MUNICIPALITY/DISTRICT,REGION,COUNTRY
0,Image_001,9.80,Moderate,6,Female,Anemic,Nkawie-Toase Government Hospital,Nkawie-Toase,Atwima Nwabiagya South,Ashanti,Ghana
1,Image_002,9.90,Moderate,24,Male,Anemic,Ejusu Government Hospital,Ejusu,Ejusu Municipality,Ashanti,Ghana
2,Image_003,11.10,Non-Anemic,24,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
3,Image_004,12.50,Non-Anemic,12,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
4,Image_005,9.90,Moderate,24,Male,Anemic,Sunyani Municipal Hospital,Sunyani,Sunyani Municipality,Bono,Ghana
...,...,...,...,...,...,...,...,...,...,...,...
705,Image_706,12.80,Non-Anemic,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
706,Image_707,11.47,Non-Anemic,48,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
707,Image_708,11.60,Non-Anemic,60,Male,Non-anemic,Komfo Anokye Teaching Hospital,Kumasi,Kumasi Metropolitan,Ashanti,Ghana
708,Image_709,12.10,Non-Anemic,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
709,Image_710,11.70,Non-Anemic,24,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana

In [18]:
# Mapping diagnosis to severity
severity_mapping = {
    "Non-Anemic": 0,
    "Mild": 1,
    "Moderate": 2,
    "Severe": 3,
}

data_sheet['Severity'] = data_sheet['Severity'].map(severity_mapping)
display(data_sheet)

,IMAGE_ID,HB_LEVEL,Severity,Age(Months),GENDER,REMARK,HOSPITAL,CITY/TOWN,MUNICIPALITY/DISTRICT,REGION,COUNTRY
0,Image_001,9.80,2,6,Female,Anemic,Nkawie-Toase Government Hospital,Nkawie-Toase,Atwima Nwabiagya South,Ashanti,Ghana
1,Image_002,9.90,2,24,Male,Anemic,Ejusu Government Hospital,Ejusu,Ejusu Municipality,Ashanti,Ghana
2,Image_003,11.10,0,24,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
3,Image_004,12.50,0,12,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
4,Image_005,9.90,2,24,Male,Anemic,Sunyani Municipal Hospital,Sunyani,Sunyani Municipality,Bono,Ghana
...,...,...,...,...,...,...,...,...,...,...,...
705,Image_706,12.80,0,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
706,Image_707,11.47,0,48,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
707,Image_708,11.60,0,60,Male,Non-anemic,Komfo Anokye Teaching Hospital,Kumasi,Kumasi Metropolitan,Ashanti,Ghana
708,Image_709,12.10,0,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
709,Image_710,11.70,0,24,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana

In [19]:
# Define data augmentations or transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=np.random.rand()),
    transforms.RandomVerticalFlip(p=np.random.rand()),
    transforms.RandomRotation(degrees=np.random.randint(0, 360)),
    transforms.RandomAffine(degrees=np.random.randint(0, 360)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Custom dataset class
class CPAnemiCDataset(Dataset):
    def __init__(self, dir, df, transform=None):
        self.dir = dir
        self.df = df
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_id = row['IMAGE_ID']
        img_folder = row['REMARK']
        img_path = os.path.join(self.dir, img_folder, img_id + ".png")
        img = Image.open(img_path).convert('RGB')

        if self.transform:
            img = self.transform(img)

        multiclass_label = torch.tensor(row['Severity'])
        hb_level = torch.tensor(row['HB_LEVEL'])

        return img, multiclass_label, hb_level

    # Load the dataset
image_dataset = CPAnemiCDataset(data_dir, data_sheet, transform=transform)
train_dataset, test_dataset = train_test_split(image_dataset, test_size=0.20, shuffle=True)

print(f"Image Dataset Size (All): {len(image_dataset)}, \
        Train Size: {len(train_dataset)}, \
        Test Size: {len(test_dataset)}")

BATCH_SIZE = 32
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, pin_memory=True)

Image Dataset Size (All): 710,         Train Size: 568,         Test Size: 142

In [20]:
# Default device
device = torch.device('cpu')

# Check for CUDA availability
if torch.cuda.is_available():
    device = torch.device("cuda:0")
else:
    print("CUDA is not available, using CPU.")

print(f"Selected device: {device}")

Selected device: cuda:0

In [21]:
!nvidia-smi

Tue Mar 25 14:25:03 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:41:00.0 Off |                  Off |
|  0%   53C    P2             98W /  480W |     978MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:82:00.0 Off |                  Off |
|  0%   42C    P8             39W /  480W |     731MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2122      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A     21476      C   ...cp-anemia-detection/cawt/bin/python        384MiB |
|    0   N/A  N/A     22521      C   ...cp-anemia-detection/cawt/bin/python        572MiB |
|    1   N/A  N/A      2122      G   /usr/lib/xorg/Xorg                              9MiB |
|    1   N/A  N/A      2247      G   /usr/bin/gnome-shell                           10MiB |
|    1   N/A  N/A     21476      C   ...cp-anemia-detection/cawt/bin/python        694MiB |
+-----------------------------------------------------------------------------------------+

In [ ]:
def get_model_size(mdl):
    torch.save(mdl.state_dict(), "tmp.pth")
    model_size = "Model Size: %.2f MB" %(os.path.getsize("tmp.pth")/1e6)
    os.remove('tmp.pth')
    return model_size

def timed_forward(model, img):
    """Applies checkpointing and logs GPU latency and memory usage."""
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)

    # Record memory before forward pass
    torch.cuda.reset_peak_memory_stats()
    mem_before = torch.cuda.memory_allocated()
    max_mem_before = torch.cuda.max_memory_allocated()

    # Start measuring latency
    start_event.record()
    class_pred, reg_pred = model(img)
    end_event.record()

    torch.cuda.synchronize()  # Ensure timing accuracy
    latency = start_event.elapsed_time(end_event)  # Time in milliseconds

    # Record memory after forward pass
    mem_after = torch.cuda.memory_allocated()
    max_mem_after = torch.cuda.max_memory_allocated()

    # Store stats in a dictionary
    stats = {
        "latency": latency,
        "malloc_before": mem_before,
        "malloc_after": mem_after,
        "max_malloc": max_mem_after,
    }

    return class_pred, reg_pred, stats

# Static Weighting Function. Set eta_class to desired importance (Classification > .5, Regression < .5, Equal == .5)
def sw_loss(loss_class, loss_reg, eta_class=0.5):
    eta_reg = 1 - eta_class
    total_loss = (eta_class * loss_class) + (eta_reg * loss_reg)
    return total_loss

In [23]:
class MultiModel(nn.Module):
    MODEL_MAPPING = {
        "mobilenetv2": lambda: models.mobilenet_v2(pretrained=False),
        "resnet18": lambda: models.resnet18(pretrained=False),
        "densenet121": lambda: models.densenet121(pretrained=False),
        "vgg16": lambda: models.vgg16(pretrained=False),
        "vit-tiny": lambda: create_model("vit_tiny_patch16_224", pretrained=False),
        "convnext-tiny": lambda: models.convnext_tiny(pretrained=False),
        "efficientnet-b0": lambda: models.efficientnet_b0(pretrained=False),
        "shufflenetv2-0.5x": lambda: models.shufflenet_v2_x0_5(pretrained=False),
        "regnety-400mf": lambda: models.regnet_y_400mf(pretrained=False),
        "mnasnet0_5": lambda: models.mnasnet0_5(pretrained=False),
        "ghostnetv2": lambda: create_model('ghostnetv2_100.in1k', pretrained=False),
        "tinynet-a": lambda: create_model("tinynet_a.in1k", pretrained=False)
    }

    FEATURE_LAYER_MAPPING = {
        "fc": ["resnet", "shufflenet", "regnet"],
        "classifier": ["densenet", "vgg", "mobilenet", "efficientnet",
                       "mnasnet","convnext", "ghostnet", "tinynet"],
        "head": ["vit"]
    }

    def __init__(self, model_name):
        super().__init__()
        self.model_name = model_name.lower()

        if self.model_name not in self.MODEL_MAPPING:
            raise ValueError(f"Model {model_name} not supported")

        self.model = self.MODEL_MAPPING[self.model_name]()
        num_ftrs = self._get_feature_size()

        # print(f"Initial Backbone {get_model_size(self.model)}")

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(p=0.2),
            nn.Linear(num_ftrs, 128),
            nn.ReLU(),
            nn.Linear(128, 5)
        )

        self._assign_classifier()
        # print(f"Modified Backbone {get_model_size(self.model)}\n")

    def _get_feature_size(self):
        """Retrieve the number of input features for the last layer."""
        # Special case for VGG16 since its features need flattening
        if "vgg" in self.model_name:
            return 25088  # VGG16 outputs (batch, 512, 7, 7) -> flattened to 25088

        feature_layers = {
            "fc": getattr(self.model, "fc", None),
            "classifier": getattr(self.model, "classifier", None),
            "head": getattr(self.model, "head", None)
        }

        for key, layer in feature_layers.items():
            if layer:
                return layer[-1].in_features if isinstance(layer, nn.Sequential) else layer.in_features

        return getattr(self.model, "num_features", None)

    def _assign_classifier(self):
        """Assigns the appropriate classifier to the model based on its architecture."""
        if "vgg" in self.model_name:
            self.model.classifier = self.classifier
        else:
          for attr, models in self.FEATURE_LAYER_MAPPING.items():
            if any(m in self.model_name for m in models):
                setattr(self.model, attr, self.classifier)
                return

    def forward(self, x):
        output = self.model(x)
        return output[:, :4], output[:, 4]  # Class probabilities and Hb level estimate

In [24]:
models_list = ["mobilenetv2", "resnet18", "densenet121", "vgg16", "vit-tiny",
               "efficientnet-b0", "shufflenetv2-0.5x", "regnety-400mf",
               "mnasnet0_5", "convnext-tiny", "ghostnetv2", "tinynet-a"
               ]
for arch in models_list:
    print(f"Loading model: {arch}")
    model = MultiModel(arch).to(device)
    print(summary(model))
    # print(model)

Loading model: mobilenetv2
================================================================================
Layer (type:depth-idx)                                  Param #
================================================================================
MultiModel                                              --
├─MobileNetV2: 1-1                                      --
│    └─Sequential: 2-1                                  --
│    │    └─Conv2dNormActivation: 3-1                   928
│    │    └─InvertedResidual: 3-2                       896
│    │    └─InvertedResidual: 3-3                       5,136
│    │    └─InvertedResidual: 3-4                       8,832
│    │    └─InvertedResidual: 3-5                       10,000
│    │    └─InvertedResidual: 3-6                       14,848
│    │    └─InvertedResidual: 3-7                       14,848
│    │    └─InvertedResidual: 3-8                       21,056
│    │    └─InvertedResidual: 3-9                       54,272
│    │    └─InvertedResidual: 3-10                      54,272
│    │    └─InvertedResidual: 3-11                      54,272
│    │    └─InvertedResidual: 3-12                      66,624
│    │    └─InvertedResidual: 3-13                      118,272
│    │    └─InvertedResidual: 3-14                      118,272
│    │    └─InvertedResidual: 3-15                      155,264
│    │    └─InvertedResidual: 3-16                      320,000
│    │    └─InvertedResidual: 3-17                      320,000
│    │    └─InvertedResidual: 3-18                      473,920
│    │    └─Conv2dNormActivation: 3-19                  412,160
│    └─Sequential: 2-2                                  --
│    │    └─Flatten: 3-20                               --
│    │    └─Dropout: 3-21                               --
│    │    └─Linear: 3-22                                163,968
│    │    └─ReLU: 3-23                                  --
│    │    └─Linear: 3-24                                645
├─Sequential: 1-2                                       (recursive)
│    └─Flatten: 2-3                                     --
│    └─Dropout: 2-4                                     --
│    └─Linear: 2-5                                      (recursive)
│    └─ReLU: 2-6                                        --
│    └─Linear: 2-7                                      (recursive)
================================================================================
Total params: 2,388,485
Trainable params: 2,388,485
Non-trainable params: 0
================================================================================
Loading model: resnet18

======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─ResNet: 1-1                                 --
│    └─Conv2d: 2-1                            9,408
│    └─BatchNorm2d: 2-2                       128
│    └─ReLU: 2-3                              --
│    └─MaxPool2d: 2-4                         --
│    └─Sequential: 2-5                        --
│    │    └─BasicBlock: 3-1                   73,984
│    │    └─BasicBlock: 3-2                   73,984
│    └─Sequential: 2-6                        --
│    │    └─BasicBlock: 3-3                   230,144
│    │    └─BasicBlock: 3-4                   295,424
│    └─Sequential: 2-7                        --
│    │    └─BasicBlock: 3-5                   919,040
│    │    └─BasicBlock: 3-6                   1,180,672
│    └─Sequential: 2-8                        --
│    │    └─BasicBlock: 3-7                   3,673,088
│    │    └─BasicBlock: 3-8                   4,720,640
│    └─AdaptiveAvgPool2d: 2-9                 --
│    └─Sequential: 2-10                       --
│    │    └─Flatten: 3-9                      --
│    │    └─Dropout: 3-10                     --
│    │    └─Linear: 3-11                      65,664
│    │    └─ReLU: 3-12                        --
│    │    └─Linear: 3-13                      645
├─Sequential: 1-2                             (recursive)
│    └─Flatten: 2-11                          --
│    └─Dropout: 2-12                          --
│    └─Linear: 2-13                           (recursive)
│    └─ReLU: 2-14                             --
│    └─Linear: 2-15                           (recursive)
======================================================================
Total params: 11,242,821
Trainable params: 11,242,821
Non-trainable params: 0
======================================================================
Loading model: densenet121
======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─DenseNet: 1-1                               --
│    └─Sequential: 2-1                        --
│    │    └─Conv2d: 3-1                       9,408
│    │    └─BatchNorm2d: 3-2                  128
│    │    └─ReLU: 3-3                         --
│    │    └─MaxPool2d: 3-4                    --
│    │    └─_DenseBlock: 3-5                  335,040
│    │    └─_Transition: 3-6                  33,280
│    │    └─_DenseBlock: 3-7                  919,680
│    │    └─_Transition: 3-8                  132,096
│    │    └─_DenseBlock: 3-9                  2,837,760
│    │    └─_Transition: 3-10                 526,336
│    │    └─_DenseBlock: 3-11                 2,158,080
│    │    └─BatchNorm2d: 3-12                 2,048
│    └─Sequential: 2-2                        --
│    │    └─Flatten: 3-13                     --
│    │    └─Dropout: 3-14                     --
│    │    └─Linear: 3-15                      131,200
│    │    └─ReLU: 3-16                        --
│    │    └─Linear: 3-17                      645
├─Sequential: 1-2                             (recursive)
│    └─Flatten: 2-3                           --
│    └─Dropout: 2-4                           --
│    └─Linear: 2-5                            (recursive)
│    └─ReLU: 2-6                              --
│    └─Linear: 2-7                            (recursive)
======================================================================
Total params: 7,085,701
Trainable params: 7,085,701
Non-trainable params: 0
======================================================================
Loading model: vgg16
=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
MultiModel                               --
├─VGG: 1-1                               --
│    └─Sequential: 2-1                   --
│    │    └─Conv2d: 3-1                  1,792
│    │    └─ReLU: 3-2                    --
│    │    └─Conv2d: 3-3                  36,928
│    │    └─ReLU: 3-4                    --
│    │    └─MaxPool2d: 3-5               --
│    │    └─Conv2d: 3-6                  73,856
│    │    └─ReLU: 3-7                    --
│    │    └─Conv2d: 3-8                  147,584
│    │    └─ReLU: 3-9                    --
│    │    └─MaxPool2d: 3-10              --
│    │    └─Conv2d: 3-11                 295,168
│    │    └─ReLU: 3-12                   --
│    │    └─Conv2d: 3-13                 590,080
│    │    └─ReLU: 3-14                   --
│    │    └─Conv2d: 3-15                 590,080
│    │    └─ReLU: 3-16                   --
│    │    └─MaxPool2d: 3-17              --
│    │    └─Conv2d: 3-18                 1,180,160
│    │    └─ReLU: 3-19                   --
│    │    └─Conv2d: 3-20                 2,359,808
│    │    └─ReLU: 3-21                   --
│    │    └─Conv2d: 3-22                 2,359,808
│    │    └─ReLU: 3-23                   --
│    │    └─MaxPool2d: 3-24              --
│    │    └─Conv2d: 3-25                 2,359,808
│    │    └─ReLU: 3-26                   --
│    │    └─Conv2d: 3-27                 2,359,808
│    │    └─ReLU: 3-28                   --
│    │    └─Conv2d: 3-29                 2,359,808
│    │    └─ReLU: 3-30                   --
│    │    └─MaxPool2d: 3-31              --
│    └─AdaptiveAvgPool2d: 2-2            --
│    └─Sequential: 2-3                   --
│    │    └─Flatten: 3-32                --
│    │    └─Dropout: 3-33                --
│    │    └─Linear: 3-34                 3,211,392
│    │    └─ReLU: 3-35                   --
│    │    └─Linear: 3-36                 645
├─Sequential: 1-2                        (recursive)
│    └─Flatten: 2-4                      --
│    └─Dropout: 2-5                      --
│    └─Linear: 2-6                       (recursive)
│    └─ReLU: 2-7                         --
│    └─Linear: 2-8                       (recursive)
=================================================================
Total params: 17,926,725
Trainable params: 17,926,725
Non-trainable params: 0
=================================================================
Loading model: vit-tiny
======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─VisionTransformer: 1-1                      38,016
│    └─PatchEmbed: 2-1                        --
│    │    └─Conv2d: 3-1                       147,648
│    │    └─Identity: 3-2                     --
│    └─Dropout: 2-2                           --
│    └─Identity: 2-3                          --
│    └─Identity: 2-4                          --
│    └─Sequential: 2-5                        --
│    │    └─Block: 3-3                        444,864
│    │    └─Block: 3-4                        444,864
│    │    └─Block: 3-5                        444,864
│    │    └─Block: 3-6                        444,864
│    │    └─Block: 3-7                        444,864
│    │    └─Block: 3-8                        444,864
│    │    └─Block: 3-9                        444,864
│    │    └─Block: 3-10                       444,864
│    │    └─Block: 3-11                       444,864
│    │    └─Block: 3-12                       444,864
│    │    └─Block: 3-13                       444,864
│    │    └─Block: 3-14                       444,864
│    └─LayerNorm: 2-6                         384
│    └─Identity: 2-7                          --
│    └─Dropout: 2-8                           --
│    └─Sequential: 2-9                        --
│    │    └─Flatten: 3-15                     --
│    │    └─Dropout: 3-16                     --
│    │    └─Linear: 3-17                      24,704
│    │    └─ReLU: 3-18                        --
│    │    └─Linear: 3-19                      645
├─Sequential: 1-2                             (recursive)
│    └─Flatten: 2-10                          --
│    └─Dropout: 2-11                          --
│    └─Linear: 2-12                           (recursive)
│    └─ReLU: 2-13                             --
│    └─Linear: 2-14                           (recursive)
======================================================================
Total params: 5,549,765
Trainable params: 5,549,765
Non-trainable params: 0
======================================================================
Loading model: efficientnet-b0
=====================================================================================
Layer (type:depth-idx)                                       Param #
=====================================================================================
MultiModel                                                   --
├─EfficientNet: 1-1                                          --
│    └─Sequential: 2-1                                       --
│    │    └─Conv2dNormActivation: 3-1                        928
│    │    └─Sequential: 3-2                                  1,448
│    │    └─Sequential: 3-3                                  16,714
│    │    └─Sequential: 3-4                                  46,640
│    │    └─Sequential: 3-5                                  242,930
│    │    └─Sequential: 3-6                                  543,148
│    │    └─Sequential: 3-7                                  2,026,348
│    │    └─Sequential: 3-8                                  717,232
│    │    └─Conv2dNormActivation: 3-9                        412,160
│    └─AdaptiveAvgPool2d: 2-2                                --
│    └─Sequential: 2-3                                       --
│    │    └─Flatten: 3-10                                    --
│    │    └─Dropout: 3-11                                    --
│    │    └─Linear: 3-12                                     163,968
│    │    └─ReLU: 3-13                                       --
│    │    └─Linear: 3-14                                     645
├─Sequential: 1-2                                            (recursive)
│    └─Flatten: 2-4                                          --
│    └─Dropout: 2-5                                          --
│    └─Linear: 2-6                                           (recursive)
│    └─ReLU: 2-7                                             --
│    └─Linear: 2-8                                           (recursive)
=====================================================================================
Total params: 4,172,161
Trainable params: 4,172,161
Non-trainable params: 0
=====================================================================================
Loading model: shufflenetv2-0.5x
======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─ShuffleNetV2: 1-1                           --
│    └─Sequential: 2-1                        --
│    │    └─Conv2d: 3-1                       648
│    │    └─BatchNorm2d: 3-2                  48
│    │    └─ReLU: 3-3                         --
│    └─MaxPool2d: 2-2                         --
│    └─Sequential: 2-3                        --
│    │    └─InvertedResidual: 3-4             2,400
│    │    └─InvertedResidual: 3-5             1,512
│    │    └─InvertedResidual: 3-6             1,512
│    │    └─InvertedResidual: 3-7             1,512
│    └─Sequential: 2-4                        --
│    │    └─InvertedResidual: 3-8             8,256
│    │    └─InvertedResidual: 3-9             5,328
│    │    └─InvertedResidual: 3-10            5,328
│    │    └─InvertedResidual: 3-11            5,328
│    │    └─InvertedResidual: 3-12            5,328
│    │    └─InvertedResidual: 3-13            5,328
│    │    └─InvertedResidual: 3-14            5,328
│    │    └─InvertedResidual: 3-15            5,328
│    └─Sequential: 2-5                        --
│    │    └─InvertedResidual: 3-16            30,336
│    │    └─InvertedResidual: 3-17            19,872
│    │    └─InvertedResidual: 3-18            19,872
│    │    └─InvertedResidual: 3-19            19,872
│    └─Sequential: 2-6                        --
│    │    └─Conv2d: 3-20                      196,608
│    │    └─BatchNorm2d: 3-21                 2,048
│    │    └─ReLU: 3-22                        --
│    └─Sequential: 2-7                        --
│    │    └─Flatten: 3-23                     --
│    │    └─Dropout: 3-24                     --
│    │    └─Linear: 3-25                      131,200
│    │    └─ReLU: 3-26                        --
│    │    └─Linear: 3-27                      645
├─Sequential: 1-2                             (recursive)
│    └─Flatten: 2-8                           --
│    └─Dropout: 2-9                           --
│    └─Linear: 2-10                           (recursive)
│    └─ReLU: 2-11                             --
│    └─Linear: 2-12                           (recursive)
======================================================================
Total params: 473,637
Trainable params: 473,637
Non-trainable params: 0
======================================================================
Loading model: regnety-400mf
=====================================================================================
Layer (type:depth-idx)                                       Param #
=====================================================================================
MultiModel                                                   --
├─RegNet: 1-1                                                --
│    └─SimpleStemIN: 2-1                                     --
│    │    └─Conv2d: 3-1                                      864
│    │    └─BatchNorm2d: 3-2                                 64
│    │    └─ReLU: 3-3                                        --
│    └─Sequential: 2-2                                       --
│    │    └─AnyStage: 3-4                                    10,040
│    │    └─AnyStage: 3-5                                    102,296
│    │    └─AnyStage: 3-6                                    737,438
│    │    └─AnyStage: 3-7                                    3,052,442
│    └─AdaptiveAvgPool2d: 2-3                                --
│    └─Sequential: 2-4                                       --
│    │    └─Flatten: 3-8                                     --
│    │    └─Dropout: 3-9                                     --
│    │    └─Linear: 3-10                                     56,448
│    │    └─ReLU: 3-11                                       --
│    │    └─Linear: 3-12                                     645
├─Sequential: 1-2                                            (recursive)
│    └─Flatten: 2-5                                          --
│    └─Dropout: 2-6                                          --
│    └─Linear: 2-7                                           (recursive)
│    └─ReLU: 2-8                                             --
│    └─Linear: 2-9                                           (recursive)
=====================================================================================
Total params: 3,960,237
Trainable params: 3,960,237
Non-trainable params: 0
=====================================================================================
Loading model: mnasnet0_5
===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
MultiModel                                         --
├─MNASNet: 1-1                                     --
│    └─Sequential: 2-1                             --
│    │    └─Conv2d: 3-1                            432
│    │    └─BatchNorm2d: 3-2                       32
│    │    └─ReLU: 3-3                              --
│    │    └─Conv2d: 3-4                            144
│    │    └─BatchNorm2d: 3-5                       32
│    │    └─ReLU: 3-6                              --
│    │    └─Conv2d: 3-7                            128
│    │    └─BatchNorm2d: 3-8                       16
│    │    └─Sequential: 3-9                        5,304
│    │    └─Sequential: 3-10                       14,544
│    │    └─Sequential: 3-11                       65,952
│    │    └─Sequential: 3-12                       55,824
│    │    └─Sequential: 3-13                       432,480
│    │    └─Sequential: 3-14                       155,264
│    │    └─Conv2d: 3-15                           204,800
│    │    └─BatchNorm2d: 3-16                      2,560
│    │    └─ReLU: 3-17                             --
│    └─Sequential: 2-2                             --
│    │    └─Flatten: 3-18                          --
│    │    └─Dropout: 3-19                          --
│    │    └─Linear: 3-20                           163,968
│    │    └─ReLU: 3-21                             --
│    │    └─Linear: 3-22                           645
├─Sequential: 1-2                                  (recursive)
│    └─Flatten: 2-3                                --
│    └─Dropout: 2-4                                --
│    └─Linear: 2-5                                 (recursive)
│    └─ReLU: 2-6                                   --
│    └─Linear: 2-7                                 (recursive)
===========================================================================
Total params: 1,102,125
Trainable params: 1,102,125
Non-trainable params: 0
===========================================================================
Loading model: convnext-tiny
===========================================================================
Layer (type:depth-idx)                             Param #
===========================================================================
MultiModel                                         --
├─ConvNeXt: 1-1                                    --
│    └─Sequential: 2-1                             --
│    │    └─Conv2dNormActivation: 3-1              4,896
│    │    └─Sequential: 3-2                        237,888
│    │    └─Sequential: 3-3                        74,112
│    │    └─Sequential: 3-4                        918,144
│    │    └─Sequential: 3-5                        295,680
│    │    └─Sequential: 3-6                        10,817,280
│    │    └─Sequential: 3-7                        1,181,184
│    │    └─Sequential: 3-8                        14,289,408
│    └─AdaptiveAvgPool2d: 2-2                      --
│    └─Sequential: 2-3                             --
│    │    └─Flatten: 3-9                           --
│    │    └─Dropout: 3-10                          --
│    │    └─Linear: 3-11                           98,432
│    │    └─ReLU: 3-12                             --
│    │    └─Linear: 3-13                           645
├─Sequential: 1-2                                  (recursive)
│    └─Flatten: 2-4                                --
│    └─Dropout: 2-5                                --
│    └─Linear: 2-6                                 (recursive)
│    └─ReLU: 2-7                                   --
│    └─Linear: 2-8                                 (recursive)
===========================================================================
Total params: 27,917,669
Trainable params: 27,917,669
Non-trainable params: 0
===========================================================================
Loading model: ghostnetv2
================================================================================
Layer (type:depth-idx)                                  Param #

In [25]:
def train(dataloader, model, class_loss, reg1_loss, reg2_loss, optimizer):
    """Trains the model and logs additional metrics."""
    model.train()
    total_loss = 0
    total_ce_loss = 0
    total_mse_loss = 0
    total_mae_loss = 0
    correct = 0
    total_samples = 0

    all_preds = []
    all_targets = []
    all_probs = []
    all_hb_targets = []
    all_hb_preds = []

    for _, (img, multiclass, hb_level) in enumerate(dataloader):
        img = img.to(device)
        multiclass = multiclass.to(device).long()
        hb_level = hb_level.to(device).unsqueeze(1).float()

        optimizer.zero_grad()

        # Forward pass
        class_pred, reg_pred = model(img)

        # Compute losses
        ce_loss = class_loss(class_pred, multiclass)
        mse_loss = reg1_loss(reg_pred, hb_level)
        mae_loss = reg2_loss(reg_pred, hb_level)
        loss = sw_loss(ce_loss, mse_loss, 0.7)  # Weighted loss

        # Backpropagation
        loss.backward()
        optimizer.step()

        # Track total losses
        total_loss += loss.item()
        total_ce_loss += ce_loss.item()
        total_mse_loss += mse_loss.item()
        total_mae_loss += mae_loss.item()

        # Compute classification accuracy
        class_probs = F.softmax(class_pred, dim=1)
        highest_prob_class = torch.argmax(class_probs, dim=1)

        correct += (highest_prob_class == multiclass).sum().item()
        total_samples += multiclass.size(0)

        # Collect data for additional metrics
        all_preds.extend(highest_prob_class.detach().cpu().numpy())
        all_targets.extend(multiclass.detach().cpu().numpy())
        all_probs.extend(class_probs.detach().cpu().numpy())
        all_hb_targets.extend(hb_level.detach().cpu().numpy())
        all_hb_preds.extend(reg_pred.squeeze().cpu().detach().numpy())

    # Compute additional metrics
    precision = precision_score(all_targets, all_preds, average="weighted")
    recall = recall_score(all_targets, all_preds, average="weighted")
    f1 = f1_score(all_targets, all_preds, average="weighted")
    auc = roc_auc_score(all_targets, all_probs, multi_class="ovr")
    r2 = r2_score(all_hb_targets, all_hb_preds)

    # Compute final statistics
    avg_loss = total_loss / len(dataloader)
    avg_ce_loss = total_ce_loss / len(dataloader)
    avg_mse_loss = total_mse_loss / len(dataloader)
    avg_mae_loss = total_mae_loss / len(dataloader)
    accuracy = correct / total_samples

    # Store metrics
    final_metrics = [avg_loss, avg_ce_loss, accuracy, precision, recall, f1, auc, r2, avg_mae_loss, avg_mse_loss]

    return final_metrics

In [26]:
def eval(dataloader, model, class_loss, reg1_loss, reg2_loss):
    """Evaluates the model with additional metrics: Precision, Recall, AUC, F1, R², Memory Usage, and Latency."""
    model.eval()
    mean_stats = []

    total_loss = 0
    total_ce_loss = 0
    total_mse_loss = 0
    total_mae_loss = 0
    correct = 0
    total_samples = 0

    all_preds = []
    all_targets = []
    all_probs = []
    all_hb_targets = []
    all_hb_preds = []

    torch.cuda.empty_cache()
    gc.collect()

    with torch.no_grad():
        for _, (img, multiclass, hb_level) in enumerate(dataloader):
            img = img.to(device)
            multiclass = multiclass.to(device).long()
            hb_level = hb_level.to(device).unsqueeze(1).float()

            # Forward pass with latency & memory tracking
            class_pred, reg_pred, stats = timed_forward(model, img)
            mean_stats.append(stats)

            # Compute losses
            ce_loss = class_loss(class_pred, multiclass)
            mse_loss = reg1_loss(reg_pred, hb_level)
            mae_loss = reg2_loss(reg_pred, hb_level)
            loss = sw_loss(ce_loss, mse_loss, 0.7)

            # Track total losses
            total_loss += loss.item()
            total_ce_loss += ce_loss.item()
            total_mse_loss += mse_loss.item()
            total_mae_loss += mae_loss.item()

            # Compute classification accuracy
            class_probs = F.softmax(class_pred, dim=1)
            highest_prob_class = torch.argmax(class_probs, dim=1)

            correct += (highest_prob_class == multiclass).sum().item()
            total_samples += multiclass.size(0)

            # Collect data for additional metrics
            all_preds.extend(highest_prob_class.detach().cpu().numpy())
            all_targets.extend(multiclass.detach().cpu().numpy())
            all_probs.extend(class_probs.detach().cpu().numpy())
            all_hb_targets.extend(hb_level.detach().cpu().numpy())
            all_hb_preds.extend(reg_pred.squeeze().detach().cpu().numpy())

    # Compute mean statistics
    mean_latency = np.mean([s["latency"] for s in mean_stats])
    mean_mem_before = np.mean([s["malloc_before"] for s in mean_stats]) / 1_048_576  # Convert bytes to MB
    mean_mem_after = np.mean([s["malloc_after"] for s in mean_stats]) / 1_048_576  # Convert bytes to MB
    mean_max_mem = np.mean([s["max_malloc"] for s in mean_stats]) / 1_048_576  # Convert bytes to MB

    # Store final mean statistics
    final_mean_stats = [mean_latency, mean_mem_before, mean_mem_after, mean_max_mem]

    # Compute additional evaluation metrics
    precision = precision_score(all_targets, all_preds, average="weighted")
    recall = recall_score(all_targets, all_preds, average="weighted")
    f1 = f1_score(all_targets, all_preds, average="weighted")
    auc = roc_auc_score(all_targets, all_probs, multi_class="ovr")
    r2 = r2_score(all_hb_targets, all_hb_preds)

    # Compute confusion matrix
    # cm = confusion_matrix(all_targets, all_preds)

    # Compute final average losses
    avg_loss = total_loss / len(dataloader)
    avg_ce_loss = total_ce_loss / len(dataloader)
    avg_mse_loss = total_mse_loss / len(dataloader)
    avg_mae_loss = total_mae_loss / len(dataloader)
    accuracy = correct / total_samples

    # Store metrics
    final_metrics = [avg_loss, avg_ce_loss, accuracy, precision, recall, f1, auc, r2, avg_mae_loss, avg_mse_loss]

    return final_metrics, final_mean_stats

In [27]:
def main(ARCH):
    BATCH_SIZE = 32
    EPOCHS = 150
    FOLDS = 5

    # Device setup
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Define loss functions
    cross_entropy_loss = torch.nn.CrossEntropyLoss()  # Multi-class classification loss
    mse_loss = torch.nn.MSELoss()  # Regression loss
    mae_loss = torch.nn.L1Loss()  # Regression loss

    # Set up 5-Fold Cross Validation
    kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)

    # Model Saving Directory
    weights_dir = "weights"
    os.makedirs(weights_dir, exist_ok=True)

    metrics_dir = "metrics"
    os.makedirs(metrics_dir, exist_ok=True)

    print("=" * 100)
    print(f"Training Model: {ARCH}")

    # === INITIALIZE MODEL ===
    model = MultiModel(ARCH).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

    best_val_acc = -float("inf")  # Track best validation accuracy
    train_metrics_list = []
    val_metrics_list = []

    # === TRAINING LOOP ===
    for epoch in range(EPOCHS):
        print(f"\nEpoch {epoch+1}/{EPOCHS}")
        fold = 1

        for train_idx, val_idx in kf.split(range(len(image_dataset))):
            train_subset = Subset(image_dataset, train_idx)
            val_subset = Subset(image_dataset, val_idx)

            train_loader = DataLoader(train_subset, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)
            val_loader = DataLoader(val_subset, batch_size=BATCH_SIZE, shuffle=False, pin_memory=True)

            if fold == FOLDS:
                # === VALIDATION PHASE ===
                val_metrics, val_stats = eval(val_loader, model, cross_entropy_loss, mse_loss, mae_loss)
                print(
                    f"Validation: Fold {fold} - Total Loss: {val_metrics[0]:.4f}, Cross Entropy: {val_metrics[1]:4f}, Accuracy: {val_metrics[2]:.4f}, "
                    f"Precision: {val_metrics[3]:.4f}, Recall: {val_metrics[4]:.4f}, F1 Score: {val_metrics[5]:.4f}, AUC: {val_metrics[6]:.4f}, "
                    f"R2 Score: {val_metrics[7]:4f}, MAE: {val_metrics[8]:.4f}, MSE: {val_metrics[9]:.4f}"
                )
                print(
                    f"Avg Latency (ms): {val_stats[0]:.2f}, Avg Memory Before (MB): {val_stats[1]:.2f}, "
                    f"Avg Memory After (MB): {val_stats[2]:.2f}, Avg Max Memory (MB): {val_stats[3]:.2f}"
                )

                # Save best model based on validation accuracy
                if val_metrics[2] > best_val_acc:
                    best_val_acc = val_metrics[2]
                    torch.save(
                        model,
                        f"{weights_dir}/pytorch/model_best_accuracy_{ARCH}_{signature}.pth",
                    )
                    print(f"Best model saved with Accuracy: {best_val_acc:.4f}")

                # Store validation metrics
                val_metrics_list.append(
                    {
                        "epoch": epoch + 1,
                        "fold": fold,
                        "total_loss": val_metrics[0],
                        "cross_entropy_loss": val_metrics[1],
                        "accuracy": val_metrics[2],
                        "precision": val_metrics[3],
                        "recall": val_metrics[4],
                        "f1_score": val_metrics[5],
                        "auc": val_metrics[6],
                        "r2_score": val_metrics[7],
                        "mae_loss": val_metrics[8],
                        "mse_loss": val_metrics[9],
                        "latency": val_stats[0],
                        "malloc_before": val_stats[1],
                        "malloc_after": val_stats[2],
                        "max_malloc": val_stats[3],
                    }
                )

            else:
                # === TRAINING PHASE ===
                train_metrics = train(train_loader, model, cross_entropy_loss, mse_loss, mae_loss, optimizer)
                print(
                    f"Training: Fold {fold} - Total Loss: {train_metrics[0]:.4f}, Cross Entropy: {train_metrics[1]:4f}, Accuracy: {train_metrics[2]:.4f}, "
                    f"Precision: {train_metrics[3]:.4f}, Recall: {train_metrics[4]:.4f}, F1 Score: {train_metrics[5]:.4f}, AUC: {train_metrics[6]:.4f}, "
                    f"R2 Score: {train_metrics[7]:4f}, MAE: {train_metrics[8]:.4f}, MSE: {train_metrics[9]:.4f}"
                )

                # Store training metrics
                train_metrics_list.append(
                    {
                        "epoch": epoch + 1,
                        "fold": fold,
                        "total_loss": train_metrics[0],
                        "cross_entropy_loss": train_metrics[1],
                        "accuracy": train_metrics[2],
                        "precision": train_metrics[3],
                        "recall": train_metrics[4],
                        "f1_score": train_metrics[5],
                        "auc": train_metrics[6],
                        "r2_score": train_metrics[7],
                        "mae_loss": train_metrics[8],
                        "mse_loss": train_metrics[9],
                    }
                )

            fold += 1  # Move to next fold
        
        keys = train_metrics_list[0].keys()
        with open(f"{metrics_dir}/pytorch/training_metrics_{ARCH}_{signature}.csv", 'w', newline='') as output_file:
            dict_writer = csv.DictWriter(output_file, keys)
            dict_writer.writeheader()
            dict_writer.writerows(train_metrics_list)

        keys = val_metrics_list[0].keys()
        with open(f"{metrics_dir}/pytorch/validation_metrics_{ARCH}_{signature}.csv", 'w', newline='') as output_file:
            dict_writer = csv.DictWriter(output_file, keys)
            dict_writer.writeheader()
            dict_writer.writerows(val_metrics_list)

    print(f"\nFine-tuned {get_model_size(model)}")
    print("=" * 100)

## Model Selection

### MobileNetV2

MobileNetV2 is a highly efficient deep learning model designed for mobile and embedded vision applications. It builds upon its predecessor, MobileNetV1, by introducing **inverted residual blocks** and **linear bottlenecks**, significantly improving both computational efficiency and accuracy. Instead of using standard convolutions, MobileNetV2 employs **depthwise separable convolutions**, reducing the number of parameters while maintaining expressiveness. This makes it particularly useful for real-time applications such as mobile vision, IoT, and edge computing.

- **Paper:** Sandler, M., Howard, A., Zhu, M., Zhmoginov, A., & Chen, L. C. (2018). *MobileNetV2: Inverted Residuals and Linear Bottlenecks*. [CVPR](https://arxiv.org/abs/1801.04381

In [28]:
# === CONFIGURATION ===
ARCH = "mobilenetv2"
main(ARCH)

====================================================================================================
Training Model: mobilenetv2

Epoch 1/150
Training: Fold 1 - Total Loss: 28.6413, Cross Entropy: 1.373471, Accuracy: 0.3662, Precision: 0.2042, Recall: 0.3662, F1 Score: 0.2565, AUC: 0.4934, R2 Score: -16.711635, MAE: 9.3005, MSE: 92.2662
Training: Fold 2 - Total Loss: 17.3097, Cross Entropy: 1.349754, Accuracy: 0.4049, Precision: 0.2988, Recall: 0.4049, F1 Score: 0.2384, AUC: 0.5036, R2 Score: -10.020304, MAE: 7.0254, MSE: 54.5495
Training: Fold 3 - Total Loss: 8.6862, Cross Entropy: 1.345575, Accuracy: 0.3785, Precision: 0.1433, Recall: 0.3785, F1 Score: 0.2079, AUC: 0.5003, R2 Score: -4.329905, MAE: 4.5960, MSE: 25.8142
Training: Fold 4 - Total Loss: 4.2016, Cross Entropy: 1.271020, Accuracy: 0.4173, Precision: 0.1741, Recall: 0.4173, F1 Score: 0.2457, AUC: 0.5042, R2 Score: -1.080541, MAE: 2.8020, MSE: 11.0396
Validation: Fold 5 - Total Loss: 6.0082, Cross Entropy: 1.243434, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4807, R2 Score: -2.175435, MAE: 3.6487, MSE: 17.1260
Avg Latency (ms): 6.73, Avg Memory Before (MB): 100.77, Avg Memory After (MB): 100.77, Avg Max Memory (MB): 385.04
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 2.6405, Cross Entropy: 1.242083, Accuracy: 0.4102, Precision: 0.4964, Recall: 0.4102, F1 Score: 0.2407, AUC: 0.4629, R2 Score: -0.135961, MAE: 1.9502, MSE: 5.9035
Training: Fold 2 - Total Loss: 2.3675, Cross Entropy: 1.235246, Accuracy: 0.3908, Precision: 0.2733, Recall: 0.3908, F1 Score: 0.3015, AUC: 0.4711, R2 Score: 0.002156, MAE: 1.7805, MSE: 5.0093
Training: Fold 3 - Total Loss: 2.3591, Cross Entropy: 1.250112, Accuracy: 0.3592, Precision: 0.2089, Recall: 0.3592, F1 Score: 0.2228, AUC: 0.5045, R2 Score: -0.018706, MAE: 1.7681, MSE: 4.9467
Training: Fold 4 - Total Loss: 2.4703, Cross Entropy: 1.239761, Accuracy: 0.4137, Precision: 0.1739, Recall: 0.4137, F1 Score: 0.2448, AUC: 0.5068, R2 Score: -0.015777, MAE: 1.8382, MSE: 5.3416
Validation: Fold 5 - Total Loss: 2.4731, Cross Entropy: 1.236670, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4618, R2 Score: -0.006688, MAE: 1.8226, MSE: 5.3581
Avg Latency (ms): 3.82, Avg Memory Before (MB): 100.25, Avg Memory After (MB): 100.25, Avg Max Memory (MB): 385.32

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4357, Cross Entropy: 1.240563, Accuracy: 0.4120, Precision: 0.4966, Recall: 0.4120, F1 Score: 0.2445, AUC: 0.4790, R2 Score: -0.009673, MAE: 1.8319, MSE: 5.2243
Training: Fold 2 - Total Loss: 2.3611, Cross Entropy: 1.229415, Accuracy: 0.4049, Precision: 0.3003, Recall: 0.4049, F1 Score: 0.2477, AUC: 0.5282, R2 Score: -0.009147, MAE: 1.7770, MSE: 5.0019
Training: Fold 3 - Total Loss: 2.3378, Cross Entropy: 1.243759, Accuracy: 0.3697, Precision: 0.2567, Recall: 0.3697, F1 Score: 0.2844, AUC: 0.5314, R2 Score: -0.005934, MAE: 1.7503, MSE: 4.8907
Training: Fold 4 - Total Loss: 2.4861, Cross Entropy: 1.243588, Accuracy: 0.4085, Precision: 0.2630, Recall: 0.4085, F1 Score: 0.2621, AUC: 0.5001, R2 Score: 0.001894, MAE: 1.8468, MSE: 5.3852
Validation: Fold 5 - Total Loss: 2.4456, Cross Entropy: 1.231014, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5665, R2 Score: -0.006730, MAE: 1.8155, MSE: 5.2796
Avg Latency (ms): 3.88, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 4/150
Training: Fold 1 - Total Loss: 2.4476, Cross Entropy: 1.232421, Accuracy: 0.4137, Precision: 0.3331, Recall: 0.4137, F1 Score: 0.2518, AUC: 0.5071, R2 Score: -0.007823, MAE: 1.8425, MSE: 5.2829
Training: Fold 2 - Total Loss: 2.3716, Cross Entropy: 1.233916, Accuracy: 0.4049, Precision: 0.2911, Recall: 0.4049, F1 Score: 0.3069, AUC: 0.5155, R2 Score: -0.008435, MAE: 1.7815, MSE: 5.0262
Training: Fold 3 - Total Loss: 2.3563, Cross Entropy: 1.252074, Accuracy: 0.3627, Precision: 0.2449, Recall: 0.3627, F1 Score: 0.2569, AUC: 0.5078, R2 Score: -0.006992, MAE: 1.7590, MSE: 4.9329
Training: Fold 4 - Total Loss: 2.4720, Cross Entropy: 1.241706, Accuracy: 0.4190, Precision: 0.2879, Recall: 0.4190, F1 Score: 0.2844, AUC: 0.4972, R2 Score: -0.008945, MAE: 1.8410, MSE: 5.3426
Validation: Fold 5 - Total Loss: 2.4487, Cross Entropy: 1.230342, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5422, R2 Score: -0.005922, MAE: 1.8176, MSE: 5.2914
Avg Latency (ms): 3.87, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 5/150
Training: Fold 1 - Total Loss: 2.4557, Cross Entropy: 1.236364, Accuracy: 0.4032, Precision: 0.2206, Recall: 0.4032, F1 Score: 0.2380, AUC: 0.5117, R2 Score: -0.000946, MAE: 1.8439, MSE: 5.3007
Training: Fold 2 - Total Loss: 2.3742, Cross Entropy: 1.239709, Accuracy: 0.3926, Precision: 0.2600, Recall: 0.3926, F1 Score: 0.2470, AUC: 0.4808, R2 Score: -0.008920, MAE: 1.7785, MSE: 5.0215
Training: Fold 3 - Total Loss: 2.3591, Cross Entropy: 1.253546, Accuracy: 0.3697, Precision: 0.2533, Recall: 0.3697, F1 Score: 0.2560, AUC: 0.4835, R2 Score: -0.018616, MAE: 1.7575, MSE: 4.9388
Training: Fold 4 - Total Loss: 2.4751, Cross Entropy: 1.234334, Accuracy: 0.4349, Precision: 0.3309, Recall: 0.4349, F1 Score: 0.3051, AUC: 0.5394, R2 Score: -0.015696, MAE: 1.8445, MSE: 5.3702
Validation: Fold 5 - Total Loss: 2.4417, Cross Entropy: 1.223114, Accuracy: 0.3873, Precision: 0.3043, Recall: 0.3873, F1 Score: 0.2280, AUC: 0.5920, R2 Score: 0.010532, MAE: 1.8148, MSE: 5.2852
Avg Latency (ms): 3.87, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4451, Cross Entropy: 1.235336, Accuracy: 0.3944, Precision: 0.2574, Recall: 0.3944, F1 Score: 0.2531, AUC: 0.5010, R2 Score: -0.008332, MAE: 1.8390, MSE: 5.2680
Training: Fold 2 - Total Loss: 2.3633, Cross Entropy: 1.234904, Accuracy: 0.4049, Precision: 0.3037, Recall: 0.4049, F1 Score: 0.2720, AUC: 0.5084, R2 Score: -0.004201, MAE: 1.7775, MSE: 4.9962
Training: Fold 3 - Total Loss: 2.3392, Cross Entropy: 1.248994, Accuracy: 0.3680, Precision: 0.2534, Recall: 0.3680, F1 Score: 0.2814, AUC: 0.4972, R2 Score: 0.001354, MAE: 1.7502, MSE: 4.8832
Training: Fold 4 - Total Loss: 2.4711, Cross Entropy: 1.239590, Accuracy: 0.4155, Precision: 0.2879, Recall: 0.4155, F1 Score: 0.3189, AUC: 0.5435, R2 Score: -0.010178, MAE: 1.8373, MSE: 5.3447
Validation: Fold 5 - Total Loss: 2.4384, Cross Entropy: 1.228600, Accuracy: 0.3803, Precision: 0.1483, Recall: 0.3803, F1 Score: 0.2134, AUC: 0.5402, R2 Score: -0.006211, MAE: 1.8138, MSE: 5.2611
Avg Latency (ms): 3.86, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4364, Cross Entropy: 1.231178, Accuracy: 0.4085, Precision: 0.3310, Recall: 0.4085, F1 Score: 0.2458, AUC: 0.5175, R2 Score: -0.016547, MAE: 1.8398, MSE: 5.2487
Training: Fold 2 - Total Loss: 2.3829, Cross Entropy: 1.230011, Accuracy: 0.4014, Precision: 0.2890, Recall: 0.4014, F1 Score: 0.2703, AUC: 0.5175, R2 Score: -0.010879, MAE: 1.7865, MSE: 5.0729
Training: Fold 3 - Total Loss: 2.3481, Cross Entropy: 1.247731, Accuracy: 0.3627, Precision: 0.2561, Recall: 0.3627, F1 Score: 0.2990, AUC: 0.4957, R2 Score: -0.010719, MAE: 1.7505, MSE: 4.9155
Training: Fold 4 - Total Loss: 2.4705, Cross Entropy: 1.240582, Accuracy: 0.4085, Precision: 0.2788, Recall: 0.4085, F1 Score: 0.3171, AUC: 0.5126, R2 Score: -0.013900, MAE: 1.8382, MSE: 5.3403
Validation: Fold 5 - Total Loss: 2.4269, Cross Entropy: 1.225514, Accuracy: 0.3873, Precision: 0.2290, Recall: 0.3873, F1 Score: 0.2297, AUC: 0.5722, R2 Score: -0.013901, MAE: 1.8153, MSE: 5.2303
Avg Latency (ms): 3.86, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4505, Cross Entropy: 1.234970, Accuracy: 0.4032, Precision: 0.2619, Recall: 0.4032, F1 Score: 0.2635, AUC: 0.5092, R2 Score: -0.012346, MAE: 1.8442, MSE: 5.2869
Training: Fold 2 - Total Loss: 2.3512, Cross Entropy: 1.228623, Accuracy: 0.4067, Precision: 0.2900, Recall: 0.4067, F1 Score: 0.3139, AUC: 0.5534, R2 Score: 0.005721, MAE: 1.7723, MSE: 4.9705
Training: Fold 3 - Total Loss: 2.3510, Cross Entropy: 1.250475, Accuracy: 0.3820, Precision: 0.2681, Recall: 0.3820, F1 Score: 0.2812, AUC: 0.5045, R2 Score: -0.005002, MAE: 1.7578, MSE: 4.9188
Training: Fold 4 - Total Loss: 2.4805, Cross Entropy: 1.237837, Accuracy: 0.4102, Precision: 0.2883, Recall: 0.4102, F1 Score: 0.3310, AUC: 0.5390, R2 Score: 0.006667, MAE: 1.8456, MSE: 5.3799
Validation: Fold 5 - Total Loss: 2.4389, Cross Entropy: 1.216626, Accuracy: 0.4155, Precision: 0.3509, Recall: 0.4155, F1 Score: 0.2954, AUC: 0.5965, R2 Score: -0.015459, MAE: 1.8147, MSE: 5.2909
Avg Latency (ms): 3.84, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78
Best model saved with Accuracy: 0.4155

Epoch 9/150
Training: Fold 1 - Total Loss: 2.4280, Cross Entropy: 1.225688, Accuracy: 0.4120, Precision: 0.2706, Recall: 0.4120, F1 Score: 0.2519, AUC: 0.5336, R2 Score: -0.010932, MAE: 1.8353, MSE: 5.2334
Training: Fold 2 - Total Loss: 2.3507, Cross Entropy: 1.224430, Accuracy: 0.4120, Precision: 0.2933, Recall: 0.4120, F1 Score: 0.3255, AUC: 0.5381, R2 Score: -0.014951, MAE: 1.7711, MSE: 4.9788
Training: Fold 3 - Total Loss: 2.3389, Cross Entropy: 1.246219, Accuracy: 0.3873, Precision: 0.2759, Recall: 0.3873, F1 Score: 0.2844, AUC: 0.5163, R2 Score: -0.015146, MAE: 1.7510, MSE: 4.8884
Training: Fold 4 - Total Loss: 2.4900, Cross Entropy: 1.237838, Accuracy: 0.4366, Precision: 0.3111, Recall: 0.4366, F1 Score: 0.3574, AUC: 0.5403, R2 Score: -0.008710, MAE: 1.8498, MSE: 5.4119
Validation: Fold 5 - Total Loss: 2.4207, Cross Entropy: 1.213021, Accuracy: 0.4014, Precision: 0.2795, Recall: 0.4014, F1 Score: 0.2919, AUC: 0.6003, R2 Score: 0.016872, MAE: 1.8115, MSE: 5.2385
Avg Latency (ms): 3.86, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 10/150
Training: Fold 1 - Total Loss: 2.4487, Cross Entropy: 1.218559, Accuracy: 0.4313, Precision: 0.3286, Recall: 0.4313, F1 Score: 0.3173, AUC: 0.5777, R2 Score: 0.003537, MAE: 1.8486, MSE: 5.3191
Training: Fold 2 - Total Loss: 2.3712, Cross Entropy: 1.228309, Accuracy: 0.4155, Precision: 0.3092, Recall: 0.4155, F1 Score: 0.3533, AUC: 0.5249, R2 Score: -0.010293, MAE: 1.7832, MSE: 5.0378
Training: Fold 3 - Total Loss: 2.3490, Cross Entropy: 1.245343, Accuracy: 0.3944, Precision: 0.2815, Recall: 0.3944, F1 Score: 0.2888, AUC: 0.5215, R2 Score: -0.029804, MAE: 1.7635, MSE: 4.9241
Training: Fold 4 - Total Loss: 2.4650, Cross Entropy: 1.232761, Accuracy: 0.4173, Precision: 0.2961, Recall: 0.4173, F1 Score: 0.3443, AUC: 0.5519, R2 Score: -0.009747, MAE: 1.8389, MSE: 5.3401
Validation: Fold 5 - Total Loss: 2.4150, Cross Entropy: 1.197345, Accuracy: 0.4437, Precision: 0.3095, Recall: 0.4437, F1 Score: 0.3501, AUC: 0.6030, R2 Score: 0.006539, MAE: 1.8106, MSE: 5.2561
Avg Latency (ms): 3.81, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78
Best model saved with Accuracy: 0.4437

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4495, Cross Entropy: 1.217524, Accuracy: 0.4296, Precision: 0.3105, Recall: 0.4296, F1 Score: 0.3354, AUC: 0.5628, R2 Score: -0.007953, MAE: 1.8510, MSE: 5.3241
Training: Fold 2 - Total Loss: 2.3523, Cross Entropy: 1.224720, Accuracy: 0.4243, Precision: 0.3057, Recall: 0.4243, F1 Score: 0.3485, AUC: 0.5545, R2 Score: -0.002924, MAE: 1.7731, MSE: 4.9833
Training: Fold 3 - Total Loss: 2.3315, Cross Entropy: 1.234609, Accuracy: 0.4243, Precision: 0.3081, Recall: 0.4243, F1 Score: 0.3221, AUC: 0.5559, R2 Score: -0.002440, MAE: 1.7545, MSE: 4.8909
Training: Fold 4 - Total Loss: 2.4747, Cross Entropy: 1.228426, Accuracy: 0.4313, Precision: 0.3375, Recall: 0.4313, F1 Score: 0.3666, AUC: 0.5759, R2 Score: -0.006630, MAE: 1.8456, MSE: 5.3828
Validation: Fold 5 - Total Loss: 2.4150, Cross Entropy: 1.175403, Accuracy: 0.4507, Precision: 0.3142, Recall: 0.4507, F1 Score: 0.3702, AUC: 0.5960, R2 Score: -0.021079, MAE: 1.8169, MSE: 5.3074
Avg Latency (ms): 3.85, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78
Best model saved with Accuracy: 0.4507

Epoch 12/150
Training: Fold 1 - Total Loss: 2.4429, Cross Entropy: 1.215052, Accuracy: 0.4313, Precision: 0.3119, Recall: 0.4313, F1 Score: 0.3424, AUC: 0.5724, R2 Score: -0.008438, MAE: 1.8513, MSE: 5.3079
Training: Fold 2 - Total Loss: 2.3520, Cross Entropy: 1.219034, Accuracy: 0.4261, Precision: 0.3090, Recall: 0.4261, F1 Score: 0.3528, AUC: 0.5369, R2 Score: -0.022335, MAE: 1.7777, MSE: 4.9956
Training: Fold 3 - Total Loss: 2.3079, Cross Entropy: 1.211092, Accuracy: 0.4384, Precision: 0.3118, Recall: 0.4384, F1 Score: 0.3643, AUC: 0.5999, R2 Score: 0.005227, MAE: 1.7470, MSE: 4.8671
Training: Fold 4 - Total Loss: 2.4581, Cross Entropy: 1.214507, Accuracy: 0.4384, Precision: 0.3134, Recall: 0.4384, F1 Score: 0.3644, AUC: 0.5713, R2 Score: -0.023853, MAE: 1.8432, MSE: 5.3598
Validation: Fold 5 - Total Loss: 2.3763, Cross Entropy: 1.159481, Accuracy: 0.4718, Precision: 0.3286, Recall: 0.4718, F1 Score: 0.3874, AUC: 0.6093, R2 Score: 0.003819, MAE: 1.8134, MSE: 5.2156
Avg Latency (ms): 3.88, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78
Best model saved with Accuracy: 0.4718

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4334, Cross Entropy: 1.203485, Accuracy: 0.4454, Precision: 0.3285, Recall: 0.4454, F1 Score: 0.3781, AUC: 0.5636, R2 Score: -0.001214, MAE: 1.8456, MSE: 5.3031
Training: Fold 2 - Total Loss: 2.3330, Cross Entropy: 1.199521, Accuracy: 0.4472, Precision: 0.3267, Recall: 0.4472, F1 Score: 0.3775, AUC: 0.5695, R2 Score: -0.016497, MAE: 1.7746, MSE: 4.9777
Training: Fold 3 - Total Loss: 2.3215, Cross Entropy: 1.219870, Accuracy: 0.4137, Precision: 0.2939, Recall: 0.4137, F1 Score: 0.3430, AUC: 0.5524, R2 Score: -0.013336, MAE: 1.7521, MSE: 4.8921
Training: Fold 4 - Total Loss: 2.4579, Cross Entropy: 1.211687, Accuracy: 0.4243, Precision: 0.3104, Recall: 0.4243, F1 Score: 0.3584, AUC: 0.5719, R2 Score: -0.002145, MAE: 1.8458, MSE: 5.3656
Validation: Fold 5 - Total Loss: 2.3940, Cross Entropy: 1.168378, Accuracy: 0.4366, Precision: 0.3062, Recall: 0.4366, F1 Score: 0.3596, AUC: 0.5834, R2 Score: -0.000998, MAE: 1.8222, MSE: 5.2539
Avg Latency (ms): 3.85, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 14/150
Training: Fold 1 - Total Loss: 2.4303, Cross Entropy: 1.200407, Accuracy: 0.4754, Precision: 0.3489, Recall: 0.4754, F1 Score: 0.4016, AUC: 0.5614, R2 Score: -0.017114, MAE: 1.8453, MSE: 5.2999
Training: Fold 2 - Total Loss: 2.3360, Cross Entropy: 1.194377, Accuracy: 0.4384, Precision: 0.3261, Recall: 0.4384, F1 Score: 0.3727, AUC: 0.5635, R2 Score: -0.010889, MAE: 1.7780, MSE: 4.9999
Training: Fold 3 - Total Loss: 2.3078, Cross Entropy: 1.206837, Accuracy: 0.4331, Precision: 0.5284, Recall: 0.4331, F1 Score: 0.3631, AUC: 0.5682, R2 Score: -0.014559, MAE: 1.7491, MSE: 4.8768
Training: Fold 4 - Total Loss: 2.4597, Cross Entropy: 1.214845, Accuracy: 0.4278, Precision: 0.3085, Recall: 0.4278, F1 Score: 0.3583, AUC: 0.5536, R2 Score: -0.009543, MAE: 1.8422, MSE: 5.3645
Validation: Fold 5 - Total Loss: 2.3753, Cross Entropy: 1.136539, Accuracy: 0.4930, Precision: 0.3425, Recall: 0.4930, F1 Score: 0.4040, AUC: 0.6366, R2 Score: 0.002945, MAE: 1.8122, MSE: 5.2657
Avg Latency (ms): 3.89, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78
Best model saved with Accuracy: 0.4930

Epoch 15/150
Training: Fold 1 - Total Loss: 2.3968, Cross Entropy: 1.173627, Accuracy: 0.4842, Precision: 0.3560, Recall: 0.4842, F1 Score: 0.4102, AUC: 0.6158, R2 Score: -0.012413, MAE: 1.8392, MSE: 5.2508
Training: Fold 2 - Total Loss: 2.3533, Cross Entropy: 1.196137, Accuracy: 0.4384, Precision: 0.3332, Recall: 0.4384, F1 Score: 0.3739, AUC: 0.5639, R2 Score: -0.012272, MAE: 1.7862, MSE: 5.0533
Training: Fold 3 - Total Loss: 2.3289, Cross Entropy: 1.217530, Accuracy: 0.4137, Precision: 0.2925, Recall: 0.4137, F1 Score: 0.3421, AUC: 0.5871, R2 Score: -0.006876, MAE: 1.7637, MSE: 4.9219
Training: Fold 4 - Total Loss: 2.4378, Cross Entropy: 1.187480, Accuracy: 0.4560, Precision: 0.4690, Recall: 0.4560, F1 Score: 0.3915, AUC: 0.5909, R2 Score: -0.012618, MAE: 1.8435, MSE: 5.3552
Validation: Fold 5 - Total Loss: 2.3727, Cross Entropy: 1.154013, Accuracy: 0.4437, Precision: 0.3114, Recall: 0.4437, F1 Score: 0.3475, AUC: 0.6499, R2 Score: 0.023368, MAE: 1.8045, MSE: 5.2164
Avg Latency (ms): 3.85, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 16/150
Training: Fold 1 - Total Loss: 2.3961, Cross Entropy: 1.174960, Accuracy: 0.4401, Precision: 0.3234, Recall: 0.4401, F1 Score: 0.3728, AUC: 0.5940, R2 Score: -0.009631, MAE: 1.8377, MSE: 5.2453
Training: Fold 2 - Total Loss: 2.3353, Cross Entropy: 1.197434, Accuracy: 0.4401, Precision: 0.3430, Recall: 0.4401, F1 Score: 0.3749, AUC: 0.5890, R2 Score: -0.018672, MAE: 1.7744, MSE: 4.9902
Training: Fold 3 - Total Loss: 2.3059, Cross Entropy: 1.198475, Accuracy: 0.4155, Precision: 0.4074, Recall: 0.4155, F1 Score: 0.3494, AUC: 0.5822, R2 Score: -0.020523, MAE: 1.7522, MSE: 4.8897
Training: Fold 4 - Total Loss: 2.4327, Cross Entropy: 1.189194, Accuracy: 0.4278, Precision: 0.3503, Recall: 0.4278, F1 Score: 0.3665, AUC: 0.5917, R2 Score: -0.007638, MAE: 1.8383, MSE: 5.3342
Validation: Fold 5 - Total Loss: 2.3750, Cross Entropy: 1.138726, Accuracy: 0.4296, Precision: 0.2934, Recall: 0.4296, F1 Score: 0.3448, AUC: 0.6162, R2 Score: 0.004164, MAE: 1.8157, MSE: 5.2597
Avg Latency (ms): 3.85, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4036, Cross Entropy: 1.171986, Accuracy: 0.4384, Precision: 0.3320, Recall: 0.4384, F1 Score: 0.3763, AUC: 0.5970, R2 Score: -0.015075, MAE: 1.8439, MSE: 5.2773
Training: Fold 2 - Total Loss: 2.3271, Cross Entropy: 1.178795, Accuracy: 0.4437, Precision: 0.3276, Recall: 0.4437, F1 Score: 0.3765, AUC: 0.5892, R2 Score: -0.018236, MAE: 1.7776, MSE: 5.0066
Training: Fold 3 - Total Loss: 2.2953, Cross Entropy: 1.188087, Accuracy: 0.4437, Precision: 0.3285, Recall: 0.4437, F1 Score: 0.3696, AUC: 0.6106, R2 Score: -0.009795, MAE: 1.7486, MSE: 4.8788
Training: Fold 4 - Total Loss: 2.4259, Cross Entropy: 1.163883, Accuracy: 0.4542, Precision: 0.3583, Recall: 0.4542, F1 Score: 0.3905, AUC: 0.6213, R2 Score: -0.015938, MAE: 1.8431, MSE: 5.3705
Validation: Fold 5 - Total Loss: 2.3340, Cross Entropy: 1.115309, Accuracy: 0.4577, Precision: 0.3187, Recall: 0.4577, F1 Score: 0.3753, AUC: 0.6401, R2 Score: 0.013647, MAE: 1.8089, MSE: 5.1775
Avg Latency (ms): 3.84, Avg Memory Before (MB): 99.71, Avg Memory After (MB): 99.71, Avg Max Memory (MB): 384.78

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4010, Cross Entropy: 1.164128, Accuracy: 0.4560, Precision: 0.3437, Recall: 0.4560, F1 Score: 0.3904, AUC: 0.5993, R2 Score: -0.012509, MAE: 1.8480, MSE: 5.2869
Training: Fold 2 - Total Loss: 2.3334, Cross Entropy: 1.172467, Accuracy: 0.4366, Precision: 0.3215, Recall: 0.4366, F1 Score: 0.3701, AUC: 0.6072, R2 Score: -0.011390, MAE: 1.7875, MSE: 5.0421
Training: Fold 3 - Total Loss: 2.3050, Cross Entropy: 1.187736, Accuracy: 0.4437, Precision: 0.3393, Recall: 0.4437, F1 Score: 0.3732, AUC: 0.6108, R2 Score: -0.012612, MAE: 1.7536, MSE: 4.9120
Training: Fold 4 - Total Loss: 2.4404, Cross Entropy: 1.166895, Accuracy: 0.4331, Precision: 0.3564, Recall: 0.4331, F1 Score: 0.3745, AUC: 0.6271, R2 Score: -0.017182, MAE: 1.8495, MSE: 5.4120

### ResNet-18

ResNet (Residual Network) introduced a revolutionary technique called **skip connections**, which helps in training very deep networks without suffering from vanishing gradients. The architecture enables **identity mappings** through shortcut connections, allowing gradients to propagate smoothly during backpropagation. The 18-layer variant (ResNet-18) is a lightweight version of the deeper ResNet models, making it suitable for real-time inference while still benefiting from the **deep residual learning approach**.

- **Paper:** He, K., Zhang, X., Ren, S., & Sun, J. (2016). *Deep Residual Learning for Image Recognition*. [CVPR](https://arxiv.org/abs/1512.03385).

In [29]:
ARCH = "resnet18"
main(ARCH)

====================================================================================================
Training Model: resnet18

Epoch 1/150
Training: Fold 1 - Total Loss: 25.1673, Cross Entropy: 1.705812, Accuracy: 0.0810, Precision: 0.1352, Recall: 0.0810, F1 Score: 0.0395, AUC: 0.4998, R2 Score: -14.262058, MAE: 8.5681, MSE: 79.9106
Training: Fold 2 - Total Loss: 11.5815, Cross Entropy: 2.021323, Accuracy: 0.0669, Precision: 0.0863, Recall: 0.0669, F1 Score: 0.0174, AUC: 0.5107, R2 Score: -5.858213, MAE: 5.3334, MSE: 33.8887
Training: Fold 3 - Total Loss: 4.4490, Cross Entropy: 1.964428, Accuracy: 0.1109, Precision: 0.1244, Recall: 0.1109, F1 Score: 0.0803, AUC: 0.4991, R2 Score: -1.091946, MAE: 2.6828, MSE: 10.2465
Training: Fold 4 - Total Loss: 2.7919, Cross Entropy: 1.600479, Accuracy: 0.2236, Precision: 0.3300, Recall: 0.2236, F1 Score: 0.1467, AUC: 0.5041, R2 Score: -0.049949, MAE: 1.8895, MSE: 5.5720
Validation: Fold 5 - Total Loss: 2.6181, Cross Entropy: 1.355286, Accuracy: 0.2958, Precision: 0.1586, Recall: 0.2958, F1 Score: 0.1869, AUC: 0.5629, R2 Score: -0.065482, MAE: 1.8601, MSE: 5.5645
Avg Latency (ms): 9.22, Avg Memory Before (MB): 238.16, Avg Memory After (MB): 238.16, Avg Max Memory (MB): 412.11
Best model saved with Accuracy: 0.2958

Epoch 2/150
Training: Fold 1 - Total Loss: 2.5296, Cross Entropy: 1.293249, Accuracy: 0.3820, Precision: 0.2949, Recall: 0.3820, F1 Score: 0.3224, AUC: 0.5205, R2 Score: -0.038884, MAE: 1.8697, MSE: 5.4143
Training: Fold 2 - Total Loss: 2.3821, Cross Entropy: 1.240921, Accuracy: 0.4049, Precision: 0.3076, Recall: 0.4049, F1 Score: 0.2719, AUC: 0.5339, R2 Score: -0.016371, MAE: 1.7877, MSE: 5.0450
Training: Fold 3 - Total Loss: 2.3652, Cross Entropy: 1.251370, Accuracy: 0.3838, Precision: 0.4865, Recall: 0.3838, F1 Score: 0.3130, AUC: 0.5278, R2 Score: -0.019117, MAE: 1.7671, MSE: 4.9641
Training: Fold 4 - Total Loss: 2.4838, Cross Entropy: 1.235138, Accuracy: 0.4085, Precision: 0.2913, Recall: 0.4085, F1 Score: 0.3386, AUC: 0.5528, R2 Score: -0.008397, MAE: 1.8533, MSE: 5.3973
Validation: Fold 5 - Total Loss: 2.4057, Cross Entropy: 1.197113, Accuracy: 0.3944, Precision: 0.3059, Recall: 0.3944, F1 Score: 0.2521, AUC: 0.6439, R2 Score: 0.014395, MAE: 1.8181, MSE: 5.2257
Avg Latency (ms): 3.19, Avg Memory Before (MB): 238.16, Avg Memory After (MB): 238.16, Avg Max Memory (MB): 412.11
Best model saved with Accuracy: 0.3944

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4565, Cross Entropy: 1.219359, Accuracy: 0.4049, Precision: 0.2777, Recall: 0.4049, F1 Score: 0.2956, AUC: 0.5622, R2 Score: -0.023207, MAE: 1.8522, MSE: 5.3432
Training: Fold 2 - Total Loss: 2.3767, Cross Entropy: 1.221023, Accuracy: 0.4278, Precision: 0.3089, Recall: 0.4278, F1 Score: 0.3510, AUC: 0.5497, R2 Score: -0.003276, MAE: 1.7961, MSE: 5.0733
Training: Fold 3 - Total Loss: 2.3850, Cross Entropy: 1.235860, Accuracy: 0.3944, Precision: 0.2764, Recall: 0.3944, F1 Score: 0.3203, AUC: 0.5650, R2 Score: -0.011025, MAE: 1.7848, MSE: 5.0663
Training: Fold 4 - Total Loss: 2.5057, Cross Entropy: 1.218605, Accuracy: 0.4278, Precision: 0.5056, Recall: 0.4278, F1 Score: 0.3579, AUC: 0.5847, R2 Score: -0.022659, MAE: 1.8645, MSE: 5.5090
Validation: Fold 5 - Total Loss: 2.4330, Cross Entropy: 1.168689, Accuracy: 0.4437, Precision: 0.2939, Recall: 0.4437, F1 Score: 0.3375, AUC: 0.6562, R2 Score: -0.038813, MAE: 1.8278, MSE: 5.3830
Avg Latency (ms): 3.18, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.4437

Epoch 4/150
Training: Fold 1 - Total Loss: 2.4465, Cross Entropy: 1.206279, Accuracy: 0.4384, Precision: 0.3206, Recall: 0.4384, F1 Score: 0.3614, AUC: 0.5823, R2 Score: -0.004498, MAE: 1.8550, MSE: 5.3402
Training: Fold 2 - Total Loss: 2.3659, Cross Entropy: 1.201822, Accuracy: 0.4384, Precision: 0.4178, Recall: 0.4384, F1 Score: 0.3660, AUC: 0.5817, R2 Score: -0.018307, MAE: 1.7972, MSE: 5.0820
Training: Fold 3 - Total Loss: 2.3476, Cross Entropy: 1.218145, Accuracy: 0.4173, Precision: 0.3741, Recall: 0.4173, F1 Score: 0.3513, AUC: 0.5994, R2 Score: -0.027297, MAE: 1.7691, MSE: 4.9830
Training: Fold 4 - Total Loss: 2.4589, Cross Entropy: 1.199330, Accuracy: 0.4472, Precision: 0.3241, Recall: 0.4472, F1 Score: 0.3757, AUC: 0.6055, R2 Score: -0.030629, MAE: 1.8501, MSE: 5.3979
Validation: Fold 5 - Total Loss: 2.3980, Cross Entropy: 1.146858, Accuracy: 0.4718, Precision: 0.3273, Recall: 0.4718, F1 Score: 0.3862, AUC: 0.6384, R2 Score: -0.024953, MAE: 1.8174, MSE: 5.3173
Avg Latency (ms): 3.18, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.4718

Epoch 5/150
Training: Fold 1 - Total Loss: 2.4432, Cross Entropy: 1.197882, Accuracy: 0.3961, Precision: 0.3154, Recall: 0.3961, F1 Score: 0.3340, AUC: 0.5867, R2 Score: -0.026765, MAE: 1.8569, MSE: 5.3489
Training: Fold 2 - Total Loss: 2.3536, Cross Entropy: 1.189414, Accuracy: 0.4437, Precision: 0.3341, Recall: 0.4437, F1 Score: 0.3794, AUC: 0.5870, R2 Score: -0.013599, MAE: 1.7920, MSE: 5.0701
Training: Fold 3 - Total Loss: 2.3357, Cross Entropy: 1.199016, Accuracy: 0.4366, Precision: 0.3764, Recall: 0.4366, F1 Score: 0.3703, AUC: 0.5978, R2 Score: -0.007699, MAE: 1.7752, MSE: 4.9881
Training: Fold 4 - Total Loss: 2.4459, Cross Entropy: 1.175715, Accuracy: 0.4419, Precision: 0.4157, Recall: 0.4419, F1 Score: 0.3868, AUC: 0.6268, R2 Score: -0.005247, MAE: 1.8509, MSE: 5.4096
Validation: Fold 5 - Total Loss: 2.3388, Cross Entropy: 1.108807, Accuracy: 0.4789, Precision: 0.3557, Recall: 0.4789, F1 Score: 0.3729, AUC: 0.7039, R2 Score: 0.013072, MAE: 1.8085, MSE: 5.2088
Avg Latency (ms): 3.19, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.4789

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4281, Cross Entropy: 1.170275, Accuracy: 0.4894, Precision: 0.4568, Recall: 0.4894, F1 Score: 0.4202, AUC: 0.6276, R2 Score: -0.047136, MAE: 1.8623, MSE: 5.3630
Training: Fold 2 - Total Loss: 2.3651, Cross Entropy: 1.180733, Accuracy: 0.4595, Precision: 0.5515, Recall: 0.4595, F1 Score: 0.3929, AUC: 0.5935, R2 Score: -0.035583, MAE: 1.8015, MSE: 5.1286
Training: Fold 3 - Total Loss: 2.3446, Cross Entropy: 1.208689, Accuracy: 0.4208, Precision: 0.3594, Recall: 0.4208, F1 Score: 0.3627, AUC: 0.6032, R2 Score: -0.036374, MAE: 1.7778, MSE: 4.9951
Training: Fold 4 - Total Loss: 2.4344, Cross Entropy: 1.158851, Accuracy: 0.4648, Precision: 0.4250, Recall: 0.4648, F1 Score: 0.4139, AUC: 0.6418, R2 Score: -0.062112, MAE: 1.8502, MSE: 5.4106
Validation: Fold 5 - Total Loss: 2.3383, Cross Entropy: 1.101852, Accuracy: 0.5070, Precision: 0.3534, Recall: 0.5070, F1 Score: 0.4165, AUC: 0.6845, R2 Score: -0.004245, MAE: 1.8216, MSE: 5.2234
Avg Latency (ms): 3.20, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.5070

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4200, Cross Entropy: 1.166886, Accuracy: 0.4648, Precision: 0.4016, Recall: 0.4648, F1 Score: 0.4025, AUC: 0.6250, R2 Score: -0.026337, MAE: 1.8535, MSE: 5.3440
Training: Fold 2 - Total Loss: 2.3048, Cross Entropy: 1.140386, Accuracy: 0.4613, Precision: 0.4089, Recall: 0.4613, F1 Score: 0.3973, AUC: 0.6397, R2 Score: -0.014083, MAE: 1.7820, MSE: 5.0218
Training: Fold 3 - Total Loss: 2.3090, Cross Entropy: 1.148421, Accuracy: 0.4842, Precision: 0.4361, Recall: 0.4842, F1 Score: 0.4146, AUC: 0.6480, R2 Score: -0.037894, MAE: 1.7763, MSE: 5.0172
Training: Fold 4 - Total Loss: 2.4420, Cross Entropy: 1.166041, Accuracy: 0.4560, Precision: 0.3942, Recall: 0.4560, F1 Score: 0.4102, AUC: 0.6454, R2 Score: -0.019541, MAE: 1.8486, MSE: 5.4192
Validation: Fold 5 - Total Loss: 2.2797, Cross Entropy: 1.039754, Accuracy: 0.5211, Precision: 0.6052, Recall: 0.5211, F1 Score: 0.4417, AUC: 0.7147, R2 Score: 0.047093, MAE: 1.8058, MSE: 5.1729
Avg Latency (ms): 3.20, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.5211

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4009, Cross Entropy: 1.134679, Accuracy: 0.4842, Precision: 0.4380, Recall: 0.4842, F1 Score: 0.4279, AUC: 0.6558, R2 Score: -0.034495, MAE: 1.8611, MSE: 5.3555
Training: Fold 2 - Total Loss: 2.3693, Cross Entropy: 1.173641, Accuracy: 0.4613, Precision: 0.4304, Recall: 0.4613, F1 Score: 0.4003, AUC: 0.6201, R2 Score: -0.028873, MAE: 1.8051, MSE: 5.1593
Training: Fold 3 - Total Loss: 2.3280, Cross Entropy: 1.146763, Accuracy: 0.4824, Precision: 0.4505, Recall: 0.4824, F1 Score: 0.4187, AUC: 0.6481, R2 Score: -0.078689, MAE: 1.7849, MSE: 5.0844
Training: Fold 4 - Total Loss: 2.4230, Cross Entropy: 1.143859, Accuracy: 0.4842, Precision: 0.4325, Recall: 0.4842, F1 Score: 0.4487, AUC: 0.6675, R2 Score: -0.044832, MAE: 1.8561, MSE: 5.4077
Validation: Fold 5 - Total Loss: 2.6951, Cross Entropy: 1.357149, Accuracy: 0.5282, Precision: 0.4625, Recall: 0.5282, F1 Score: 0.4534, AUC: 0.6895, R2 Score: 0.110762, MAE: 1.8896, MSE: 5.8171
Avg Latency (ms): 3.18, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.5282

Epoch 9/150
Training: Fold 1 - Total Loss: 2.4069, Cross Entropy: 1.145005, Accuracy: 0.4842, Precision: 0.4347, Recall: 0.4842, F1 Score: 0.4263, AUC: 0.6558, R2 Score: -0.012739, MAE: 1.8604, MSE: 5.3515
Training: Fold 2 - Total Loss: 2.3371, Cross Entropy: 1.150864, Accuracy: 0.4947, Precision: 0.4346, Recall: 0.4947, F1 Score: 0.4286, AUC: 0.6534, R2 Score: -0.031849, MAE: 1.8003, MSE: 5.1051
Training: Fold 3 - Total Loss: 2.2837, Cross Entropy: 1.139871, Accuracy: 0.4736, Precision: 0.4386, Recall: 0.4736, F1 Score: 0.4183, AUC: 0.6648, R2 Score: -0.021163, MAE: 1.7652, MSE: 4.9526
Training: Fold 4 - Total Loss: 2.4177, Cross Entropy: 1.140767, Accuracy: 0.4894, Precision: 0.4351, Recall: 0.4894, F1 Score: 0.4351, AUC: 0.6788, R2 Score: -0.026587, MAE: 1.8505, MSE: 5.3972
Validation: Fold 5 - Total Loss: 2.3335, Cross Entropy: 1.080928, Accuracy: 0.4859, Precision: 0.3449, Recall: 0.4859, F1 Score: 0.4016, AUC: 0.6969, R2 Score: -0.005981, MAE: 1.8132, MSE: 5.2562
Avg Latency (ms): 3.37, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99

Epoch 10/150
Training: Fold 1 - Total Loss: 2.3994, Cross Entropy: 1.141735, Accuracy: 0.4489, Precision: 0.3756, Recall: 0.4489, F1 Score: 0.3994, AUC: 0.6480, R2 Score: -0.020575, MAE: 1.8543, MSE: 5.3339
Training: Fold 2 - Total Loss: 2.3154, Cross Entropy: 1.136626, Accuracy: 0.4806, Precision: 0.4408, Recall: 0.4806, F1 Score: 0.4392, AUC: 0.6383, R2 Score: -0.042934, MAE: 1.7912, MSE: 5.0659
Training: Fold 3 - Total Loss: 2.2671, Cross Entropy: 1.102712, Accuracy: 0.5176, Precision: 0.4453, Recall: 0.5176, F1 Score: 0.4536, AUC: 0.6885, R2 Score: -0.010904, MAE: 1.7693, MSE: 4.9839
Training: Fold 4 - Total Loss: 2.4028, Cross Entropy: 1.125208, Accuracy: 0.5018, Precision: 0.4406, Recall: 0.5018, F1 Score: 0.4494, AUC: 0.6711, R2 Score: -0.027179, MAE: 1.8462, MSE: 5.3839
Validation: Fold 5 - Total Loss: 2.3563, Cross Entropy: 1.130468, Accuracy: 0.4648, Precision: 0.3780, Recall: 0.4648, F1 Score: 0.3967, AUC: 0.6720, R2 Score: 0.042020, MAE: 1.8053, MSE: 5.2167
Avg Latency (ms): 3.22, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4242, Cross Entropy: 1.157251, Accuracy: 0.4789, Precision: 0.4206, Recall: 0.4789, F1 Score: 0.4377, AUC: 0.6483, R2 Score: -0.027409, MAE: 1.8632, MSE: 5.3805
Training: Fold 2 - Total Loss: 2.3228, Cross Entropy: 1.154942, Accuracy: 0.4648, Precision: 0.3912, Recall: 0.4648, F1 Score: 0.4107, AUC: 0.6334, R2 Score: -0.021111, MAE: 1.7939, MSE: 5.0478
Training: Fold 3 - Total Loss: 2.2864, Cross Entropy: 1.145022, Accuracy: 0.4771, Precision: 0.4278, Recall: 0.4771, F1 Score: 0.4171, AUC: 0.6588, R2 Score: -0.014385, MAE: 1.7639, MSE: 4.9497
Training: Fold 4 - Total Loss: 2.4152, Cross Entropy: 1.115982, Accuracy: 0.4965, Precision: 0.4447, Recall: 0.4965, F1 Score: 0.4490, AUC: 0.6882, R2 Score: -0.029765, MAE: 1.8612, MSE: 5.4466
Validation: Fold 5 - Total Loss: 2.3119, Cross Entropy: 1.074399, Accuracy: 0.5141, Precision: 0.4761, Recall: 0.5141, F1 Score: 0.4250, AUC: 0.7348, R2 Score: 0.057752, MAE: 1.8195, MSE: 5.1995
Avg Latency (ms): 3.18, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99

Epoch 12/150
Training: Fold 1 - Total Loss: 2.3943, Cross Entropy: 1.127989, Accuracy: 0.4930, Precision: 0.4261, Recall: 0.4930, F1 Score: 0.4430, AUC: 0.6657, R2 Score: 0.005047, MAE: 1.8565, MSE: 5.3492
Training: Fold 2 - Total Loss: 2.3154, Cross Entropy: 1.102638, Accuracy: 0.5053, Precision: 0.4486, Recall: 0.5053, F1 Score: 0.4527, AUC: 0.6806, R2 Score: -0.042642, MAE: 1.8183, MSE: 5.1451
Training: Fold 3 - Total Loss: 2.2718, Cross Entropy: 1.130778, Accuracy: 0.5053, Precision: 0.4394, Recall: 0.5053, F1 Score: 0.4358, AUC: 0.6731, R2 Score: -0.044227, MAE: 1.7611, MSE: 4.9342
Training: Fold 4 - Total Loss: 2.3951, Cross Entropy: 1.098996, Accuracy: 0.5229, Precision: 0.4599, Recall: 0.5229, F1 Score: 0.4682, AUC: 0.6966, R2 Score: -0.012300, MAE: 1.8556, MSE: 5.4193
Validation: Fold 5 - Total Loss: 2.2626, Cross Entropy: 0.977233, Accuracy: 0.5493, Precision: 0.3883, Recall: 0.5493, F1 Score: 0.4550, AUC: 0.7412, R2 Score: 0.023036, MAE: 1.8095, MSE: 5.2618
Avg Latency (ms): 3.27, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.5493

Epoch 13/150
Training: Fold 1 - Total Loss: 2.3786, Cross Entropy: 1.091968, Accuracy: 0.5335, Precision: 0.4664, Recall: 0.5335, F1 Score: 0.4851, AUC: 0.6851, R2 Score: -0.046058, MAE: 1.8635, MSE: 5.3807
Training: Fold 2 - Total Loss: 2.2615, Cross Entropy: 1.074259, Accuracy: 0.5194, Precision: 0.4770, Recall: 0.5194, F1 Score: 0.4660, AUC: 0.7161, R2 Score: -0.032992, MAE: 1.7814, MSE: 5.0316
Training: Fold 3 - Total Loss: 2.2505, Cross Entropy: 1.083585, Accuracy: 0.5176, Precision: 0.4625, Recall: 0.5176, F1 Score: 0.4688, AUC: 0.7156, R2 Score: -0.020978, MAE: 1.7672, MSE: 4.9734
Training: Fold 4 - Total Loss: 2.3635, Cross Entropy: 1.067357, Accuracy: 0.5352, Precision: 0.4783, Recall: 0.5352, F1 Score: 0.4954, AUC: 0.7241, R2 Score: -0.006856, MAE: 1.8501, MSE: 5.3878
Validation: Fold 5 - Total Loss: 2.2344, Cross Entropy: 0.974027, Accuracy: 0.5493, Precision: 0.5519, Recall: 0.5493, F1 Score: 0.4778, AUC: 0.7512, R2 Score: 0.009448, MAE: 1.8047, MSE: 5.1754
Avg Latency (ms): 3.24, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99

Epoch 14/150
Training: Fold 1 - Total Loss: 2.3566, Cross Entropy: 1.084645, Accuracy: 0.5229, Precision: 0.4632, Recall: 0.5229, F1 Score: 0.4828, AUC: 0.6991, R2 Score: -0.022942, MAE: 1.8519, MSE: 5.3245
Training: Fold 2 - Total Loss: 2.3119, Cross Entropy: 1.109377, Accuracy: 0.4947, Precision: 0.4161, Recall: 0.4947, F1 Score: 0.4382, AUC: 0.6819, R2 Score: -0.024745, MAE: 1.7953, MSE: 5.1178
Training: Fold 3 - Total Loss: 2.2517, Cross Entropy: 1.086420, Accuracy: 0.5317, Precision: 0.4850, Recall: 0.5317, F1 Score: 0.4892, AUC: 0.7033, R2 Score: -0.020042, MAE: 1.7715, MSE: 4.9707
Training: Fold 4 - Total Loss: 2.3450, Cross Entropy: 1.047061, Accuracy: 0.5651, Precision: 0.4925, Recall: 0.5651, F1 Score: 0.5127, AUC: 0.7391, R2 Score: -0.017240, MAE: 1.8502, MSE: 5.3734
Validation: Fold 5 - Total Loss: 2.2120, Cross Entropy: 0.925494, Accuracy: 0.5845, Precision: 0.5393, Recall: 0.5845, F1 Score: 0.5071, AUC: 0.7821, R2 Score: 0.018659, MAE: 1.8136, MSE: 5.2138
Avg Latency (ms): 3.20, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99
Best model saved with Accuracy: 0.5845

Epoch 15/150
Training: Fold 1 - Total Loss: 2.3269, Cross Entropy: 1.037822, Accuracy: 0.5387, Precision: 0.4434, Recall: 0.5387, F1 Score: 0.4766, AUC: 0.7443, R2 Score: -0.026678, MAE: 1.8501, MSE: 5.3348
Training: Fold 2 - Total Loss: 2.3151, Cross Entropy: 1.112198, Accuracy: 0.5194, Precision: 0.4757, Recall: 0.5194, F1 Score: 0.4670, AUC: 0.6817, R2 Score: -0.021692, MAE: 1.8068, MSE: 5.1220
Training: Fold 3 - Total Loss: 2.2344, Cross Entropy: 1.062621, Accuracy: 0.5423, Precision: 0.4742, Recall: 0.5423, F1 Score: 0.4882, AUC: 0.7209, R2 Score: -0.033438, MAE: 1.7683, MSE: 4.9686
Training: Fold 4 - Total Loss: 2.3508, Cross Entropy: 1.050057, Accuracy: 0.5370, Precision: 0.4764, Recall: 0.5370, F1 Score: 0.4947, AUC: 0.7394, R2 Score: -0.022098, MAE: 1.8476, MSE: 5.3859
Validation: Fold 5 - Total Loss: 2.2607, Cross Entropy: 0.984108, Accuracy: 0.5423, Precision: 0.4703, Recall: 0.5423, F1 Score: 0.4896, AUC: 0.7647, R2 Score: 0.039494, MAE: 1.8055, MSE: 5.2393
Avg Latency (ms): 3.21, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99

Epoch 16/150
Training: Fold 1 - Total Loss: 2.3520, Cross Entropy: 1.049849, Accuracy: 0.5387, Precision: 0.4792, Recall: 0.5387, F1 Score: 0.4871, AUC: 0.7412, R2 Score: -0.012769, MAE: 1.8615, MSE: 5.3905
Training: Fold 2 - Total Loss: 2.2593, Cross Entropy: 1.036667, Accuracy: 0.5458, Precision: 0.5024, Recall: 0.5458, F1 Score: 0.4977, AUC: 0.7332, R2 Score: -0.021246, MAE: 1.8046, MSE: 5.1120
Training: Fold 3 - Total Loss: 2.2739, Cross Entropy: 1.035277, Accuracy: 0.5405, Precision: 0.4821, Recall: 0.5405, F1 Score: 0.5054, AUC: 0.7487, R2 Score: -0.083401, MAE: 1.8103, MSE: 5.1640
Training: Fold 4 - Total Loss: 2.3942, Cross Entropy: 1.063615, Accuracy: 0.5493, Precision: 0.4880, Recall: 0.5493, F1 Score: 0.5003, AUC: 0.7437, R2 Score: -0.012381, MAE: 1.8645, MSE: 5.4989
Validation: Fold 5 - Total Loss: 2.2355, Cross Entropy: 0.938738, Accuracy: 0.5845, Precision: 0.5087, Recall: 0.5845, F1 Score: 0.5189, AUC: 0.7700, R2 Score: -0.023570, MAE: 1.8252, MSE: 5.2613
Avg Latency (ms): 3.20, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99

Epoch 17/150
Training: Fold 1 - Total Loss: 2.3196, Cross Entropy: 1.012519, Accuracy: 0.5599, Precision: 0.4854, Recall: 0.5599, F1 Score: 0.5076, AUC: 0.7452, R2 Score: -0.051245, MAE: 1.8614, MSE: 5.3694
Training: Fold 2 - Total Loss: 2.2507, Cross Entropy: 1.032441, Accuracy: 0.5511, Precision: 0.4892, Recall: 0.5511, F1 Score: 0.5005, AUC: 0.7487, R2 Score: -0.007769, MAE: 1.7971, MSE: 5.0932
Training: Fold 3 - Total Loss: 2.2196, Cross Entropy: 1.031037, Accuracy: 0.5423, Precision: 0.4903, Recall: 0.5423, F1 Score: 0.4967, AUC: 0.7526, R2 Score: -0.014279, MAE: 1.7724, MSE: 4.9928
Training: Fold 4 - Total Loss: 2.3518, Cross Entropy: 1.042249, Accuracy: 0.5387, Precision: 0.4873, Recall: 0.5387, F1 Score: 0.5012, AUC: 0.7459, R2 Score: -0.018430, MAE: 1.8500, MSE: 5.4075
Validation: Fold 5 - Total Loss: 2.2470, Cross Entropy: 0.957502, Accuracy: 0.5634, Precision: 0.6204, Recall: 0.5634, F1 Score: 0.4758, AUC: 0.8085, R2 Score: -0.002577, MAE: 1.8166, MSE: 5.2558
Avg Latency (ms): 3.20, Avg Memory Before (MB): 238.04, Avg Memory After (MB): 238.04, Avg Max Memory (MB): 411.99

Epoch 18/150
Training: Fold 1 - Total Loss: 2.2998, Cross Entropy: 0.975119, Accuracy: 0.5951, Precision: 0.5423, Recall: 0.5951, F1 Score: 0.5620, AUC: 0.7868, R2 Score: -0.027873, MAE: 1.8674, MSE: 5.3907
Training: Fold 2 - Total Loss: 2.2434, Cross Entropy: 1.024136, Accuracy: 0.5687, Precision: 0.5309, Recall: 0.5687, F1 Score: 0.5257, AUC: 0.7311, R2 Score: -0.029798, MAE: 1.7992, MSE: 5.0885
Training: Fold 3 - Total Loss: 2.1912, Cross Entropy: 1.003573, Accuracy: 0.5563, Precision: 0.5047, Recall: 0.5563, F1 Score: 0.5251, AUC: 0.7701, R2 Score: -0.001754, MAE: 1.7685, MSE: 4.9623

### DenseNet-121

DenseNet (Densely Connected Convolutional Networks) improves gradient flow and feature reuse by introducing **dense connections**. Unlike traditional architectures, where layers receive input only from the previous layer, **DenseNet connects each layer to every preceding layer**. This eliminates redundant feature maps and improves efficiency while requiring fewer parameters than other deep networks. DenseNet-121, a version with 121 layers, is particularly effective for feature-rich tasks like medical image classification and object recognition.

- **Paper:** Huang, G., Liu, Z., Van Der Maaten, L., & Weinberger, K. Q. (2017). *Densely Connected Convolutional Networks*. [CVPR](https://arxiv.org/abs/1608.06993).

In [ ]:
ARCH = "densenet121"
main(ARCH)

====================================================================================================
Training Model: densenet121

Epoch 1/150
Training: Fold 1 - Total Loss: 28.0507, Cross Entropy: 1.344499, Accuracy: 0.3627, Precision: 0.3522, Recall: 0.3627, F1 Score: 0.2568, AUC: 0.5332, R2 Score: -16.261096, MAE: 9.2019, MSE: 90.3652
Training: Fold 2 - Total Loss: 15.5603, Cross Entropy: 1.302381, Accuracy: 0.3979, Precision: 0.2935, Recall: 0.3979, F1 Score: 0.3374, AUC: 0.5070, R2 Score: -8.903810, MAE: 6.5755, MSE: 48.8286
Training: Fold 3 - Total Loss: 6.8593, Cross Entropy: 1.329755, Accuracy: 0.3662, Precision: 0.2294, Recall: 0.3662, F1 Score: 0.2330, AUC: 0.5271, R2 Score: -3.085949, MAE: 3.9229, MSE: 19.7616
Training: Fold 4 - Total Loss: 3.3408, Cross Entropy: 1.270405, Accuracy: 0.4243, Precision: 0.2942, Recall: 0.4243, F1 Score: 0.2995, AUC: 0.4975, R2 Score: -0.532054, MAE: 2.3710, MSE: 8.1716
Validation: Fold 5 - Total Loss: 2.4978, Cross Entropy: 1.231907, Accuracy: 0.3873, Precision: 0.2146, Recall: 0.3873, F1 Score: 0.2305, AUC: 0.5876, R2 Score: 0.028320, MAE: 1.8393, MSE: 5.4515
Avg Latency (ms): 17.56, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 2.4490, Cross Entropy: 1.230850, Accuracy: 0.3961, Precision: 0.2476, Recall: 0.3961, F1 Score: 0.2628, AUC: 0.5273, R2 Score: -0.009946, MAE: 1.8444, MSE: 5.2914
Training: Fold 2 - Total Loss: 2.3639, Cross Entropy: 1.229860, Accuracy: 0.3979, Precision: 0.2777, Recall: 0.3979, F1 Score: 0.2855, AUC: 0.5031, R2 Score: -0.008396, MAE: 1.7803, MSE: 5.0100
Training: Fold 3 - Total Loss: 2.3365, Cross Entropy: 1.240659, Accuracy: 0.3926, Precision: 0.2733, Recall: 0.3926, F1 Score: 0.2792, AUC: 0.5591, R2 Score: -0.003535, MAE: 1.7523, MSE: 4.8934
Training: Fold 4 - Total Loss: 2.4646, Cross Entropy: 1.230195, Accuracy: 0.4067, Precision: 0.2693, Recall: 0.4067, F1 Score: 0.2895, AUC: 0.5422, R2 Score: -0.002774, MAE: 1.8395, MSE: 5.3449
Validation: Fold 5 - Total Loss: 2.4135, Cross Entropy: 1.207876, Accuracy: 0.3873, Precision: 0.1511, Recall: 0.3873, F1 Score: 0.2174, AUC: 0.6412, R2 Score: 0.022789, MAE: 1.8084, MSE: 5.2265
Avg Latency (ms): 11.38, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4435, Cross Entropy: 1.216014, Accuracy: 0.4243, Precision: 0.3318, Recall: 0.4243, F1 Score: 0.2937, AUC: 0.5916, R2 Score: -0.003410, MAE: 1.8501, MSE: 5.3075
Training: Fold 2 - Total Loss: 2.3449, Cross Entropy: 1.208768, Accuracy: 0.4595, Precision: 0.3519, Recall: 0.4595, F1 Score: 0.3580, AUC: 0.5978, R2 Score: -0.006280, MAE: 1.7755, MSE: 4.9959
Training: Fold 3 - Total Loss: 2.3141, Cross Entropy: 1.213087, Accuracy: 0.4630, Precision: 0.3290, Recall: 0.4630, F1 Score: 0.3774, AUC: 0.6099, R2 Score: 0.015948, MAE: 1.7494, MSE: 4.8831
Training: Fold 4 - Total Loss: 2.4501, Cross Entropy: 1.207022, Accuracy: 0.4560, Precision: 0.3263, Recall: 0.4560, F1 Score: 0.3788, AUC: 0.6081, R2 Score: 0.004613, MAE: 1.8389, MSE: 5.3506
Validation: Fold 5 - Total Loss: 2.3787, Cross Entropy: 1.154302, Accuracy: 0.4577, Precision: 0.3678, Recall: 0.4577, F1 Score: 0.3441, AUC: 0.6888, R2 Score: 0.033605, MAE: 1.8070, MSE: 5.2356
Avg Latency (ms): 11.37, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.4577

Epoch 4/150
Training: Fold 1 - Total Loss: 2.4058, Cross Entropy: 1.180813, Accuracy: 0.4683, Precision: 0.3436, Recall: 0.4683, F1 Score: 0.3774, AUC: 0.6431, R2 Score: -0.006957, MAE: 1.8384, MSE: 5.2641
Training: Fold 2 - Total Loss: 2.3254, Cross Entropy: 1.177104, Accuracy: 0.4789, Precision: 0.3490, Recall: 0.4789, F1 Score: 0.3945, AUC: 0.6273, R2 Score: -0.015237, MAE: 1.7792, MSE: 5.0047
Training: Fold 3 - Total Loss: 2.3329, Cross Entropy: 1.196554, Accuracy: 0.4630, Precision: 0.3289, Recall: 0.4630, F1 Score: 0.3841, AUC: 0.6207, R2 Score: -0.009055, MAE: 1.7698, MSE: 4.9844
Training: Fold 4 - Total Loss: 2.4375, Cross Entropy: 1.178637, Accuracy: 0.4982, Precision: 0.3702, Recall: 0.4982, F1 Score: 0.4233, AUC: 0.6295, R2 Score: -0.002452, MAE: 1.8437, MSE: 5.3747
Validation: Fold 5 - Total Loss: 2.2969, Cross Entropy: 1.083410, Accuracy: 0.4930, Precision: 0.3449, Recall: 0.4930, F1 Score: 0.3921, AUC: 0.6880, R2 Score: 0.052409, MAE: 1.8076, MSE: 5.1284
Avg Latency (ms): 11.39, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.4930

Epoch 5/150
Training: Fold 1 - Total Loss: 2.3959, Cross Entropy: 1.158758, Accuracy: 0.4859, Precision: 0.3563, Recall: 0.4859, F1 Score: 0.4006, AUC: 0.6488, R2 Score: -0.001182, MAE: 1.8458, MSE: 5.2824
Training: Fold 2 - Total Loss: 2.3033, Cross Entropy: 1.132037, Accuracy: 0.5000, Precision: 0.3677, Recall: 0.5000, F1 Score: 0.4236, AUC: 0.6824, R2 Score: 0.010168, MAE: 1.7859, MSE: 5.0363
Training: Fold 3 - Total Loss: 2.2748, Cross Entropy: 1.147008, Accuracy: 0.5141, Precision: 0.5128, Recall: 0.5141, F1 Score: 0.4333, AUC: 0.6654, R2 Score: 0.002357, MAE: 1.7522, MSE: 4.9064
Training: Fold 4 - Total Loss: 2.3937, Cross Entropy: 1.116012, Accuracy: 0.5088, Precision: 0.5243, Recall: 0.5088, F1 Score: 0.4460, AUC: 0.6805, R2 Score: -0.011806, MAE: 1.8475, MSE: 5.3750
Validation: Fold 5 - Total Loss: 2.2910, Cross Entropy: 1.036293, Accuracy: 0.5423, Precision: 0.6058, Recall: 0.5423, F1 Score: 0.4554, AUC: 0.7271, R2 Score: 0.150916, MAE: 1.8074, MSE: 5.2187
Avg Latency (ms): 11.38, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.5423

Epoch 6/150
Training: Fold 1 - Total Loss: 2.3638, Cross Entropy: 1.108042, Accuracy: 0.5106, Precision: 0.4147, Recall: 0.5106, F1 Score: 0.4350, AUC: 0.6891, R2 Score: -0.008687, MAE: 1.8452, MSE: 5.2939
Training: Fold 2 - Total Loss: 2.2814, Cross Entropy: 1.114217, Accuracy: 0.5141, Precision: 0.3844, Recall: 0.5141, F1 Score: 0.4376, AUC: 0.6699, R2 Score: 0.004547, MAE: 1.7780, MSE: 5.0047
Training: Fold 3 - Total Loss: 2.2381, Cross Entropy: 1.095799, Accuracy: 0.5246, Precision: 0.4668, Recall: 0.5246, F1 Score: 0.4555, AUC: 0.7061, R2 Score: -0.001177, MAE: 1.7510, MSE: 4.9034
Training: Fold 4 - Total Loss: 2.3868, Cross Entropy: 1.110229, Accuracy: 0.5035, Precision: 0.4184, Recall: 0.5035, F1 Score: 0.4372, AUC: 0.6791, R2 Score: -0.029800, MAE: 1.8428, MSE: 5.3656
Validation: Fold 5 - Total Loss: 2.2645, Cross Entropy: 0.981198, Accuracy: 0.5704, Precision: 0.6269, Recall: 0.5704, F1 Score: 0.4881, AUC: 0.7532, R2 Score: 0.002923, MAE: 1.8114, MSE: 5.2587
Avg Latency (ms): 11.40, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.5704

Epoch 7/150
Training: Fold 1 - Total Loss: 2.3380, Cross Entropy: 1.083844, Accuracy: 0.5282, Precision: 0.4776, Recall: 0.5282, F1 Score: 0.4601, AUC: 0.7106, R2 Score: 0.003833, MAE: 1.8392, MSE: 5.2644
Training: Fold 2 - Total Loss: 2.2462, Cross Entropy: 1.061568, Accuracy: 0.5352, Precision: 0.4911, Recall: 0.5352, F1 Score: 0.4791, AUC: 0.7029, R2 Score: -0.014562, MAE: 1.7824, MSE: 5.0105
Training: Fold 3 - Total Loss: 2.2198, Cross Entropy: 1.067707, Accuracy: 0.5264, Precision: 0.4746, Recall: 0.5264, F1 Score: 0.4583, AUC: 0.7175, R2 Score: -0.007436, MAE: 1.7560, MSE: 4.9079
Training: Fold 4 - Total Loss: 2.3442, Cross Entropy: 1.058852, Accuracy: 0.5335, Precision: 0.4943, Recall: 0.5335, F1 Score: 0.4604, AUC: 0.7308, R2 Score: -0.009814, MAE: 1.8361, MSE: 5.3432
Validation: Fold 5 - Total Loss: 2.2821, Cross Entropy: 1.053344, Accuracy: 0.5282, Precision: 0.5886, Recall: 0.5282, F1 Score: 0.4438, AUC: 0.7247, R2 Score: 0.051323, MAE: 1.7976, MSE: 5.1493
Avg Latency (ms): 11.38, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 8/150
Training: Fold 1 - Total Loss: 2.3639, Cross Entropy: 1.104948, Accuracy: 0.5018, Precision: 0.4334, Recall: 0.5018, F1 Score: 0.4482, AUC: 0.6862, R2 Score: -0.018293, MAE: 1.8472, MSE: 5.3015
Training: Fold 2 - Total Loss: 2.2340, Cross Entropy: 1.049096, Accuracy: 0.5423, Precision: 0.4661, Recall: 0.5423, F1 Score: 0.4747, AUC: 0.7233, R2 Score: -0.035043, MAE: 1.7712, MSE: 4.9986
Training: Fold 3 - Total Loss: 2.2153, Cross Entropy: 1.056453, Accuracy: 0.5458, Precision: 0.4625, Recall: 0.5458, F1 Score: 0.4682, AUC: 0.7353, R2 Score: -0.002266, MAE: 1.7543, MSE: 4.9193
Training: Fold 4 - Total Loss: 2.3218, Cross Entropy: 1.020105, Accuracy: 0.5669, Precision: 0.5170, Recall: 0.5669, F1 Score: 0.5204, AUC: 0.7543, R2 Score: -0.015041, MAE: 1.8424, MSE: 5.3589
Validation: Fold 5 - Total Loss: 2.2210, Cross Entropy: 0.960385, Accuracy: 0.5915, Precision: 0.5909, Recall: 0.5915, F1 Score: 0.5145, AUC: 0.7638, R2 Score: 0.034424, MAE: 1.8052, MSE: 5.1624
Avg Latency (ms): 11.37, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.5915

Epoch 9/150
Training: Fold 1 - Total Loss: 2.3213, Cross Entropy: 1.046713, Accuracy: 0.5581, Precision: 0.4906, Recall: 0.5581, F1 Score: 0.4957, AUC: 0.7243, R2 Score: -0.010117, MAE: 1.8444, MSE: 5.2954
Training: Fold 2 - Total Loss: 2.2299, Cross Entropy: 1.032954, Accuracy: 0.5317, Precision: 0.4778, Recall: 0.5317, F1 Score: 0.4788, AUC: 0.7415, R2 Score: -0.012117, MAE: 1.7817, MSE: 5.0228
Training: Fold 3 - Total Loss: 2.1961, Cross Entropy: 1.030727, Accuracy: 0.5599, Precision: 0.4835, Recall: 0.5599, F1 Score: 0.4931, AUC: 0.7496, R2 Score: -0.011234, MAE: 1.7566, MSE: 4.9152
Training: Fold 4 - Total Loss: 2.3401, Cross Entropy: 1.039963, Accuracy: 0.5599, Precision: 0.4810, Recall: 0.5599, F1 Score: 0.4919, AUC: 0.7318, R2 Score: -0.014622, MAE: 1.8444, MSE: 5.3738
Validation: Fold 5 - Total Loss: 2.2646, Cross Entropy: 1.039188, Accuracy: 0.5423, Precision: 0.4960, Recall: 0.5423, F1 Score: 0.4666, AUC: 0.7486, R2 Score: 0.073273, MAE: 1.8070, MSE: 5.1238
Avg Latency (ms): 11.89, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 10/150
Training: Fold 1 - Total Loss: 2.3096, Cross Entropy: 1.028699, Accuracy: 0.5335, Precision: 0.4501, Recall: 0.5335, F1 Score: 0.4759, AUC: 0.7332, R2 Score: -0.014974, MAE: 1.8467, MSE: 5.2985
Training: Fold 2 - Total Loss: 2.1861, Cross Entropy: 0.972154, Accuracy: 0.5933, Precision: 0.5371, Recall: 0.5933, F1 Score: 0.5324, AUC: 0.7681, R2 Score: -0.017365, MAE: 1.7850, MSE: 5.0187
Training: Fold 3 - Total Loss: 2.1637, Cross Entropy: 0.993893, Accuracy: 0.5546, Precision: 0.4854, Recall: 0.5546, F1 Score: 0.5040, AUC: 0.7776, R2 Score: 0.008850, MAE: 1.7533, MSE: 4.8933
Training: Fold 4 - Total Loss: 2.3033, Cross Entropy: 0.961461, Accuracy: 0.5863, Precision: 0.5348, Recall: 0.5863, F1 Score: 0.5530, AUC: 0.7879, R2 Score: -0.018182, MAE: 1.8536, MSE: 5.4342
Validation: Fold 5 - Total Loss: 2.1998, Cross Entropy: 0.892182, Accuracy: 0.5704, Precision: 0.5460, Recall: 0.5704, F1 Score: 0.5244, AUC: 0.7977, R2 Score: 0.002879, MAE: 1.8138, MSE: 5.2510
Avg Latency (ms): 11.62, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 11/150
Training: Fold 1 - Total Loss: 2.2841, Cross Entropy: 0.987990, Accuracy: 0.5651, Precision: 0.5098, Recall: 0.5651, F1 Score: 0.5122, AUC: 0.7665, R2 Score: -0.027979, MAE: 1.8545, MSE: 5.3085
Training: Fold 2 - Total Loss: 2.1895, Cross Entropy: 0.973871, Accuracy: 0.5810, Precision: 0.5074, Recall: 0.5810, F1 Score: 0.5211, AUC: 0.7753, R2 Score: 0.004425, MAE: 1.7791, MSE: 5.0259
Training: Fold 3 - Total Loss: 2.1532, Cross Entropy: 0.972244, Accuracy: 0.5986, Precision: 0.5437, Recall: 0.5986, F1 Score: 0.5535, AUC: 0.7744, R2 Score: -0.021066, MAE: 1.7560, MSE: 4.9087
Training: Fold 4 - Total Loss: 2.2959, Cross Entropy: 0.966019, Accuracy: 0.5968, Precision: 0.5413, Recall: 0.5968, F1 Score: 0.5557, AUC: 0.7888, R2 Score: 0.004916, MAE: 1.8473, MSE: 5.3988
Validation: Fold 5 - Total Loss: 2.1706, Cross Entropy: 0.820055, Accuracy: 0.6690, Precision: 0.6184, Recall: 0.6690, F1 Score: 0.6292, AUC: 0.8343, R2 Score: -0.056970, MAE: 1.8253, MSE: 5.3218
Avg Latency (ms): 11.40, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.6690

Epoch 12/150
Training: Fold 1 - Total Loss: 2.2514, Cross Entropy: 0.959731, Accuracy: 0.5775, Precision: 0.5226, Recall: 0.5775, F1 Score: 0.5371, AUC: 0.7827, R2 Score: -0.033916, MAE: 1.8413, MSE: 5.2653
Training: Fold 2 - Total Loss: 2.1435, Cross Entropy: 0.921307, Accuracy: 0.6074, Precision: 0.5498, Recall: 0.6074, F1 Score: 0.5464, AUC: 0.8024, R2 Score: 0.009289, MAE: 1.7744, MSE: 4.9953
Training: Fold 3 - Total Loss: 2.1381, Cross Entropy: 0.941259, Accuracy: 0.5827, Precision: 0.5332, Recall: 0.5827, F1 Score: 0.5521, AUC: 0.8004, R2 Score: -0.009315, MAE: 1.7530, MSE: 4.9307
Training: Fold 4 - Total Loss: 2.2667, Cross Entropy: 0.938696, Accuracy: 0.5880, Precision: 0.5343, Recall: 0.5880, F1 Score: 0.5547, AUC: 0.7961, R2 Score: -0.010339, MAE: 1.8443, MSE: 5.3653
Validation: Fold 5 - Total Loss: 2.1491, Cross Entropy: 0.834670, Accuracy: 0.6127, Precision: 0.5535, Recall: 0.6127, F1 Score: 0.5563, AUC: 0.8438, R2 Score: 0.004474, MAE: 1.8097, MSE: 5.2161
Avg Latency (ms): 11.41, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 13/150
Training: Fold 1 - Total Loss: 2.2205, Cross Entropy: 0.910244, Accuracy: 0.6250, Precision: 0.5710, Recall: 0.6250, F1 Score: 0.5857, AUC: 0.8102, R2 Score: -0.017652, MAE: 1.8418, MSE: 5.2777
Training: Fold 2 - Total Loss: 2.1534, Cross Entropy: 0.926289, Accuracy: 0.6004, Precision: 0.5459, Recall: 0.6004, F1 Score: 0.5610, AUC: 0.8040, R2 Score: -0.021392, MAE: 1.7831, MSE: 5.0165
Training: Fold 3 - Total Loss: 2.1216, Cross Entropy: 0.931086, Accuracy: 0.6056, Precision: 0.5586, Recall: 0.6056, F1 Score: 0.5652, AUC: 0.7995, R2 Score: -0.005335, MAE: 1.7587, MSE: 4.8996
Training: Fold 4 - Total Loss: 2.2480, Cross Entropy: 0.918451, Accuracy: 0.6180, Precision: 0.5668, Recall: 0.6180, F1 Score: 0.5908, AUC: 0.8058, R2 Score: -0.015283, MAE: 1.8398, MSE: 5.3502
Validation: Fold 5 - Total Loss: 2.1836, Cross Entropy: 0.828957, Accuracy: 0.6479, Precision: 0.5940, Recall: 0.6479, F1 Score: 0.6073, AUC: 0.8326, R2 Score: -0.023110, MAE: 1.8204, MSE: 5.3444
Avg Latency (ms): 11.41, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 14/150
Training: Fold 1 - Total Loss: 2.2377, Cross Entropy: 0.925357, Accuracy: 0.6109, Precision: 0.5599, Recall: 0.6109, F1 Score: 0.5808, AUC: 0.8032, R2 Score: 0.002246, MAE: 1.8438, MSE: 5.2999
Training: Fold 2 - Total Loss: 2.1482, Cross Entropy: 0.929932, Accuracy: 0.6004, Precision: 0.5407, Recall: 0.6004, F1 Score: 0.5386, AUC: 0.7987, R2 Score: -0.011220, MAE: 1.7774, MSE: 4.9908
Training: Fold 3 - Total Loss: 2.1139, Cross Entropy: 0.904069, Accuracy: 0.6268, Precision: 0.5758, Recall: 0.6268, F1 Score: 0.5981, AUC: 0.8242, R2 Score: -0.000651, MAE: 1.7608, MSE: 4.9368
Training: Fold 4 - Total Loss: 2.2524, Cross Entropy: 0.910154, Accuracy: 0.6109, Precision: 0.5690, Recall: 0.6109, F1 Score: 0.5830, AUC: 0.8157, R2 Score: -0.020464, MAE: 1.8470, MSE: 5.3844
Validation: Fold 5 - Total Loss: 2.1121, Cross Entropy: 0.767045, Accuracy: 0.6761, Precision: 0.6240, Recall: 0.6761, F1 Score: 0.6193, AUC: 0.8527, R2 Score: -0.001194, MAE: 1.8159, MSE: 5.2505
Avg Latency (ms): 11.39, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.6761

Epoch 15/150
Training: Fold 1 - Total Loss: 2.2007, Cross Entropy: 0.881973, Accuracy: 0.6320, Precision: 0.5742, Recall: 0.6320, F1 Score: 0.5876, AUC: 0.8189, R2 Score: -0.006587, MAE: 1.8450, MSE: 5.2778
Training: Fold 2 - Total Loss: 2.1231, Cross Entropy: 0.892374, Accuracy: 0.6215, Precision: 0.5669, Recall: 0.6215, F1 Score: 0.5790, AUC: 0.8136, R2 Score: -0.006617, MAE: 1.7772, MSE: 4.9949
Training: Fold 3 - Total Loss: 2.1181, Cross Entropy: 0.925558, Accuracy: 0.5951, Precision: 0.5397, Recall: 0.5951, F1 Score: 0.5528, AUC: 0.8118, R2 Score: -0.008062, MAE: 1.7553, MSE: 4.9006
Training: Fold 4 - Total Loss: 2.2266, Cross Entropy: 0.895307, Accuracy: 0.6215, Precision: 0.5741, Recall: 0.6215, F1 Score: 0.5949, AUC: 0.8179, R2 Score: -0.012256, MAE: 1.8359, MSE: 5.3329
Validation: Fold 5 - Total Loss: 2.1076, Cross Entropy: 0.761938, Accuracy: 0.7042, Precision: 0.6558, Recall: 0.7042, F1 Score: 0.6787, AUC: 0.8738, R2 Score: -0.001165, MAE: 1.8194, MSE: 5.2475
Avg Latency (ms): 11.88, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83
Best model saved with Accuracy: 0.7042

Epoch 16/150
Training: Fold 1 - Total Loss: 2.1981, Cross Entropy: 0.871387, Accuracy: 0.6532, Precision: 0.6001, Recall: 0.6532, F1 Score: 0.6239, AUC: 0.8258, R2 Score: -0.018033, MAE: 1.8477, MSE: 5.2937
Training: Fold 2 - Total Loss: 2.1187, Cross Entropy: 0.862747, Accuracy: 0.6602, Precision: 0.6017, Recall: 0.6602, F1 Score: 0.6130, AUC: 0.8192, R2 Score: -0.004853, MAE: 1.7868, MSE: 5.0494
Training: Fold 3 - Total Loss: 2.0673, Cross Entropy: 0.854545, Accuracy: 0.6197, Precision: 0.5667, Recall: 0.6197, F1 Score: 0.5816, AUC: 0.8353, R2 Score: -0.005867, MAE: 1.7489, MSE: 4.8971
Training: Fold 4 - Total Loss: 2.2055, Cross Entropy: 0.861304, Accuracy: 0.6056, Precision: 0.5538, Recall: 0.6056, F1 Score: 0.5760, AUC: 0.8259, R2 Score: -0.021293, MAE: 1.8383, MSE: 5.3421
Validation: Fold 5 - Total Loss: 2.0735, Cross Entropy: 0.723095, Accuracy: 0.6901, Precision: 0.6533, Recall: 0.6901, F1 Score: 0.6639, AUC: 0.8817, R2 Score: 0.017262, MAE: 1.8151, MSE: 5.2246
Avg Latency (ms): 11.38, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 17/150
Training: Fold 1 - Total Loss: 2.2019, Cross Entropy: 0.885631, Accuracy: 0.5968, Precision: 0.5807, Recall: 0.5968, F1 Score: 0.5747, AUC: 0.8123, R2 Score: -0.021558, MAE: 1.8388, MSE: 5.2732
Training: Fold 2 - Total Loss: 2.0898, Cross Entropy: 0.838628, Accuracy: 0.6637, Precision: 0.6836, Recall: 0.6637, F1 Score: 0.6188, AUC: 0.8374, R2 Score: -0.012030, MAE: 1.7780, MSE: 5.0092
Training: Fold 3 - Total Loss: 2.0565, Cross Entropy: 0.834232, Accuracy: 0.6373, Precision: 0.5889, Recall: 0.6373, F1 Score: 0.6048, AUC: 0.8383, R2 Score: -0.019031, MAE: 1.7535, MSE: 4.9086
Training: Fold 4 - Total Loss: 2.1917, Cross Entropy: 0.816406, Accuracy: 0.6391, Precision: 0.6193, Recall: 0.6391, F1 Score: 0.6153, AUC: 0.8438, R2 Score: -0.014755, MAE: 1.8541, MSE: 5.4006
Validation: Fold 5 - Total Loss: 2.1175, Cross Entropy: 0.763765, Accuracy: 0.6479, Precision: 0.6271, Recall: 0.6479, F1 Score: 0.6100, AUC: 0.8613, R2 Score: -0.039344, MAE: 1.8292, MSE: 5.2764
Avg Latency (ms): 11.39, Avg Memory Before (MB): 170.53, Avg Memory After (MB): 170.53, Avg Max Memory (MB): 442.83

Epoch 18/150
Training: Fold 1 - Total Loss: 2.1675, Cross Entropy: 0.800914, Accuracy: 0.6585, Precision: 0.6691, Recall: 0.6585, F1 Score: 0.6263, AUC: 0.8532, R2 Score: -0.026285, MAE: 1.8536, MSE: 5.3562
Training: Fold 2 - Total Loss: 2.0930, Cross Entropy: 0.828325, Accuracy: 0.6479, Precision: 0.5923, Recall: 0.6479, F1 Score: 0.6155, AUC: 0.8385, R2 Score: -0.028250, MAE: 1.7831, MSE: 5.0440
Training: Fold 3 - Total Loss: 2.0588, Cross Entropy: 0.827592, Accuracy: 0.6268, Precision: 0.5773, Recall: 0.6268, F1 Score: 0.5970, AUC: 0.8451, R2 Score: -0.019238, MAE: 1.7553, MSE: 4.9316
Training: Fold 4 - Total Loss: 2.1930, Cross Entropy: 0.820407, Accuracy: 0.6250, Precision: 0.5801, Recall: 0.6250, F1 Score: 0.6008, AUC: 0.8436, R2 Score: -0.010575, MAE: 1.8501, MSE: 5.3956

### VGG16

VGG16 is a deep convolutional neural network that achieved **high accuracy** in image classification tasks while maintaining a **simple architecture**. It consists of **16 layers**, primarily using **small 3×3 convolutions** stacked in increasing depth, with max pooling layers interspersed to reduce spatial dimensions. Unlike more recent models, VGG16 has a relatively high number of parameters, making it computationally expensive. However, it remains widely used for **transfer learning** due to its well-generalized feature representations.

- **Paper:** Simonyan, K., & Zisserman, A. (2015). *Very Deep Convolutional Networks for Large-Scale Image Recognition*. [ICLR](https://arxiv.org/abs/1409.1556).

In [ ]:
ARCH = "vgg16"
main(ARCH)

====================================================================================================
Training Model: vgg16
Initial Backbone Model Size: 553.44 MB
Modified Backbone Model Size: 71.72 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 23.4931, Cross Entropy: 1.544922, Accuracy: 0.2746, Precision: 0.3001, Recall: 0.2746, F1 Score: 0.2580, AUC: 0.4869, R2 Score: -13.446200, MAE: 7.6256, MSE: 74.7054
Training: Fold 2 - Total Loss: 4.3090, Cross Entropy: 1.313687, Accuracy: 0.3803, Precision: 0.2802, Recall: 0.3803, F1 Score: 0.3223, AUC: 0.5186, R2 Score: -1.271565, MAE: 2.6997, MSE: 11.2980
Training: Fold 3 - Total Loss: 2.4912, Cross Entropy: 1.252014, Accuracy: 0.3856, Precision: 0.3667, Recall: 0.3856, F1 Score: 0.2337, AUC: 0.5245, R2 Score: -0.083461, MAE: 1.8544, MSE: 5.3827
Training: Fold 4 - Total Loss: 2.6071, Cross Entropy: 1.260055, Accuracy: 0.3750, Precision: 0.2786, Recall: 0.3750, F1 Score: 0.3187, AUC: 0.4978, R2 Score: -0.070416, MAE: 1.9069, MSE: 5.7503
Validation: Fold 5 - Total Loss: 2.4628, Cross Entropy: 1.257184, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5063, R2 Score: -0.058645, MAE: 1.8417, MSE: 5.2758
Avg Latency (ms): 21.81, Avg Memory Before (MB): 312.96, Avg Memory After (MB): 312.97, Avg Max Memory (MB): 1356.81
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 2.6053, Cross Entropy: 1.256799, Accuracy: 0.4085, Precision: 0.1668, Recall: 0.4085, F1 Score: 0.2369, AUC: 0.4860, R2 Score: -0.052947, MAE: 1.9228, MSE: 5.7517
Training: Fold 2 - Total Loss: 2.5914, Cross Entropy: 1.248212, Accuracy: 0.3504, Precision: 0.2685, Recall: 0.3504, F1 Score: 0.2955, AUC: 0.4927, R2 Score: -0.122289, MAE: 1.9286, MSE: 5.7255
Training: Fold 3 - Total Loss: 2.6114, Cross Entropy: 1.269558, Accuracy: 0.3451, Precision: 0.2363, Recall: 0.3451, F1 Score: 0.2569, AUC: 0.4623, R2 Score: -0.136658, MAE: 1.9170, MSE: 5.7425
Training: Fold 4 - Total Loss: 2.8249, Cross Entropy: 1.239567, Accuracy: 0.4190, Precision: 0.3084, Recall: 0.4190, F1 Score: 0.2878, AUC: 0.5107, R2 Score: -0.225994, MAE: 2.0381, MSE: 6.5241
Validation: Fold 5 - Total Loss: 3.0835, Cross Entropy: 1.247472, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5182, R2 Score: -0.542761, MAE: 2.1667, MSE: 7.3677
Avg Latency (ms): 21.75, Avg Memory Before (MB): 313.62, Avg Memory After (MB): 313.62, Avg Max Memory (MB): 1357.46

Epoch 3/150
Training: Fold 1 - Total Loss: 2.7452, Cross Entropy: 1.242452, Accuracy: 0.4102, Precision: 0.4964, Recall: 0.4102, F1 Score: 0.2407, AUC: 0.5049, R2 Score: -0.183771, MAE: 2.0163, MSE: 6.2515
Training: Fold 2 - Total Loss: 2.4182, Cross Entropy: 1.238187, Accuracy: 0.3838, Precision: 0.2449, Recall: 0.3838, F1 Score: 0.2640, AUC: 0.4984, R2 Score: -0.017984, MAE: 1.8080, MSE: 5.1715
Training: Fold 3 - Total Loss: 2.3955, Cross Entropy: 1.256220, Accuracy: 0.3785, Precision: 0.2551, Recall: 0.3785, F1 Score: 0.2559, AUC: 0.4921, R2 Score: -0.014427, MAE: 1.7765, MSE: 5.0540
Training: Fold 4 - Total Loss: 2.5339, Cross Entropy: 1.255939, Accuracy: 0.3961, Precision: 0.2687, Recall: 0.3961, F1 Score: 0.2937, AUC: 0.4826, R2 Score: -0.018034, MAE: 1.8669, MSE: 5.5160
Validation: Fold 5 - Total Loss: 2.7547, Cross Entropy: 1.238761, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4982, R2 Score: -0.163050, MAE: 2.0130, MSE: 6.2919
Avg Latency (ms): 21.75, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 4/150
Training: Fold 1 - Total Loss: 2.5903, Cross Entropy: 1.242319, Accuracy: 0.3838, Precision: 0.2581, Recall: 0.3838, F1 Score: 0.2933, AUC: 0.4712, R2 Score: -0.084457, MAE: 1.9248, MSE: 5.7357
Training: Fold 2 - Total Loss: 2.4989, Cross Entropy: 1.241686, Accuracy: 0.3785, Precision: 0.2672, Recall: 0.3785, F1 Score: 0.2991, AUC: 0.4584, R2 Score: -0.086824, MAE: 1.8586, MSE: 5.4324
Training: Fold 3 - Total Loss: 2.3740, Cross Entropy: 1.262954, Accuracy: 0.3785, Precision: 0.1433, Recall: 0.3785, F1 Score: 0.2079, AUC: 0.4987, R2 Score: -0.003844, MAE: 1.7682, MSE: 4.9665
Training: Fold 4 - Total Loss: 2.6091, Cross Entropy: 1.247409, Accuracy: 0.4085, Precision: 0.2775, Recall: 0.4085, F1 Score: 0.3030, AUC: 0.4630, R2 Score: -0.091930, MAE: 1.9267, MSE: 5.7864
Validation: Fold 5 - Total Loss: 2.4408, Cross Entropy: 1.239482, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4664, R2 Score: -0.040989, MAE: 1.8397, MSE: 5.2439
Avg Latency (ms): 21.76, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 5/150
Training: Fold 1 - Total Loss: 2.5343, Cross Entropy: 1.240267, Accuracy: 0.4120, Precision: 0.4966, Recall: 0.4120, F1 Score: 0.2445, AUC: 0.4772, R2 Score: -0.038196, MAE: 1.8977, MSE: 5.5536
Training: Fold 2 - Total Loss: 2.4712, Cross Entropy: 1.238133, Accuracy: 0.3856, Precision: 0.2708, Recall: 0.3856, F1 Score: 0.2990, AUC: 0.4891, R2 Score: -0.073504, MAE: 1.8616, MSE: 5.3483
Training: Fold 3 - Total Loss: 2.4315, Cross Entropy: 1.253200, Accuracy: 0.3926, Precision: 0.3004, Recall: 0.3926, F1 Score: 0.2724, AUC: 0.4801, R2 Score: -0.048996, MAE: 1.8187, MSE: 5.1809
Training: Fold 4 - Total Loss: 2.5827, Cross Entropy: 1.243373, Accuracy: 0.4137, Precision: 0.2702, Recall: 0.4137, F1 Score: 0.2843, AUC: 0.4986, R2 Score: -0.067744, MAE: 1.9012, MSE: 5.7077
Validation: Fold 5 - Total Loss: 2.6523, Cross Entropy: 1.239428, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5555, R2 Score: -0.098560, MAE: 1.9480, MSE: 5.9491
Avg Latency (ms): 21.75, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 6/150
Training: Fold 1 - Total Loss: 2.8838, Cross Entropy: 1.244383, Accuracy: 0.3961, Precision: 0.2768, Recall: 0.3961, F1 Score: 0.3059, AUC: 0.4774, R2 Score: -0.263736, MAE: 2.0865, MSE: 6.7092
Training: Fold 2 - Total Loss: 2.4032, Cross Entropy: 1.237807, Accuracy: 0.4032, Precision: 0.2369, Recall: 0.4032, F1 Score: 0.2390, AUC: 0.4968, R2 Score: -0.018551, MAE: 1.8001, MSE: 5.1224
Training: Fold 3 - Total Loss: 2.3939, Cross Entropy: 1.256280, Accuracy: 0.3609, Precision: 0.2595, Recall: 0.3609, F1 Score: 0.2995, AUC: 0.4801, R2 Score: -0.026422, MAE: 1.7860, MSE: 5.0483
Training: Fold 4 - Total Loss: 2.5793, Cross Entropy: 1.252445, Accuracy: 0.4102, Precision: 0.2696, Recall: 0.4102, F1 Score: 0.2681, AUC: 0.4988, R2 Score: -0.064476, MAE: 1.9024, MSE: 5.6752
Validation: Fold 5 - Total Loss: 2.7143, Cross Entropy: 1.255275, Accuracy: 0.3873, Precision: 0.2544, Recall: 0.3873, F1 Score: 0.2972, AUC: 0.5268, R2 Score: -0.248069, MAE: 1.9939, MSE: 6.1187
Avg Latency (ms): 21.76, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 7/150
Training: Fold 1 - Total Loss: 2.7315, Cross Entropy: 1.248977, Accuracy: 0.4102, Precision: 0.2959, Recall: 0.4102, F1 Score: 0.2586, AUC: 0.4517, R2 Score: -0.170555, MAE: 1.9732, MSE: 6.1907
Training: Fold 2 - Total Loss: 2.5009, Cross Entropy: 1.245165, Accuracy: 0.3768, Precision: 0.2619, Recall: 0.3768, F1 Score: 0.3005, AUC: 0.4554, R2 Score: -0.072103, MAE: 1.8705, MSE: 5.4309
Training: Fold 3 - Total Loss: 2.3946, Cross Entropy: 1.253088, Accuracy: 0.3838, Precision: 0.2759, Recall: 0.3838, F1 Score: 0.2565, AUC: 0.5114, R2 Score: -0.022613, MAE: 1.8039, MSE: 5.0582
Training: Fold 4 - Total Loss: 2.6168, Cross Entropy: 1.260650, Accuracy: 0.3750, Precision: 0.2600, Recall: 0.3750, F1 Score: 0.3008, AUC: 0.4642, R2 Score: -0.091917, MAE: 1.9283, MSE: 5.7811
Validation: Fold 5 - Total Loss: 2.5143, Cross Entropy: 1.237091, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5410, R2 Score: -0.020268, MAE: 1.8496, MSE: 5.4945
Avg Latency (ms): 21.76, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 8/150
Training: Fold 1 - Total Loss: 2.8111, Cross Entropy: 1.246936, Accuracy: 0.3820, Precision: 0.2700, Recall: 0.3820, F1 Score: 0.2985, AUC: 0.4868, R2 Score: -0.206154, MAE: 2.0589, MSE: 6.4609
Training: Fold 2 - Total Loss: 2.6197, Cross Entropy: 1.247926, Accuracy: 0.3644, Precision: 0.2564, Recall: 0.3644, F1 Score: 0.2922, AUC: 0.4847, R2 Score: -0.145269, MAE: 1.9292, MSE: 5.8205
Training: Fold 3 - Total Loss: 2.4052, Cross Entropy: 1.268583, Accuracy: 0.3556, Precision: 0.2453, Recall: 0.3556, F1 Score: 0.2795, AUC: 0.5061, R2 Score: -0.024933, MAE: 1.7975, MSE: 5.0574
Training: Fold 4 - Total Loss: 2.7237, Cross Entropy: 1.253954, Accuracy: 0.3944, Precision: 0.2698, Recall: 0.3944, F1 Score: 0.3029, AUC: 0.5084, R2 Score: -0.148966, MAE: 1.9915, MSE: 6.1531
Validation: Fold 5 - Total Loss: 3.8058, Cross Entropy: 1.249251, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5142, R2 Score: -1.044676, MAE: 2.4937, MSE: 9.7712
Avg Latency (ms): 21.77, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 9/150
Training: Fold 1 - Total Loss: 3.0325, Cross Entropy: 1.243359, Accuracy: 0.4067, Precision: 0.2869, Recall: 0.4067, F1 Score: 0.3203, AUC: 0.4794, R2 Score: -0.362218, MAE: 2.1734, MSE: 7.2072
Training: Fold 2 - Total Loss: 2.4815, Cross Entropy: 1.243948, Accuracy: 0.3961, Precision: 0.2676, Recall: 0.3961, F1 Score: 0.2680, AUC: 0.4606, R2 Score: -0.074858, MAE: 1.8591, MSE: 5.3692
Training: Fold 3 - Total Loss: 2.5042, Cross Entropy: 1.257422, Accuracy: 0.3768, Precision: 0.2386, Recall: 0.3768, F1 Score: 0.2136, AUC: 0.4580, R2 Score: -0.089475, MAE: 1.8487, MSE: 5.4133
Training: Fold 4 - Total Loss: 2.6200, Cross Entropy: 1.252544, Accuracy: 0.4014, Precision: 0.2299, Recall: 0.4014, F1 Score: 0.2510, AUC: 0.4939, R2 Score: -0.069118, MAE: 1.9272, MSE: 5.8107
Validation: Fold 5 - Total Loss: 2.6912, Cross Entropy: 1.240244, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5535, R2 Score: -0.111522, MAE: 1.9723, MSE: 6.0767
Avg Latency (ms): 21.77, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 10/150
Training: Fold 1 - Total Loss: 2.6209, Cross Entropy: 1.245424, Accuracy: 0.4102, Precision: 0.3060, Recall: 0.4102, F1 Score: 0.2609, AUC: 0.4779, R2 Score: -0.101087, MAE: 1.9653, MSE: 5.8303
Training: Fold 2 - Total Loss: 2.5346, Cross Entropy: 1.237977, Accuracy: 0.3750, Precision: 0.2636, Recall: 0.3750, F1 Score: 0.2950, AUC: 0.5048, R2 Score: -0.112395, MAE: 1.8825, MSE: 5.5599
Training: Fold 3 - Total Loss: 2.5922, Cross Entropy: 1.265285, Accuracy: 0.3451, Precision: 0.2461, Recall: 0.3451, F1 Score: 0.2873, AUC: 0.4745, R2 Score: -0.158558, MAE: 1.9232, MSE: 5.6883
Training: Fold 4 - Total Loss: 2.6177, Cross Entropy: 1.257722, Accuracy: 0.4208, Precision: 0.3816, Recall: 0.4208, F1 Score: 0.2535, AUC: 0.4765, R2 Score: -0.066261, MAE: 1.9512, MSE: 5.7911
Validation: Fold 5 - Total Loss: 2.6416, Cross Entropy: 1.236954, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5595, R2 Score: -0.083168, MAE: 1.9407, MSE: 5.9192
Avg Latency (ms): 21.75, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 11/150
Training: Fold 1 - Total Loss: 2.5225, Cross Entropy: 1.243869, Accuracy: 0.3996, Precision: 0.2764, Recall: 0.3996, F1 Score: 0.2836, AUC: 0.4937, R2 Score: -0.041616, MAE: 1.8898, MSE: 5.5059
Training: Fold 2 - Total Loss: 2.6767, Cross Entropy: 1.243534, Accuracy: 0.3891, Precision: 0.2618, Recall: 0.3891, F1 Score: 0.2718, AUC: 0.4770, R2 Score: -0.183976, MAE: 1.9923, MSE: 6.0206
Training: Fold 3 - Total Loss: 2.5950, Cross Entropy: 1.260772, Accuracy: 0.3433, Precision: 0.2421, Recall: 0.3433, F1 Score: 0.2820, AUC: 0.4831, R2 Score: -0.160150, MAE: 1.9152, MSE: 5.7083
Training: Fold 4 - Total Loss: 2.5630, Cross Entropy: 1.241021, Accuracy: 0.4190, Precision: 0.3809, Recall: 0.4190, F1 Score: 0.2525, AUC: 0.5028, R2 Score: -0.059530, MAE: 1.9077, MSE: 5.6475
Validation: Fold 5 - Total Loss: 2.4396, Cross Entropy: 1.240105, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5273, R2 Score: 0.004912, MAE: 1.8075, MSE: 5.2386
Avg Latency (ms): 21.77, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 12/150
Training: Fold 1 - Total Loss: 2.5532, Cross Entropy: 1.241598, Accuracy: 0.3697, Precision: 0.2761, Recall: 0.3697, F1 Score: 0.3149, AUC: 0.4869, R2 Score: -0.054505, MAE: 1.8884, MSE: 5.6136
Training: Fold 2 - Total Loss: 2.4649, Cross Entropy: 1.241276, Accuracy: 0.4067, Precision: 0.3098, Recall: 0.4067, F1 Score: 0.2565, AUC: 0.5112, R2 Score: -0.056952, MAE: 1.8523, MSE: 5.3199
Training: Fold 3 - Total Loss: 2.4587, Cross Entropy: 1.252609, Accuracy: 0.3398, Precision: 0.2268, Recall: 0.3398, F1 Score: 0.2551, AUC: 0.5102, R2 Score: -0.080430, MAE: 1.8547, MSE: 5.2728
Training: Fold 4 - Total Loss: 2.6911, Cross Entropy: 1.252328, Accuracy: 0.3856, Precision: 0.2659, Recall: 0.3856, F1 Score: 0.3076, AUC: 0.4851, R2 Score: -0.134150, MAE: 1.9406, MSE: 6.0483
Validation: Fold 5 - Total Loss: 2.4261, Cross Entropy: 1.241987, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5367, R2 Score: 0.007940, MAE: 1.8085, MSE: 5.1889
Avg Latency (ms): 21.78, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 13/150
Training: Fold 1 - Total Loss: 2.7235, Cross Entropy: 1.238601, Accuracy: 0.4014, Precision: 0.1657, Recall: 0.4014, F1 Score: 0.2346, AUC: 0.4882, R2 Score: -0.172801, MAE: 1.9950, MSE: 6.1884
Training: Fold 2 - Total Loss: 2.7556, Cross Entropy: 1.238069, Accuracy: 0.3979, Precision: 0.2535, Recall: 0.3979, F1 Score: 0.2448, AUC: 0.5004, R2 Score: -0.246285, MAE: 1.9945, MSE: 6.2965
Training: Fold 3 - Total Loss: 2.3928, Cross Entropy: 1.259754, Accuracy: 0.3257, Precision: 0.2221, Recall: 0.3257, F1 Score: 0.2547, AUC: 0.4701, R2 Score: -0.027599, MAE: 1.7830, MSE: 5.0365
Training: Fold 4 - Total Loss: 2.6015, Cross Entropy: 1.244094, Accuracy: 0.4155, Precision: 0.1737, Recall: 0.4155, F1 Score: 0.2450, AUC: 0.4830, R2 Score: -0.077975, MAE: 1.9192, MSE: 5.7689
Validation: Fold 5 - Total Loss: 2.5933, Cross Entropy: 1.236778, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5321, R2 Score: -0.062382, MAE: 1.9064, MSE: 5.7585
Avg Latency (ms): 21.75, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 14/150
Training: Fold 1 - Total Loss: 2.6106, Cross Entropy: 1.244444, Accuracy: 0.3961, Precision: 0.1991, Recall: 0.3961, F1 Score: 0.2399, AUC: 0.4579, R2 Score: -0.091821, MAE: 1.9305, MSE: 5.7985
Training: Fold 2 - Total Loss: 2.4825, Cross Entropy: 1.239944, Accuracy: 0.3961, Precision: 0.2402, Recall: 0.3961, F1 Score: 0.2587, AUC: 0.4810, R2 Score: -0.070900, MAE: 1.8229, MSE: 5.3819
Training: Fold 3 - Total Loss: 2.4946, Cross Entropy: 1.258746, Accuracy: 0.3609, Precision: 0.2481, Recall: 0.3609, F1 Score: 0.2831, AUC: 0.4674, R2 Score: -0.093855, MAE: 1.8317, MSE: 5.3781
Training: Fold 4 - Total Loss: 2.5463, Cross Entropy: 1.237745, Accuracy: 0.4190, Precision: 0.3809, Recall: 0.4190, F1 Score: 0.2525, AUC: 0.5212, R2 Score: -0.046885, MAE: 1.8787, MSE: 5.5995
Validation: Fold 5 - Total Loss: 2.5779, Cross Entropy: 1.248198, Accuracy: 0.3803, Precision: 0.1483, Recall: 0.3803, F1 Score: 0.2134, AUC: 0.5350, R2 Score: -0.130065, MAE: 1.9267, MSE: 5.6806
Avg Latency (ms): 21.76, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 15/150
Training: Fold 1 - Total Loss: 2.6531, Cross Entropy: 1.241247, Accuracy: 0.4049, Precision: 0.2900, Recall: 0.4049, F1 Score: 0.2933, AUC: 0.4968, R2 Score: -0.117408, MAE: 1.9434, MSE: 5.9475
Training: Fold 2 - Total Loss: 2.4435, Cross Entropy: 1.242186, Accuracy: 0.4032, Precision: 0.1625, Recall: 0.4032, F1 Score: 0.2317, AUC: 0.4707, R2 Score: -0.044851, MAE: 1.7944, MSE: 5.2465
Training: Fold 3 - Total Loss: 2.4110, Cross Entropy: 1.255356, Accuracy: 0.3785, Precision: 0.2786, Recall: 0.3785, F1 Score: 0.3069, AUC: 0.5154, R2 Score: -0.044523, MAE: 1.8136, MSE: 5.1075
Training: Fold 4 - Total Loss: 2.6641, Cross Entropy: 1.246531, Accuracy: 0.4173, Precision: 0.1741, Recall: 0.4173, F1 Score: 0.2457, AUC: 0.5165, R2 Score: -0.105209, MAE: 1.9651, MSE: 5.9717
Validation: Fold 5 - Total Loss: 3.3581, Cross Entropy: 1.236800, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5534, R2 Score: -0.502897, MAE: 2.3720, MSE: 8.3077
Avg Latency (ms): 21.76, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 16/150
Training: Fold 1 - Total Loss: 3.0713, Cross Entropy: 1.239183, Accuracy: 0.3838, Precision: 0.2562, Recall: 0.3838, F1 Score: 0.2782, AUC: 0.5175, R2 Score: -0.391874, MAE: 2.1938, MSE: 7.3463
Training: Fold 2 - Total Loss: 2.7013, Cross Entropy: 1.232381, Accuracy: 0.4032, Precision: 0.1625, Recall: 0.4032, F1 Score: 0.2317, AUC: 0.5284, R2 Score: -0.233617, MAE: 1.9605, MSE: 6.1288
Training: Fold 3 - Total Loss: 2.4513, Cross Entropy: 1.252096, Accuracy: 0.3574, Precision: 0.2508, Recall: 0.3574, F1 Score: 0.2922, AUC: 0.5135, R2 Score: -0.060748, MAE: 1.8120, MSE: 5.2496
Training: Fold 4 - Total Loss: 2.6788, Cross Entropy: 1.244646, Accuracy: 0.4208, Precision: 0.3303, Recall: 0.4208, F1 Score: 0.2538, AUC: 0.4900, R2 Score: -0.130614, MAE: 1.9484, MSE: 6.0251
Validation: Fold 5 - Total Loss: 2.4901, Cross Entropy: 1.239697, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5403, R2 Score: -0.008549, MAE: 1.8315, MSE: 5.4077
Avg Latency (ms): 21.81, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 17/150
Training: Fold 1 - Total Loss: 2.5537, Cross Entropy: 1.238311, Accuracy: 0.4137, Precision: 0.3232, Recall: 0.4137, F1 Score: 0.2626, AUC: 0.5014, R2 Score: -0.058351, MAE: 1.9297, MSE: 5.6231
Training: Fold 2 - Total Loss: 2.4050, Cross Entropy: 1.233710, Accuracy: 0.3873, Precision: 0.2955, Recall: 0.3873, F1 Score: 0.3263, AUC: 0.5295, R2 Score: -0.030637, MAE: 1.7984, MSE: 5.1381
Training: Fold 3 - Total Loss: 2.5352, Cross Entropy: 1.264131, Accuracy: 0.3803, Precision: 0.2528, Recall: 0.3803, F1 Score: 0.2491, AUC: 0.5117, R2 Score: -0.118346, MAE: 1.8818, MSE: 5.5010
Training: Fold 4 - Total Loss: 2.8571, Cross Entropy: 1.249969, Accuracy: 0.4190, Precision: 0.3809, Recall: 0.4190, F1 Score: 0.2525, AUC: 0.4978, R2 Score: -0.238967, MAE: 2.0809, MSE: 6.6071
Validation: Fold 5 - Total Loss: 2.5048, Cross Entropy: 1.236237, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5650, R2 Score: -0.002124, MAE: 1.8412, MSE: 5.4649
Avg Latency (ms): 21.77, Avg Memory Before (MB): 314.87, Avg Memory After (MB): 314.87, Avg Max Memory (MB): 1358.71

Epoch 18/150
Training: Fold 1 - Total Loss: 2.6286, Cross Entropy: 1.233865, Accuracy: 0.4085, Precision: 0.1668, Recall: 0.4085, F1 Score: 0.2369, AUC: 0.5117, R2 Score: -0.105349, MAE: 1.9762, MSE: 5.8829
Training: Fold 2 - Total Loss: 2.5588, Cross Entropy: 1.234411, Accuracy: 0.4102, Precision: 0.2937, Recall: 0.4102, F1 Score: 0.2564, AUC: 0.5015, R2 Score: -0.127942, MAE: 1.8924, MSE: 5.6491
Training: Fold 3 - Total Loss: 2.3778, Cross Entropy: 1.252898, Accuracy: 0.3908, Precision: 0.2756, Recall: 0.3908, F1 Score: 0.3128, AUC: 0.5135, R2 Score: -0.009707, MAE: 1.7743, MSE: 5.0025
Training: Fold 4 - Total Loss: 2.5507, Cross Entropy: 1.243617, Accuracy: 0.4085, Precision: 0.2254, Recall: 0.4085, F1 Score: 0.2524, AUC: 0.5144, R2 Score: -0.043885, MAE: 1.8870, MSE: 5.6004
Validation: Fold 5 - Total Loss: 2.4891, Cross Entropy: 1.236774, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5580, R2 Score: -0.003094, MAE: 1.8291, MSE: 5.4111

### Vision Transformer (ViT-Tiny)

The **Vision Transformer (ViT)** introduces **self-attention mechanisms** to image classification, a method originally developed for natural language processing (NLP). Unlike CNNs, which rely on local feature extraction, ViT processes images as a sequence of **non-overlapping patches** and learns global dependencies. The **ViT-Tiny** model is a lightweight variant of ViT, optimized for lower computational costs while retaining transformer-based advantages such as **better scalability and improved performance on large datasets**.

- **Paper:** Dosovitskiy, A., Beyer, L., Kolesnikov, A., Weissenborn, D., et al. (2021). *An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale*. [ICLR](https://arxiv.org/abs/2010.11929).

In [ ]:
main(ARCH)

====================================================================================================
Training Model: vit-tiny
Initial Backbone Model Size: 22.92 MB
Modified Backbone Model Size: 22.25 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 18.3265, Cross Entropy: 1.523179, Accuracy: 0.1092, Precision: 0.4376, Recall: 0.1092, F1 Score: 0.0792, AUC: 0.4885, R2 Score: -10.079400, MAE: 7.1800, MSE: 57.5344
Training: Fold 2 - Total Loss: 13.0305, Cross Entropy: 1.490779, Accuracy: 0.0757, Precision: 0.3919, Recall: 0.0757, F1 Score: 0.0311, AUC: 0.4990, R2 Score: -7.084149, MAE: 5.9246, MSE: 39.9564
Training: Fold 3 - Total Loss: 9.4026, Cross Entropy: 1.429735, Accuracy: 0.1620, Precision: 0.2038, Recall: 0.1620, F1 Score: 0.1469, AUC: 0.4785, R2 Score: -4.803463, MAE: 4.8402, MSE: 28.0058
Training: Fold 4 - Total Loss: 6.9632, Cross Entropy: 1.354489, Accuracy: 0.3662, Precision: 0.2832, Recall: 0.3662, F1 Score: 0.2993, AUC: 0.5186, R2 Score: -2.804101, MAE: 3.9961, MSE: 20.0501
Validation: Fold 5 - Total Loss: 5.8701, Cross Entropy: 1.327109, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5841, R2 Score: -2.034954, MAE: 3.5669, MSE: 16.4705
Avg Latency (ms): 4.77, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 4.6449, Cross Entropy: 1.299404, Accuracy: 0.3996, Precision: 0.2793, Recall: 0.3996, F1 Score: 0.2816, AUC: 0.5108, R2 Score: -1.397662, MAE: 3.0184, MSE: 12.4510
Training: Fold 2 - Total Loss: 3.3314, Cross Entropy: 1.269895, Accuracy: 0.3873, Precision: 0.2364, Recall: 0.3873, F1 Score: 0.2452, AUC: 0.5013, R2 Score: -0.641113, MAE: 2.3733, MSE: 8.1417
Training: Fold 3 - Total Loss: 2.6771, Cross Entropy: 1.280573, Accuracy: 0.3539, Precision: 0.2281, Recall: 0.3539, F1 Score: 0.2403, AUC: 0.4602, R2 Score: -0.241912, MAE: 1.9695, MSE: 5.9357
Training: Fold 4 - Total Loss: 2.6151, Cross Entropy: 1.257303, Accuracy: 0.4032, Precision: 0.2826, Recall: 0.4032, F1 Score: 0.3221, AUC: 0.4850, R2 Score: -0.092427, MAE: 1.9333, MSE: 5.7833
Validation: Fold 5 - Total Loss: 2.4791, Cross Entropy: 1.238708, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6049, R2 Score: -0.009889, MAE: 1.8195, MSE: 5.3733
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4975, Cross Entropy: 1.247782, Accuracy: 0.3803, Precision: 0.2500, Recall: 0.3803, F1 Score: 0.2692, AUC: 0.4919, R2 Score: -0.050203, MAE: 1.8739, MSE: 5.4135
Training: Fold 2 - Total Loss: 2.4056, Cross Entropy: 1.230418, Accuracy: 0.4102, Precision: 0.2966, Recall: 0.4102, F1 Score: 0.3405, AUC: 0.5371, R2 Score: -0.004478, MAE: 1.8086, MSE: 5.1478
Training: Fold 3 - Total Loss: 2.4030, Cross Entropy: 1.261150, Accuracy: 0.3715, Precision: 0.2539, Recall: 0.3715, F1 Score: 0.2553, AUC: 0.4956, R2 Score: -0.010489, MAE: 1.7889, MSE: 5.0674
Training: Fold 4 - Total Loss: 2.5345, Cross Entropy: 1.260183, Accuracy: 0.3504, Precision: 0.2540, Recall: 0.3504, F1 Score: 0.2944, AUC: 0.4690, R2 Score: -0.051898, MAE: 1.8723, MSE: 5.5079
Validation: Fold 5 - Total Loss: 2.4472, Cross Entropy: 1.237542, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6235, R2 Score: -0.000664, MAE: 1.8110, MSE: 5.2698
Avg Latency (ms): 4.65, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 4/150
Training: Fold 1 - Total Loss: 2.5048, Cross Entropy: 1.257845, Accuracy: 0.3803, Precision: 0.2475, Recall: 0.3803, F1 Score: 0.2734, AUC: 0.4679, R2 Score: -0.043958, MAE: 1.8703, MSE: 5.4145
Training: Fold 2 - Total Loss: 2.4112, Cross Entropy: 1.241875, Accuracy: 0.3750, Precision: 0.2534, Recall: 0.3750, F1 Score: 0.2795, AUC: 0.4953, R2 Score: -0.043126, MAE: 1.8094, MSE: 5.1395
Training: Fold 3 - Total Loss: 2.3966, Cross Entropy: 1.269438, Accuracy: 0.3486, Precision: 0.2299, Recall: 0.3486, F1 Score: 0.2502, AUC: 0.4404, R2 Score: -0.037558, MAE: 1.7821, MSE: 5.0265
Training: Fold 4 - Total Loss: 2.5253, Cross Entropy: 1.251313, Accuracy: 0.3996, Precision: 0.2420, Recall: 0.3996, F1 Score: 0.2663, AUC: 0.4862, R2 Score: -0.037109, MAE: 1.8659, MSE: 5.4979
Validation: Fold 5 - Total Loss: 2.4395, Cross Entropy: 1.237645, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6265, R2 Score: -0.000688, MAE: 1.8134, MSE: 5.2438
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 5/150
Training: Fold 1 - Total Loss: 2.4912, Cross Entropy: 1.238201, Accuracy: 0.4049, Precision: 0.2802, Recall: 0.4049, F1 Score: 0.2869, AUC: 0.5022, R2 Score: -0.051104, MAE: 1.8731, MSE: 5.4148
Training: Fold 2 - Total Loss: 2.3964, Cross Entropy: 1.235355, Accuracy: 0.4049, Precision: 0.2760, Recall: 0.4049, F1 Score: 0.2793, AUC: 0.5223, R2 Score: 0.010393, MAE: 1.8015, MSE: 5.1057
Training: Fold 3 - Total Loss: 2.3949, Cross Entropy: 1.263855, Accuracy: 0.3521, Precision: 0.2501, Recall: 0.3521, F1 Score: 0.2917, AUC: 0.4693, R2 Score: -0.044204, MAE: 1.7844, MSE: 5.0341
Training: Fold 4 - Total Loss: 2.5331, Cross Entropy: 1.251283, Accuracy: 0.4085, Precision: 0.2772, Recall: 0.4085, F1 Score: 0.2969, AUC: 0.4913, R2 Score: -0.040768, MAE: 1.8724, MSE: 5.5239
Validation: Fold 5 - Total Loss: 2.4369, Cross Entropy: 1.235795, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6173, R2 Score: -0.000957, MAE: 1.8141, MSE: 5.2393
Avg Latency (ms): 4.63, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4985, Cross Entropy: 1.240759, Accuracy: 0.4067, Precision: 0.2949, Recall: 0.4067, F1 Score: 0.2873, AUC: 0.4958, R2 Score: -0.079238, MAE: 1.8736, MSE: 5.4333
Training: Fold 2 - Total Loss: 2.4178, Cross Entropy: 1.244664, Accuracy: 0.3838, Precision: 0.2711, Recall: 0.3838, F1 Score: 0.2977, AUC: 0.4703, R2 Score: -0.049761, MAE: 1.8130, MSE: 5.1551
Training: Fold 3 - Total Loss: 2.3923, Cross Entropy: 1.263976, Accuracy: 0.3732, Precision: 0.2516, Recall: 0.3732, F1 Score: 0.2720, AUC: 0.4687, R2 Score: -0.035591, MAE: 1.7822, MSE: 5.0250
Training: Fold 4 - Total Loss: 2.5313, Cross Entropy: 1.266164, Accuracy: 0.3891, Precision: 0.2599, Recall: 0.3891, F1 Score: 0.2911, AUC: 0.4392, R2 Score: -0.027350, MAE: 1.8688, MSE: 5.4834
Validation: Fold 5 - Total Loss: 2.4401, Cross Entropy: 1.234337, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6101, R2 Score: -0.001064, MAE: 1.8124, MSE: 5.2535
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4821, Cross Entropy: 1.232229, Accuracy: 0.4208, Precision: 0.2878, Recall: 0.4208, F1 Score: 0.3133, AUC: 0.5295, R2 Score: -0.057699, MAE: 1.8654, MSE: 5.3984
Training: Fold 2 - Total Loss: 2.4079, Cross Entropy: 1.237304, Accuracy: 0.3996, Precision: 0.2773, Recall: 0.3996, F1 Score: 0.2899, AUC: 0.4996, R2 Score: -0.022541, MAE: 1.8074, MSE: 5.1393
Training: Fold 3 - Total Loss: 2.3838, Cross Entropy: 1.254877, Accuracy: 0.3680, Precision: 0.2595, Recall: 0.3680, F1 Score: 0.2967, AUC: 0.5032, R2 Score: -0.001004, MAE: 1.7806, MSE: 5.0179
Training: Fold 4 - Total Loss: 2.5397, Cross Entropy: 1.254647, Accuracy: 0.3944, Precision: 0.2733, Recall: 0.3944, F1 Score: 0.3081, AUC: 0.4960, R2 Score: -0.047597, MAE: 1.8717, MSE: 5.5382
Validation: Fold 5 - Total Loss: 2.4335, Cross Entropy: 1.233541, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6143, R2 Score: -0.003066, MAE: 1.8160, MSE: 5.2334
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4939, Cross Entropy: 1.235412, Accuracy: 0.4085, Precision: 0.2907, Recall: 0.4085, F1 Score: 0.2549, AUC: 0.5511, R2 Score: -0.027706, MAE: 1.8670, MSE: 5.4304
Training: Fold 2 - Total Loss: 2.4421, Cross Entropy: 1.253729, Accuracy: 0.3468, Precision: 0.2589, Recall: 0.3468, F1 Score: 0.2947, AUC: 0.4892, R2 Score: -0.074153, MAE: 1.8217, MSE: 5.2150
Training: Fold 3 - Total Loss: 2.4133, Cross Entropy: 1.261507, Accuracy: 0.3680, Precision: 0.2454, Recall: 0.3680, F1 Score: 0.2569, AUC: 0.4854, R2 Score: -0.029482, MAE: 1.7928, MSE: 5.1010
Training: Fold 4 - Total Loss: 2.5252, Cross Entropy: 1.253409, Accuracy: 0.3680, Precision: 0.2521, Recall: 0.3680, F1 Score: 0.2935, AUC: 0.4699, R2 Score: -0.031186, MAE: 1.8751, MSE: 5.4927
Validation: Fold 5 - Total Loss: 2.4436, Cross Entropy: 1.231594, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6142, R2 Score: -0.001544, MAE: 1.8111, MSE: 5.2716
Avg Latency (ms): 4.63, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 9/150
Training: Fold 1 - Total Loss: 2.5088, Cross Entropy: 1.252945, Accuracy: 0.3732, Precision: 0.2113, Recall: 0.3732, F1 Score: 0.2417, AUC: 0.4716, R2 Score: -0.039313, MAE: 1.8731, MSE: 5.4393
Training: Fold 2 - Total Loss: 2.3991, Cross Entropy: 1.240788, Accuracy: 0.4155, Precision: 0.2937, Recall: 0.4155, F1 Score: 0.2995, AUC: 0.4881, R2 Score: -0.037541, MAE: 1.8009, MSE: 5.1018
Training: Fold 3 - Total Loss: 2.4029, Cross Entropy: 1.263795, Accuracy: 0.3803, Precision: 0.2578, Recall: 0.3803, F1 Score: 0.2623, AUC: 0.4551, R2 Score: -0.048099, MAE: 1.7897, MSE: 5.0610
Training: Fold 4 - Total Loss: 2.5258, Cross Entropy: 1.245322, Accuracy: 0.3785, Precision: 0.2467, Recall: 0.3785, F1 Score: 0.2828, AUC: 0.5036, R2 Score: -0.052021, MAE: 1.8768, MSE: 5.5137
Validation: Fold 5 - Total Loss: 2.4361, Cross Entropy: 1.232688, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6143, R2 Score: -0.000934, MAE: 1.8134, MSE: 5.2440
Avg Latency (ms): 4.63, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 10/150
Training: Fold 1 - Total Loss: 2.5063, Cross Entropy: 1.246757, Accuracy: 0.4102, Precision: 0.2971, Recall: 0.4102, F1 Score: 0.2838, AUC: 0.4710, R2 Score: -0.018070, MAE: 1.8732, MSE: 5.4454
Training: Fold 2 - Total Loss: 2.4364, Cross Entropy: 1.248909, Accuracy: 0.3768, Precision: 0.2691, Recall: 0.3768, F1 Score: 0.3104, AUC: 0.4681, R2 Score: -0.049148, MAE: 1.8208, MSE: 5.2072
Training: Fold 3 - Total Loss: 2.3918, Cross Entropy: 1.262772, Accuracy: 0.3539, Precision: 0.2469, Recall: 0.3539, F1 Score: 0.2819, AUC: 0.4623, R2 Score: -0.043514, MAE: 1.7818, MSE: 5.0262
Training: Fold 4 - Total Loss: 2.5105, Cross Entropy: 1.245269, Accuracy: 0.4190, Precision: 0.2916, Recall: 0.4190, F1 Score: 0.2647, AUC: 0.5224, R2 Score: -0.054455, MAE: 1.8643, MSE: 5.4627
Validation: Fold 5 - Total Loss: 2.4308, Cross Entropy: 1.229474, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6234, R2 Score: -0.002468, MAE: 1.8157, MSE: 5.2338
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4902, Cross Entropy: 1.237848, Accuracy: 0.4067, Precision: 0.2892, Recall: 0.4067, F1 Score: 0.3035, AUC: 0.5023, R2 Score: -0.053958, MAE: 1.8714, MSE: 5.4123
Training: Fold 2 - Total Loss: 2.4086, Cross Entropy: 1.230463, Accuracy: 0.3820, Precision: 0.2582, Recall: 0.3820, F1 Score: 0.2762, AUC: 0.5366, R2 Score: -0.011222, MAE: 1.8085, MSE: 5.1577
Training: Fold 3 - Total Loss: 2.3975, Cross Entropy: 1.256963, Accuracy: 0.3627, Precision: 0.2510, Recall: 0.3627, F1 Score: 0.2816, AUC: 0.4756, R2 Score: -0.053444, MAE: 1.7844, MSE: 5.0587
Training: Fold 4 - Total Loss: 2.5108, Cross Entropy: 1.243618, Accuracy: 0.4190, Precision: 0.2937, Recall: 0.4190, F1 Score: 0.3275, AUC: 0.5156, R2 Score: -0.019759, MAE: 1.8607, MSE: 5.4674
Validation: Fold 5 - Total Loss: 2.4317, Cross Entropy: 1.229280, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6297, R2 Score: -0.001903, MAE: 1.8148, MSE: 5.2372
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 12/150
Training: Fold 1 - Total Loss: 2.4883, Cross Entropy: 1.236920, Accuracy: 0.3961, Precision: 0.2500, Recall: 0.3961, F1 Score: 0.2547, AUC: 0.5291, R2 Score: -0.024783, MAE: 1.8685, MSE: 5.4082
Training: Fold 2 - Total Loss: 2.4031, Cross Entropy: 1.229402, Accuracy: 0.4085, Precision: 0.2900, Recall: 0.4085, F1 Score: 0.3249, AUC: 0.5232, R2 Score: -0.022918, MAE: 1.8078, MSE: 5.1418
Training: Fold 3 - Total Loss: 2.3858, Cross Entropy: 1.251682, Accuracy: 0.3662, Precision: 0.2497, Recall: 0.3662, F1 Score: 0.2589, AUC: 0.5273, R2 Score: -0.029945, MAE: 1.7857, MSE: 5.0322
Training: Fold 4 - Total Loss: 2.5197, Cross Entropy: 1.250675, Accuracy: 0.3873, Precision: 0.2634, Recall: 0.3873, F1 Score: 0.3009, AUC: 0.4917, R2 Score: -0.055521, MAE: 1.8659, MSE: 5.4809
Validation: Fold 5 - Total Loss: 2.4310, Cross Entropy: 1.225429, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6341, R2 Score: -0.001888, MAE: 1.8139, MSE: 5.2440
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4911, Cross Entropy: 1.251431, Accuracy: 0.3680, Precision: 0.2570, Recall: 0.3680, F1 Score: 0.2946, AUC: 0.4748, R2 Score: -0.043636, MAE: 1.8590, MSE: 5.3838
Training: Fold 2 - Total Loss: 2.4217, Cross Entropy: 1.243000, Accuracy: 0.3961, Precision: 0.2639, Recall: 0.3961, F1 Score: 0.2853, AUC: 0.4860, R2 Score: -0.043494, MAE: 1.8115, MSE: 5.1721
Training: Fold 3 - Total Loss: 2.3736, Cross Entropy: 1.249756, Accuracy: 0.3715, Precision: 0.2620, Recall: 0.3715, F1 Score: 0.2961, AUC: 0.5065, R2 Score: -0.058835, MAE: 1.7753, MSE: 4.9960
Training: Fold 4 - Total Loss: 2.5083, Cross Entropy: 1.233555, Accuracy: 0.4243, Precision: 0.2916, Recall: 0.4243, F1 Score: 0.3082, AUC: 0.5415, R2 Score: -0.027699, MAE: 1.8673, MSE: 5.4827
Validation: Fold 5 - Total Loss: 2.4234, Cross Entropy: 1.216298, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6415, R2 Score: -0.007734, MAE: 1.8168, MSE: 5.2399
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 14/150
Training: Fold 1 - Total Loss: 2.5206, Cross Entropy: 1.242271, Accuracy: 0.3996, Precision: 0.2896, Recall: 0.3996, F1 Score: 0.3342, AUC: 0.5229, R2 Score: -0.022786, MAE: 1.8902, MSE: 5.5034
Training: Fold 2 - Total Loss: 2.4045, Cross Entropy: 1.232709, Accuracy: 0.4155, Precision: 0.2973, Recall: 0.4155, F1 Score: 0.3098, AUC: 0.5307, R2 Score: -0.063183, MAE: 1.8049, MSE: 5.1387
Training: Fold 3 - Total Loss: 2.3876, Cross Entropy: 1.245881, Accuracy: 0.3944, Precision: 0.2768, Recall: 0.3944, F1 Score: 0.3171, AUC: 0.5312, R2 Score: -0.008540, MAE: 1.7879, MSE: 5.0515
Training: Fold 4 - Total Loss: 2.5008, Cross Entropy: 1.234017, Accuracy: 0.4243, Precision: 0.2933, Recall: 0.4243, F1 Score: 0.3271, AUC: 0.5579, R2 Score: -0.030848, MAE: 1.8609, MSE: 5.4567
Validation: Fold 5 - Total Loss: 2.4193, Cross Entropy: 1.206961, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6469, R2 Score: -0.010015, MAE: 1.8169, MSE: 5.2481
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 15/150
Training: Fold 1 - Total Loss: 2.4802, Cross Entropy: 1.221320, Accuracy: 0.4507, Precision: 0.3438, Recall: 0.4507, F1 Score: 0.3424, AUC: 0.5682, R2 Score: -0.036356, MAE: 1.8717, MSE: 5.4176
Training: Fold 2 - Total Loss: 2.4100, Cross Entropy: 1.234772, Accuracy: 0.4155, Precision: 0.3046, Recall: 0.4155, F1 Score: 0.3515, AUC: 0.5309, R2 Score: -0.077834, MAE: 1.8109, MSE: 5.1520
Training: Fold 3 - Total Loss: 2.3785, Cross Entropy: 1.239252, Accuracy: 0.4120, Precision: 0.5084, Recall: 0.4120, F1 Score: 0.3100, AUC: 0.5690, R2 Score: -0.037592, MAE: 1.7842, MSE: 5.0368
Training: Fold 4 - Total Loss: 2.5247, Cross Entropy: 1.234292, Accuracy: 0.4366, Precision: 0.5116, Recall: 0.4366, F1 Score: 0.3643, AUC: 0.5462, R2 Score: -0.038824, MAE: 1.8796, MSE: 5.5355
Validation: Fold 5 - Total Loss: 2.4193, Cross Entropy: 1.211789, Accuracy: 0.4296, Precision: 0.2974, Recall: 0.4296, F1 Score: 0.3093, AUC: 0.6474, R2 Score: -0.007808, MAE: 1.8177, MSE: 5.2369
Avg Latency (ms): 4.64, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51
Best model saved with Accuracy: 0.4296

Epoch 16/150
Training: Fold 1 - Total Loss: 2.4855, Cross Entropy: 1.223922, Accuracy: 0.4560, Precision: 0.3473, Recall: 0.4560, F1 Score: 0.3554, AUC: 0.5484, R2 Score: -0.052589, MAE: 1.8669, MSE: 5.4291
Training: Fold 2 - Total Loss: 2.3885, Cross Entropy: 1.212691, Accuracy: 0.4366, Precision: 0.3139, Recall: 0.4366, F1 Score: 0.3598, AUC: 0.5794, R2 Score: -0.026515, MAE: 1.8092, MSE: 5.1320
Training: Fold 3 - Total Loss: 2.3644, Cross Entropy: 1.226595, Accuracy: 0.4454, Precision: 0.3146, Recall: 0.4454, F1 Score: 0.3607, AUC: 0.5670, R2 Score: -0.039034, MAE: 1.7816, MSE: 5.0194
Training: Fold 4 - Total Loss: 2.5150, Cross Entropy: 1.242046, Accuracy: 0.4419, Precision: 0.3111, Recall: 0.4419, F1 Score: 0.3556, AUC: 0.5303, R2 Score: -0.039279, MAE: 1.8703, MSE: 5.4853
Validation: Fold 5 - Total Loss: 2.4086, Cross Entropy: 1.195113, Accuracy: 0.4225, Precision: 0.2831, Recall: 0.4225, F1 Score: 0.3194, AUC: 0.6488, R2 Score: -0.008076, MAE: 1.8169, MSE: 5.2400
Avg Latency (ms): 4.65, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4761, Cross Entropy: 1.207349, Accuracy: 0.4683, Precision: 0.3413, Recall: 0.4683, F1 Score: 0.3919, AUC: 0.5781, R2 Score: -0.039982, MAE: 1.8717, MSE: 5.4366
Training: Fold 2 - Total Loss: 2.3825, Cross Entropy: 1.209754, Accuracy: 0.4507, Precision: 0.3240, Recall: 0.4507, F1 Score: 0.3741, AUC: 0.5944, R2 Score: -0.022101, MAE: 1.8072, MSE: 5.1189
Training: Fold 3 - Total Loss: 2.3892, Cross Entropy: 1.246334, Accuracy: 0.4120, Precision: 0.2914, Recall: 0.4120, F1 Score: 0.3188, AUC: 0.5589, R2 Score: -0.038460, MAE: 1.7908, MSE: 5.0560
Training: Fold 4 - Total Loss: 2.4962, Cross Entropy: 1.232145, Accuracy: 0.4384, Precision: 0.3142, Recall: 0.4384, F1 Score: 0.3652, AUC: 0.5555, R2 Score: -0.020996, MAE: 1.8642, MSE: 5.4457
Validation: Fold 5 - Total Loss: 2.4103, Cross Entropy: 1.174598, Accuracy: 0.4718, Precision: 0.3230, Recall: 0.4718, F1 Score: 0.3816, AUC: 0.6640, R2 Score: -0.017093, MAE: 1.8139, MSE: 5.2937
Avg Latency (ms): 4.63, Avg Memory Before (MB): 117.34, Avg Memory After (MB): 117.34, Avg Max Memory (MB): 166.51
Best model saved with Accuracy: 0.4718

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4572, Cross Entropy: 1.203681, Accuracy: 0.4701, Precision: 0.3416, Recall: 0.4701, F1 Score: 0.3936, AUC: 0.5832, R2 Score: -0.052546, MAE: 1.8623, MSE: 5.3822
Training: Fold 2 - Total Loss: 2.4006, Cross Entropy: 1.205962, Accuracy: 0.4542, Precision: 0.3294, Recall: 0.4542, F1 Score: 0.3809, AUC: 0.5898, R2 Score: -0.048383, MAE: 1.8171, MSE: 5.1880
Training: Fold 3 - Total Loss: 2.3642, Cross Entropy: 1.212815, Accuracy: 0.4577, Precision: 0.3224, Recall: 0.4577, F1 Score: 0.3744, AUC: 0.5938, R2 Score: -0.030440, MAE: 1.7865, MSE: 5.0506
Training: Fold 4 - Total Loss: 2.5073, Cross Entropy: 1.239907, Accuracy: 0.4243, Precision: 0.3035, Recall: 0.4243, F1 Score: 0.3523, AUC: 0.5516, R2 Score: -0.035219, MAE: 1.8619, MSE: 5.4646

### EfficientNet-B0
EfficientNet introduces an **automated model scaling approach**, where width, depth, and resolution are **balanced** to optimize performance. This was achieved using **Neural Architecture Search (NAS)**, enabling EfficientNet to achieve state-of-the-art accuracy while being significantly **smaller and faster** than previous CNN architectures. EfficientNet-B0 is the smallest variant in the EfficientNet family, designed for mobile and embedded applications where computational efficiency is critical.

- **Paper:** Tan, M., & Le, Q. (2019). *EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks*. [ICML](https://arxiv.org/abs/1905.11946).

In [ ]:
ARCH = "efficientnet-b0"
main(ARCH)

====================================================================================================
Training Model: efficientnet-b0
Initial Backbone Model Size: 21.43 MB
Modified Backbone Model Size: 16.96 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 31.5472, Cross Entropy: 1.363154, Accuracy: 0.3081, Precision: 0.3184, Recall: 0.3081, F1 Score: 0.3017, AUC: 0.4998, R2 Score: -18.468224, MAE: 9.8114, MSE: 101.9765
Training: Fold 2 - Total Loss: 23.7652, Cross Entropy: 1.297311, Accuracy: 0.3891, Precision: 0.2719, Recall: 0.3891, F1 Score: 0.3085, AUC: 0.5298, R2 Score: -14.265299, MAE: 8.3621, MSE: 76.1903
Training: Fold 3 - Total Loss: 15.5479, Cross Entropy: 1.315223, Accuracy: 0.3820, Precision: 0.2680, Recall: 0.3820, F1 Score: 0.2305, AUC: 0.5131, R2 Score: -8.957117, MAE: 6.5041, MSE: 48.7574
Training: Fold 4 - Total Loss: 9.2499, Cross Entropy: 1.289040, Accuracy: 0.4173, Precision: 0.2676, Recall: 0.4173, F1 Score: 0.2777, AUC: 0.5192, R2 Score: -4.182535, MAE: 4.6713, MSE: 27.8251
Validation: Fold 5 - Total Loss: 4.4257, Cross Entropy: 1.344595, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5145, R2 Score: -1.114273, MAE: 2.9000, MSE: 11.6150
Avg Latency (ms): 7.47, Avg Memory Before (MB): 97.81, Avg Memory After (MB): 97.81, Avg Max Memory (MB): 382.07
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 4.9598, Cross Entropy: 1.256120, Accuracy: 0.4225, Precision: 0.3150, Recall: 0.4225, F1 Score: 0.3004, AUC: 0.5387, R2 Score: -1.578787, MAE: 3.0878, MSE: 13.6018
Training: Fold 2 - Total Loss: 3.1689, Cross Entropy: 1.261162, Accuracy: 0.3768, Precision: 0.2467, Recall: 0.3768, F1 Score: 0.2823, AUC: 0.4879, R2 Score: -0.498150, MAE: 2.2443, MSE: 7.6204
Training: Fold 3 - Total Loss: 2.7826, Cross Entropy: 1.265933, Accuracy: 0.3539, Precision: 0.2443, Recall: 0.3539, F1 Score: 0.2806, AUC: 0.4755, R2 Score: -0.375504, MAE: 2.0114, MSE: 6.3215
Training: Fold 4 - Total Loss: 2.7443, Cross Entropy: 1.248950, Accuracy: 0.3873, Precision: 0.2543, Recall: 0.3873, F1 Score: 0.2882, AUC: 0.5086, R2 Score: -0.209809, MAE: 1.9920, MSE: 6.2335
Validation: Fold 5 - Total Loss: 2.4419, Cross Entropy: 1.214473, Accuracy: 0.4014, Precision: 0.2767, Recall: 0.4014, F1 Score: 0.2864, AUC: 0.6289, R2 Score: 0.045628, MAE: 1.8306, MSE: 5.3060
Avg Latency (ms): 4.99, Avg Memory Before (MB): 98.34, Avg Memory After (MB): 98.34, Avg Max Memory (MB): 383.41
Best model saved with Accuracy: 0.4014

Epoch 3/150
Training: Fold 1 - Total Loss: 2.8102, Cross Entropy: 1.233046, Accuracy: 0.4049, Precision: 0.2801, Recall: 0.4049, F1 Score: 0.3029, AUC: 0.5254, R2 Score: -0.281323, MAE: 2.0549, MSE: 6.4903
Training: Fold 2 - Total Loss: 2.5087, Cross Entropy: 1.225369, Accuracy: 0.3891, Precision: 0.2569, Recall: 0.3891, F1 Score: 0.2846, AUC: 0.5552, R2 Score: -0.113540, MAE: 1.8821, MSE: 5.5033
Training: Fold 3 - Total Loss: 2.7060, Cross Entropy: 1.255917, Accuracy: 0.3979, Precision: 0.2793, Recall: 0.3979, F1 Score: 0.3202, AUC: 0.5011, R2 Score: -0.283774, MAE: 1.9947, MSE: 6.0897
Training: Fold 4 - Total Loss: 2.7228, Cross Entropy: 1.250336, Accuracy: 0.4102, Precision: 0.2905, Recall: 0.4102, F1 Score: 0.3354, AUC: 0.5183, R2 Score: -0.157018, MAE: 1.9848, MSE: 6.1586
Validation: Fold 5 - Total Loss: 2.4956, Cross Entropy: 1.233894, Accuracy: 0.4014, Precision: 0.3147, Recall: 0.4014, F1 Score: 0.2926, AUC: 0.5518, R2 Score: 0.056724, MAE: 1.8587, MSE: 5.4397
Avg Latency (ms): 4.97, Avg Memory Before (MB): 97.37, Avg Memory After (MB): 97.37, Avg Max Memory (MB): 381.64

Epoch 4/150
Training: Fold 1 - Total Loss: 2.5421, Cross Entropy: 1.234038, Accuracy: 0.4120, Precision: 0.2884, Recall: 0.4120, F1 Score: 0.2913, AUC: 0.5144, R2 Score: -0.090536, MAE: 1.9014, MSE: 5.5941
Training: Fold 2 - Total Loss: 2.4619, Cross Entropy: 1.225562, Accuracy: 0.4014, Precision: 0.2845, Recall: 0.4014, F1 Score: 0.3082, AUC: 0.5474, R2 Score: -0.087334, MAE: 1.8510, MSE: 5.3465
Training: Fold 3 - Total Loss: 2.4133, Cross Entropy: 1.243828, Accuracy: 0.3732, Precision: 0.2533, Recall: 0.3732, F1 Score: 0.2840, AUC: 0.5444, R2 Score: -0.049017, MAE: 1.8066, MSE: 5.1421
Training: Fold 4 - Total Loss: 2.6077, Cross Entropy: 1.250329, Accuracy: 0.3996, Precision: 0.2773, Recall: 0.3996, F1 Score: 0.3083, AUC: 0.5060, R2 Score: -0.077631, MAE: 1.9211, MSE: 5.7748
Validation: Fold 5 - Total Loss: 2.5495, Cross Entropy: 1.226418, Accuracy: 0.3944, Precision: 0.2763, Recall: 0.3944, F1 Score: 0.2875, AUC: 0.5670, R2 Score: -0.106707, MAE: 1.8709, MSE: 5.6367
Avg Latency (ms): 4.94, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 5/150
Training: Fold 1 - Total Loss: 2.5065, Cross Entropy: 1.226637, Accuracy: 0.4173, Precision: 0.3150, Recall: 0.4173, F1 Score: 0.2971, AUC: 0.5487, R2 Score: -0.004022, MAE: 1.8852, MSE: 5.4927
Training: Fold 2 - Total Loss: 2.4384, Cross Entropy: 1.235047, Accuracy: 0.3979, Precision: 0.2901, Recall: 0.3979, F1 Score: 0.3295, AUC: 0.5203, R2 Score: -0.082693, MAE: 1.8351, MSE: 5.2462
Training: Fold 3 - Total Loss: 2.4021, Cross Entropy: 1.238087, Accuracy: 0.4032, Precision: 0.2855, Recall: 0.4032, F1 Score: 0.3282, AUC: 0.5673, R2 Score: -0.066947, MAE: 1.8000, MSE: 5.1182
Training: Fold 4 - Total Loss: 2.5147, Cross Entropy: 1.243195, Accuracy: 0.4049, Precision: 0.2788, Recall: 0.4049, F1 Score: 0.3176, AUC: 0.5292, R2 Score: -0.029069, MAE: 1.8649, MSE: 5.4817
Validation: Fold 5 - Total Loss: 2.4779, Cross Entropy: 1.230554, Accuracy: 0.4014, Precision: 0.2675, Recall: 0.4014, F1 Score: 0.2971, AUC: 0.5402, R2 Score: -0.040844, MAE: 1.8357, MSE: 5.3885
Avg Latency (ms): 4.98, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 6/150
Training: Fold 1 - Total Loss: 2.5025, Cross Entropy: 1.235375, Accuracy: 0.4014, Precision: 0.2627, Recall: 0.4014, F1 Score: 0.2823, AUC: 0.5196, R2 Score: -0.045598, MAE: 1.8741, MSE: 5.4592
Training: Fold 2 - Total Loss: 2.4380, Cross Entropy: 1.236479, Accuracy: 0.3856, Precision: 0.2610, Recall: 0.3856, F1 Score: 0.2816, AUC: 0.5131, R2 Score: -0.058594, MAE: 1.8283, MSE: 5.2415
Training: Fold 3 - Total Loss: 2.3988, Cross Entropy: 1.242786, Accuracy: 0.4067, Precision: 0.2900, Recall: 0.4067, F1 Score: 0.3219, AUC: 0.5445, R2 Score: -0.048310, MAE: 1.7929, MSE: 5.0960
Training: Fold 4 - Total Loss: 2.5074, Cross Entropy: 1.238655, Accuracy: 0.4102, Precision: 0.2871, Recall: 0.4102, F1 Score: 0.3314, AUC: 0.5293, R2 Score: -0.024977, MAE: 1.8616, MSE: 5.4678
Validation: Fold 5 - Total Loss: 2.4519, Cross Entropy: 1.222377, Accuracy: 0.3803, Precision: 0.2543, Recall: 0.3803, F1 Score: 0.2789, AUC: 0.5715, R2 Score: -0.028742, MAE: 1.8218, MSE: 5.3209
Avg Latency (ms): 5.06, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4788, Cross Entropy: 1.231365, Accuracy: 0.4190, Precision: 0.3042, Recall: 0.4190, F1 Score: 0.3154, AUC: 0.5216, R2 Score: -0.061188, MAE: 1.8649, MSE: 5.3896
Training: Fold 2 - Total Loss: 2.4093, Cross Entropy: 1.229006, Accuracy: 0.4137, Precision: 0.2953, Recall: 0.4137, F1 Score: 0.3126, AUC: 0.5312, R2 Score: -0.039415, MAE: 1.8193, MSE: 5.1633
Training: Fold 3 - Total Loss: 2.3758, Cross Entropy: 1.248282, Accuracy: 0.4032, Precision: 0.2813, Recall: 0.4032, F1 Score: 0.3228, AUC: 0.5093, R2 Score: -0.060181, MAE: 1.7811, MSE: 5.0067
Training: Fold 4 - Total Loss: 2.5147, Cross Entropy: 1.240798, Accuracy: 0.4225, Precision: 0.2899, Recall: 0.4225, F1 Score: 0.3318, AUC: 0.5387, R2 Score: -0.024206, MAE: 1.8688, MSE: 5.4872
Validation: Fold 5 - Total Loss: 2.4374, Cross Entropy: 1.225680, Accuracy: 0.3732, Precision: 0.2505, Recall: 0.3732, F1 Score: 0.2692, AUC: 0.5417, R2 Score: 0.013599, MAE: 1.8168, MSE: 5.2648
Avg Latency (ms): 4.98, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 8/150
Training: Fold 1 - Total Loss: 2.5050, Cross Entropy: 1.228908, Accuracy: 0.4243, Precision: 0.3145, Recall: 0.4243, F1 Score: 0.3368, AUC: 0.5210, R2 Score: -0.060326, MAE: 1.8899, MSE: 5.4826
Training: Fold 2 - Total Loss: 2.3906, Cross Entropy: 1.226014, Accuracy: 0.4190, Precision: 0.2972, Recall: 0.4190, F1 Score: 0.3355, AUC: 0.5400, R2 Score: -0.020798, MAE: 1.8015, MSE: 5.1079
Training: Fold 3 - Total Loss: 2.3703, Cross Entropy: 1.240643, Accuracy: 0.4067, Precision: 0.2877, Recall: 0.4067, F1 Score: 0.3203, AUC: 0.5415, R2 Score: -0.023797, MAE: 1.7864, MSE: 5.0062
Training: Fold 4 - Total Loss: 2.5194, Cross Entropy: 1.238620, Accuracy: 0.4296, Precision: 0.3047, Recall: 0.4296, F1 Score: 0.3443, AUC: 0.5356, R2 Score: -0.029300, MAE: 1.8791, MSE: 5.5080
Validation: Fold 5 - Total Loss: 2.4672, Cross Entropy: 1.251224, Accuracy: 0.4014, Precision: 0.2900, Recall: 0.4014, F1 Score: 0.3163, AUC: 0.4839, R2 Score: -0.002030, MAE: 1.8142, MSE: 5.3044
Avg Latency (ms): 4.83, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 9/150
Training: Fold 1 - Total Loss: 2.5025, Cross Entropy: 1.242854, Accuracy: 0.4014, Precision: 0.2884, Recall: 0.4014, F1 Score: 0.3028, AUC: 0.5027, R2 Score: -0.031855, MAE: 1.8672, MSE: 5.4416
Training: Fold 2 - Total Loss: 2.3976, Cross Entropy: 1.226929, Accuracy: 0.3979, Precision: 0.2779, Recall: 0.3979, F1 Score: 0.3050, AUC: 0.5345, R2 Score: -0.023026, MAE: 1.7968, MSE: 5.1291
Training: Fold 3 - Total Loss: 2.3648, Cross Entropy: 1.238847, Accuracy: 0.4049, Precision: 0.2875, Recall: 0.4049, F1 Score: 0.3206, AUC: 0.5544, R2 Score: -0.013872, MAE: 1.7766, MSE: 4.9921
Training: Fold 4 - Total Loss: 2.5087, Cross Entropy: 1.235078, Accuracy: 0.4261, Precision: 0.3035, Recall: 0.4261, F1 Score: 0.3503, AUC: 0.5336, R2 Score: -0.040834, MAE: 1.8631, MSE: 5.4805
Validation: Fold 5 - Total Loss: 2.4574, Cross Entropy: 1.234022, Accuracy: 0.3803, Precision: 0.2554, Recall: 0.3803, F1 Score: 0.2878, AUC: 0.4972, R2 Score: 0.027866, MAE: 1.8205, MSE: 5.3120
Avg Latency (ms): 4.83, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 10/150
Training: Fold 1 - Total Loss: 2.4661, Cross Entropy: 1.221561, Accuracy: 0.4173, Precision: 0.3060, Recall: 0.4173, F1 Score: 0.3228, AUC: 0.5505, R2 Score: -0.037667, MAE: 1.8661, MSE: 5.3700
Training: Fold 2 - Total Loss: 2.3800, Cross Entropy: 1.219071, Accuracy: 0.4331, Precision: 0.3142, Recall: 0.4331, F1 Score: 0.3555, AUC: 0.5538, R2 Score: -0.021314, MAE: 1.7974, MSE: 5.0890
Training: Fold 3 - Total Loss: 2.3914, Cross Entropy: 1.250944, Accuracy: 0.4137, Precision: 0.2998, Recall: 0.4137, F1 Score: 0.3332, AUC: 0.5004, R2 Score: -0.049659, MAE: 1.7870, MSE: 5.0526
Training: Fold 4 - Total Loss: 2.5139, Cross Entropy: 1.236047, Accuracy: 0.4102, Precision: 0.2912, Recall: 0.4102, F1 Score: 0.3389, AUC: 0.5393, R2 Score: -0.042473, MAE: 1.8745, MSE: 5.4956
Validation: Fold 5 - Total Loss: 2.4682, Cross Entropy: 1.209411, Accuracy: 0.4225, Precision: 0.2957, Recall: 0.4225, F1 Score: 0.3328, AUC: 0.5971, R2 Score: -0.058366, MAE: 1.8408, MSE: 5.4052
Avg Latency (ms): 4.90, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96
Best model saved with Accuracy: 0.4225

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4622, Cross Entropy: 1.223728, Accuracy: 0.3979, Precision: 0.2737, Recall: 0.3979, F1 Score: 0.3013, AUC: 0.5506, R2 Score: -0.011549, MAE: 1.8543, MSE: 5.3521
Training: Fold 2 - Total Loss: 2.4025, Cross Entropy: 1.238090, Accuracy: 0.3856, Precision: 0.2640, Recall: 0.3856, F1 Score: 0.2886, AUC: 0.4954, R2 Score: -0.009818, MAE: 1.7967, MSE: 5.1194
Training: Fold 3 - Total Loss: 2.3812, Cross Entropy: 1.247328, Accuracy: 0.3662, Precision: 0.2512, Recall: 0.3662, F1 Score: 0.2813, AUC: 0.5225, R2 Score: -0.062407, MAE: 1.7765, MSE: 5.0270
Training: Fold 4 - Total Loss: 2.4956, Cross Entropy: 1.242217, Accuracy: 0.4049, Precision: 0.2871, Recall: 0.4049, F1 Score: 0.3317, AUC: 0.5181, R2 Score: -0.017407, MAE: 1.8545, MSE: 5.4202
Validation: Fold 5 - Total Loss: 2.4231, Cross Entropy: 1.213762, Accuracy: 0.4085, Precision: 0.3008, Recall: 0.4085, F1 Score: 0.3185, AUC: 0.5758, R2 Score: -0.002141, MAE: 1.8183, MSE: 5.2449
Avg Latency (ms): 4.83, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 12/150
Training: Fold 1 - Total Loss: 2.4990, Cross Entropy: 1.235074, Accuracy: 0.4173, Precision: 0.2992, Recall: 0.4173, F1 Score: 0.3218, AUC: 0.5365, R2 Score: -0.045285, MAE: 1.8758, MSE: 5.4482
Training: Fold 2 - Total Loss: 2.3608, Cross Entropy: 1.220528, Accuracy: 0.4173, Precision: 0.2995, Recall: 0.4173, F1 Score: 0.3290, AUC: 0.5439, R2 Score: -0.022468, MAE: 1.7856, MSE: 5.0214
Training: Fold 3 - Total Loss: 2.3637, Cross Entropy: 1.243345, Accuracy: 0.4014, Precision: 0.2808, Recall: 0.4014, F1 Score: 0.3143, AUC: 0.5340, R2 Score: 0.004751, MAE: 1.7688, MSE: 4.9780
Training: Fold 4 - Total Loss: 2.4908, Cross Entropy: 1.230904, Accuracy: 0.4173, Precision: 0.2978, Recall: 0.4173, F1 Score: 0.3462, AUC: 0.5382, R2 Score: -0.034114, MAE: 1.8611, MSE: 5.4307
Validation: Fold 5 - Total Loss: 2.4298, Cross Entropy: 1.218899, Accuracy: 0.4155, Precision: 0.2875, Recall: 0.4155, F1 Score: 0.3359, AUC: 0.5660, R2 Score: -0.018230, MAE: 1.8291, MSE: 5.2552
Avg Latency (ms): 4.90, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4981, Cross Entropy: 1.228982, Accuracy: 0.4296, Precision: 0.3087, Recall: 0.4296, F1 Score: 0.3333, AUC: 0.5122, R2 Score: -0.048006, MAE: 1.8752, MSE: 5.4595
Training: Fold 2 - Total Loss: 2.3966, Cross Entropy: 1.219665, Accuracy: 0.4067, Precision: 0.2902, Recall: 0.4067, F1 Score: 0.3305, AUC: 0.5710, R2 Score: -0.017756, MAE: 1.8068, MSE: 5.1427
Training: Fold 3 - Total Loss: 2.3808, Cross Entropy: 1.240424, Accuracy: 0.4120, Precision: 0.2912, Recall: 0.4120, F1 Score: 0.3319, AUC: 0.5359, R2 Score: -0.017378, MAE: 1.7926, MSE: 5.0416
Training: Fold 4 - Total Loss: 2.4845, Cross Entropy: 1.243391, Accuracy: 0.4049, Precision: 0.2803, Recall: 0.4049, F1 Score: 0.3213, AUC: 0.5200, R2 Score: -0.023386, MAE: 1.8383, MSE: 5.3806
Validation: Fold 5 - Total Loss: 2.4217, Cross Entropy: 1.214656, Accuracy: 0.4225, Precision: 0.2899, Recall: 0.4225, F1 Score: 0.3231, AUC: 0.5967, R2 Score: 0.024675, MAE: 1.8126, MSE: 5.2383
Avg Latency (ms): 4.84, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 14/150
Training: Fold 1 - Total Loss: 2.4474, Cross Entropy: 1.219904, Accuracy: 0.4225, Precision: 0.2989, Recall: 0.4225, F1 Score: 0.3412, AUC: 0.5669, R2 Score: -0.013676, MAE: 1.8549, MSE: 5.3117
Training: Fold 2 - Total Loss: 2.3789, Cross Entropy: 1.213264, Accuracy: 0.4366, Precision: 0.3157, Recall: 0.4366, F1 Score: 0.3522, AUC: 0.5703, R2 Score: -0.016155, MAE: 1.7979, MSE: 5.0987
Training: Fold 3 - Total Loss: 2.3519, Cross Entropy: 1.234976, Accuracy: 0.4067, Precision: 0.2862, Recall: 0.4067, F1 Score: 0.3297, AUC: 0.5596, R2 Score: 0.010307, MAE: 1.7587, MSE: 4.9580
Training: Fold 4 - Total Loss: 2.4987, Cross Entropy: 1.237962, Accuracy: 0.4190, Precision: 0.3004, Recall: 0.4190, F1 Score: 0.3485, AUC: 0.5358, R2 Score: -0.034746, MAE: 1.8558, MSE: 5.4405
Validation: Fold 5 - Total Loss: 2.4548, Cross Entropy: 1.209505, Accuracy: 0.4718, Precision: 0.3346, Recall: 0.4718, F1 Score: 0.3831, AUC: 0.5759, R2 Score: -0.059504, MAE: 1.8392, MSE: 5.3604
Avg Latency (ms): 4.83, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96
Best model saved with Accuracy: 0.4718

Epoch 15/150
Training: Fold 1 - Total Loss: 2.4808, Cross Entropy: 1.227148, Accuracy: 0.4243, Precision: 0.3049, Recall: 0.4243, F1 Score: 0.3441, AUC: 0.5544, R2 Score: -0.024794, MAE: 1.8695, MSE: 5.4061
Training: Fold 2 - Total Loss: 2.3667, Cross Entropy: 1.213812, Accuracy: 0.4313, Precision: 0.3109, Recall: 0.4313, F1 Score: 0.3463, AUC: 0.5656, R2 Score: -0.017873, MAE: 1.7962, MSE: 5.0567
Training: Fold 3 - Total Loss: 2.3952, Cross Entropy: 1.243403, Accuracy: 0.3803, Precision: 0.2674, Recall: 0.3803, F1 Score: 0.3029, AUC: 0.5426, R2 Score: -0.047381, MAE: 1.7872, MSE: 5.0826
Training: Fold 4 - Total Loss: 2.4981, Cross Entropy: 1.229359, Accuracy: 0.4049, Precision: 0.2899, Recall: 0.4049, F1 Score: 0.3372, AUC: 0.5536, R2 Score: -0.037946, MAE: 1.8665, MSE: 5.4586
Validation: Fold 5 - Total Loss: 2.4244, Cross Entropy: 1.213565, Accuracy: 0.4155, Precision: 0.3002, Recall: 0.4155, F1 Score: 0.3260, AUC: 0.5419, R2 Score: -0.023798, MAE: 1.8269, MSE: 5.2497
Avg Latency (ms): 4.83, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 16/150
Training: Fold 1 - Total Loss: 2.4504, Cross Entropy: 1.222444, Accuracy: 0.4208, Precision: 0.2992, Recall: 0.4208, F1 Score: 0.3264, AUC: 0.5424, R2 Score: -0.009020, MAE: 1.8528, MSE: 5.3155
Training: Fold 2 - Total Loss: 2.3778, Cross Entropy: 1.221659, Accuracy: 0.4173, Precision: 0.3005, Recall: 0.4173, F1 Score: 0.3445, AUC: 0.5400, R2 Score: -0.002532, MAE: 1.7956, MSE: 5.0753
Training: Fold 3 - Total Loss: 2.3708, Cross Entropy: 1.243198, Accuracy: 0.4120, Precision: 0.2911, Recall: 0.4120, F1 Score: 0.3384, AUC: 0.5426, R2 Score: -0.020733, MAE: 1.7735, MSE: 5.0019
Training: Fold 4 - Total Loss: 2.4984, Cross Entropy: 1.232225, Accuracy: 0.4349, Precision: 0.3093, Recall: 0.4349, F1 Score: 0.3456, AUC: 0.5366, R2 Score: -0.035763, MAE: 1.8541, MSE: 5.4529
Validation: Fold 5 - Total Loss: 2.4206, Cross Entropy: 1.221496, Accuracy: 0.4085, Precision: 0.2705, Recall: 0.4085, F1 Score: 0.2847, AUC: 0.5757, R2 Score: -0.004678, MAE: 1.8173, MSE: 5.2184
Avg Latency (ms): 4.83, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4468, Cross Entropy: 1.218669, Accuracy: 0.4384, Precision: 0.3136, Recall: 0.4384, F1 Score: 0.3445, AUC: 0.5476, R2 Score: -0.031568, MAE: 1.8498, MSE: 5.3123
Training: Fold 2 - Total Loss: 2.3763, Cross Entropy: 1.225251, Accuracy: 0.4173, Precision: 0.3001, Recall: 0.4173, F1 Score: 0.3456, AUC: 0.5431, R2 Score: -0.024031, MAE: 1.7925, MSE: 5.0621
Training: Fold 3 - Total Loss: 2.3600, Cross Entropy: 1.231382, Accuracy: 0.4173, Precision: 0.2950, Recall: 0.4173, F1 Score: 0.3445, AUC: 0.5748, R2 Score: -0.030792, MAE: 1.7726, MSE: 4.9934
Training: Fold 4 - Total Loss: 2.4873, Cross Entropy: 1.224246, Accuracy: 0.4313, Precision: 0.2995, Recall: 0.4313, F1 Score: 0.3421, AUC: 0.5605, R2 Score: -0.028375, MAE: 1.8517, MSE: 5.4344
Validation: Fold 5 - Total Loss: 2.4242, Cross Entropy: 1.213491, Accuracy: 0.4648, Precision: 0.3303, Recall: 0.4648, F1 Score: 0.3704, AUC: 0.5812, R2 Score: -0.002619, MAE: 1.8146, MSE: 5.2491
Avg Latency (ms): 4.90, Avg Memory Before (MB): 97.69, Avg Memory After (MB): 97.69, Avg Max Memory (MB): 381.96

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4570, Cross Entropy: 1.215717, Accuracy: 0.4225, Precision: 0.2992, Recall: 0.4225, F1 Score: 0.3122, AUC: 0.5761, R2 Score: -0.000230, MAE: 1.8579, MSE: 5.3534
Training: Fold 2 - Total Loss: 2.3868, Cross Entropy: 1.217177, Accuracy: 0.4401, Precision: 0.3174, Recall: 0.4401, F1 Score: 0.3649, AUC: 0.5691, R2 Score: -0.004648, MAE: 1.8001, MSE: 5.1159
Training: Fold 3 - Total Loss: 2.3574, Cross Entropy: 1.240701, Accuracy: 0.3891, Precision: 0.2717, Recall: 0.3891, F1 Score: 0.3135, AUC: 0.5391, R2 Score: -0.048893, MAE: 1.7648, MSE: 4.9630
Training: Fold 4 - Total Loss: 2.4758, Cross Entropy: 1.227997, Accuracy: 0.4349, Precision: 0.3092, Recall: 0.4349, F1 Score: 0.3599, AUC: 0.5569, R2 Score: -0.017221, MAE: 1.8523, MSE: 5.3874

### ShuffleNetV2-0.5x

ShuffleNetV2 was designed to address practical limitations of lightweight CNNs in real-world applications. Unlike conventional CNNs, it incorporates **channel shuffling** and **group convolutions**, optimizing the trade-off between **speed, accuracy, and memory efficiency**. This makes it an ideal choice for **low-power devices**, including mobile phones and embedded vision systems.

- **Paper:** Ma, N., Zhang, X., Zheng, H. T., & Sun, J. (2018). *ShuffleNet V2: Practical Guidelines for Efficient CNN Architecture Design*. [ECCV](https://arxiv.org/abs/1807.11164).

In [ ]:
ARCH = "shufflenetv2-0.5x"
main(ARCH)

====================================================================================================
Training Model: shufflenetv2-0.5x
Initial Backbone Model Size: 5.59 MB
Modified Backbone Model Size: 2.02 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 28.4044, Cross Entropy: 1.381656, Accuracy: 0.3028, Precision: 0.2300, Recall: 0.3028, F1 Score: 0.2583, AUC: 0.5122, R2 Score: -16.538587, MAE: 9.2593, MSE: 91.4574
Training: Fold 2 - Total Loss: 17.5974, Cross Entropy: 1.332064, Accuracy: 0.3504, Precision: 0.2094, Recall: 0.3504, F1 Score: 0.2620, AUC: 0.5169, R2 Score: -10.224374, MAE: 7.0920, MSE: 55.5500
Training: Fold 3 - Total Loss: 9.2559, Cross Entropy: 1.280724, Accuracy: 0.3785, Precision: 0.1433, Recall: 0.3785, F1 Score: 0.2079, AUC: 0.5202, R2 Score: -4.730235, MAE: 4.7959, MSE: 27.8645
Training: Fold 4 - Total Loss: 4.6802, Cross Entropy: 1.244576, Accuracy: 0.4173, Precision: 0.1741, Recall: 0.4173, F1 Score: 0.2457, AUC: 0.4954, R2 Score: -1.380930, MAE: 3.0445, MSE: 12.6966
Validation: Fold 5 - Total Loss: 3.8752, Cross Entropy: 1.238147, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5024, R2 Score: -0.819080, MAE: 2.6557, MSE: 10.0283
Avg Latency (ms): 3.58, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 2.7397, Cross Entropy: 1.237145, Accuracy: 0.4067, Precision: 0.1670, Recall: 0.4067, F1 Score: 0.2368, AUC: 0.4854, R2 Score: -0.183072, MAE: 2.0368, MSE: 6.2455
Training: Fold 2 - Total Loss: 2.3931, Cross Entropy: 1.236414, Accuracy: 0.4032, Precision: 0.3270, Recall: 0.4032, F1 Score: 0.2347, AUC: 0.4940, R2 Score: -0.010042, MAE: 1.8006, MSE: 5.0920
Training: Fold 3 - Total Loss: 2.3529, Cross Entropy: 1.245840, Accuracy: 0.3803, Precision: 0.2444, Recall: 0.3803, F1 Score: 0.2381, AUC: 0.5332, R2 Score: 0.003445, MAE: 1.7661, MSE: 4.9359
Training: Fold 4 - Total Loss: 2.4788, Cross Entropy: 1.242778, Accuracy: 0.4155, Precision: 0.2874, Recall: 0.4155, F1 Score: 0.2777, AUC: 0.5044, R2 Score: -0.007499, MAE: 1.8430, MSE: 5.3630
Validation: Fold 5 - Total Loss: 2.4678, Cross Entropy: 1.232499, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5764, R2 Score: 0.017935, MAE: 1.8209, MSE: 5.3503
Avg Latency (ms): 2.77, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4408, Cross Entropy: 1.235694, Accuracy: 0.4085, Precision: 0.1668, Recall: 0.4085, F1 Score: 0.2369, AUC: 0.4981, R2 Score: 0.004508, MAE: 1.8367, MSE: 5.2527
Training: Fold 2 - Total Loss: 2.3802, Cross Entropy: 1.234729, Accuracy: 0.4032, Precision: 0.1625, Recall: 0.4032, F1 Score: 0.2317, AUC: 0.5013, R2 Score: -0.000217, MAE: 1.7887, MSE: 5.0530
Training: Fold 3 - Total Loss: 2.3555, Cross Entropy: 1.249898, Accuracy: 0.3768, Precision: 0.2499, Recall: 0.3768, F1 Score: 0.2280, AUC: 0.5047, R2 Score: -0.006213, MAE: 1.7607, MSE: 4.9351
Training: Fold 4 - Total Loss: 2.4843, Cross Entropy: 1.244126, Accuracy: 0.4208, Precision: 0.2973, Recall: 0.4208, F1 Score: 0.2735, AUC: 0.5026, R2 Score: -0.009483, MAE: 1.8433, MSE: 5.3779
Validation: Fold 5 - Total Loss: 2.4724, Cross Entropy: 1.237859, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4885, R2 Score: -0.017017, MAE: 1.8205, MSE: 5.3532
Avg Latency (ms): 3.18, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 4/150
Training: Fold 1 - Total Loss: 2.4482, Cross Entropy: 1.235765, Accuracy: 0.4085, Precision: 0.1668, Recall: 0.4085, F1 Score: 0.2369, AUC: 0.4961, R2 Score: -0.005786, MAE: 1.8453, MSE: 5.2772
Training: Fold 2 - Total Loss: 2.3605, Cross Entropy: 1.230769, Accuracy: 0.4032, Precision: 0.2862, Recall: 0.4032, F1 Score: 0.2411, AUC: 0.5059, R2 Score: -0.015674, MAE: 1.7789, MSE: 4.9966
Training: Fold 3 - Total Loss: 2.3459, Cross Entropy: 1.248350, Accuracy: 0.3873, Precision: 0.3254, Recall: 0.3873, F1 Score: 0.2325, AUC: 0.5336, R2 Score: 0.000447, MAE: 1.7524, MSE: 4.9069
Training: Fold 4 - Total Loss: 2.4729, Cross Entropy: 1.242572, Accuracy: 0.4225, Precision: 0.4849, Recall: 0.4225, F1 Score: 0.2570, AUC: 0.4880, R2 Score: -0.006216, MAE: 1.8406, MSE: 5.3438
Validation: Fold 5 - Total Loss: 2.4529, Cross Entropy: 1.231751, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5459, R2 Score: -0.005063, MAE: 1.8148, MSE: 5.3022
Avg Latency (ms): 3.03, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 5/150
Training: Fold 1 - Total Loss: 2.4494, Cross Entropy: 1.235096, Accuracy: 0.4049, Precision: 0.1663, Recall: 0.4049, F1 Score: 0.2357, AUC: 0.5093, R2 Score: -0.002905, MAE: 1.8450, MSE: 5.2827
Training: Fold 2 - Total Loss: 2.3555, Cross Entropy: 1.232094, Accuracy: 0.4049, Precision: 0.4921, Recall: 0.4049, F1 Score: 0.2355, AUC: 0.5130, R2 Score: 0.000904, MAE: 1.7720, MSE: 4.9767
Training: Fold 3 - Total Loss: 2.3418, Cross Entropy: 1.250826, Accuracy: 0.3732, Precision: 0.2618, Recall: 0.3732, F1 Score: 0.2704, AUC: 0.4857, R2 Score: -0.010638, MAE: 1.7492, MSE: 4.8874
Training: Fold 4 - Total Loss: 2.4753, Cross Entropy: 1.239427, Accuracy: 0.4173, Precision: 0.2733, Recall: 0.4173, F1 Score: 0.2864, AUC: 0.5154, R2 Score: -0.001525, MAE: 1.8430, MSE: 5.3590
Validation: Fold 5 - Total Loss: 2.4610, Cross Entropy: 1.229032, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5643, R2 Score: -0.006405, MAE: 1.8179, MSE: 5.3356
Avg Latency (ms): 2.87, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4607, Cross Entropy: 1.237437, Accuracy: 0.4085, Precision: 0.1668, Recall: 0.4085, F1 Score: 0.2369, AUC: 0.5051, R2 Score: 0.006952, MAE: 1.8529, MSE: 5.3149
Training: Fold 2 - Total Loss: 2.3687, Cross Entropy: 1.232931, Accuracy: 0.4014, Precision: 0.2979, Recall: 0.4014, F1 Score: 0.2741, AUC: 0.5073, R2 Score: -0.005502, MAE: 1.7777, MSE: 5.0188
Training: Fold 3 - Total Loss: 2.3333, Cross Entropy: 1.246048, Accuracy: 0.3715, Precision: 0.2565, Recall: 0.3715, F1 Score: 0.2324, AUC: 0.5229, R2 Score: -0.011755, MAE: 1.7452, MSE: 4.8704
Training: Fold 4 - Total Loss: 2.4784, Cross Entropy: 1.241113, Accuracy: 0.4225, Precision: 0.3074, Recall: 0.4225, F1 Score: 0.2791, AUC: 0.4987, R2 Score: -0.014359, MAE: 1.8420, MSE: 5.3654
Validation: Fold 5 - Total Loss: 2.4456, Cross Entropy: 1.225786, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5579, R2 Score: -0.002027, MAE: 1.8159, MSE: 5.2917
Avg Latency (ms): 3.01, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4437, Cross Entropy: 1.232875, Accuracy: 0.4067, Precision: 0.1664, Recall: 0.4067, F1 Score: 0.2362, AUC: 0.5175, R2 Score: -0.019988, MAE: 1.8411, MSE: 5.2691
Training: Fold 2 - Total Loss: 2.3618, Cross Entropy: 1.229245, Accuracy: 0.4014, Precision: 0.1624, Recall: 0.4014, F1 Score: 0.2313, AUC: 0.5248, R2 Score: 0.004909, MAE: 1.7801, MSE: 5.0044
Training: Fold 3 - Total Loss: 2.3520, Cross Entropy: 1.249479, Accuracy: 0.3803, Precision: 0.2519, Recall: 0.3803, F1 Score: 0.2448, AUC: 0.5155, R2 Score: 0.004073, MAE: 1.7595, MSE: 4.9247
Training: Fold 4 - Total Loss: 2.4818, Cross Entropy: 1.241324, Accuracy: 0.4225, Precision: 0.2958, Recall: 0.4225, F1 Score: 0.3209, AUC: 0.5298, R2 Score: -0.008231, MAE: 1.8450, MSE: 5.3763
Validation: Fold 5 - Total Loss: 2.4350, Cross Entropy: 1.225943, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5539, R2 Score: 0.004493, MAE: 1.8089, MSE: 5.2562
Avg Latency (ms): 2.94, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4480, Cross Entropy: 1.229028, Accuracy: 0.4085, Precision: 0.1668, Recall: 0.4085, F1 Score: 0.2369, AUC: 0.5410, R2 Score: 0.003242, MAE: 1.8479, MSE: 5.2924
Training: Fold 2 - Total Loss: 2.3646, Cross Entropy: 1.234152, Accuracy: 0.3961, Precision: 0.2578, Recall: 0.3961, F1 Score: 0.2546, AUC: 0.4871, R2 Score: 0.002354, MAE: 1.7795, MSE: 5.0022
Training: Fold 3 - Total Loss: 2.3429, Cross Entropy: 1.246079, Accuracy: 0.3785, Precision: 0.2738, Recall: 0.3785, F1 Score: 0.2803, AUC: 0.5034, R2 Score: -0.005336, MAE: 1.7523, MSE: 4.9020
Training: Fold 4 - Total Loss: 2.4716, Cross Entropy: 1.233681, Accuracy: 0.4067, Precision: 0.2748, Recall: 0.4067, F1 Score: 0.3090, AUC: 0.5374, R2 Score: -0.009651, MAE: 1.8447, MSE: 5.3601
Validation: Fold 5 - Total Loss: 2.4325, Cross Entropy: 1.221177, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6199, R2 Score: 0.000179, MAE: 1.8113, MSE: 5.2590
Avg Latency (ms): 2.94, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 9/150
Training: Fold 1 - Total Loss: 2.4534, Cross Entropy: 1.235558, Accuracy: 0.4049, Precision: 0.2481, Recall: 0.4049, F1 Score: 0.2385, AUC: 0.5143, R2 Score: -0.012697, MAE: 1.8427, MSE: 5.2949
Training: Fold 2 - Total Loss: 2.3734, Cross Entropy: 1.232826, Accuracy: 0.3961, Precision: 0.2756, Recall: 0.3961, F1 Score: 0.2774, AUC: 0.5122, R2 Score: -0.001664, MAE: 1.7814, MSE: 5.0347
Training: Fold 3 - Total Loss: 2.3378, Cross Entropy: 1.244216, Accuracy: 0.3574, Precision: 0.2494, Recall: 0.3574, F1 Score: 0.2875, AUC: 0.5291, R2 Score: -0.000485, MAE: 1.7505, MSE: 4.8894
Training: Fold 4 - Total Loss: 2.4684, Cross Entropy: 1.240368, Accuracy: 0.3961, Precision: 0.2536, Recall: 0.3961, F1 Score: 0.2783, AUC: 0.5292, R2 Score: 0.001589, MAE: 1.8353, MSE: 5.3338
Validation: Fold 5 - Total Loss: 2.4269, Cross Entropy: 1.219315, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6043, R2 Score: 0.009086, MAE: 1.8099, MSE: 5.2445
Avg Latency (ms): 3.10, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 10/150
Training: Fold 1 - Total Loss: 2.4363, Cross Entropy: 1.231619, Accuracy: 0.4067, Precision: 0.2220, Recall: 0.4067, F1 Score: 0.2400, AUC: 0.5249, R2 Score: -0.004479, MAE: 1.8381, MSE: 5.2473
Training: Fold 2 - Total Loss: 2.3604, Cross Entropy: 1.230005, Accuracy: 0.3961, Precision: 0.2573, Recall: 0.3961, F1 Score: 0.2620, AUC: 0.5205, R2 Score: -0.010098, MAE: 1.7757, MSE: 4.9981
Training: Fold 3 - Total Loss: 2.3430, Cross Entropy: 1.245350, Accuracy: 0.3644, Precision: 0.2553, Recall: 0.3644, F1 Score: 0.2837, AUC: 0.5369, R2 Score: -0.000912, MAE: 1.7533, MSE: 4.9041
Training: Fold 4 - Total Loss: 2.4663, Cross Entropy: 1.236631, Accuracy: 0.4190, Precision: 0.2890, Recall: 0.4190, F1 Score: 0.3123, AUC: 0.5407, R2 Score: 0.000916, MAE: 1.8384, MSE: 5.3355
Validation: Fold 5 - Total Loss: 2.4385, Cross Entropy: 1.216674, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5875, R2 Score: -0.011311, MAE: 1.8132, MSE: 5.2893
Avg Latency (ms): 2.79, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4429, Cross Entropy: 1.231897, Accuracy: 0.4120, Precision: 0.3038, Recall: 0.4120, F1 Score: 0.2594, AUC: 0.5274, R2 Score: 0.001211, MAE: 1.8437, MSE: 5.2685
Training: Fold 2 - Total Loss: 2.3529, Cross Entropy: 1.228123, Accuracy: 0.3996, Precision: 0.2826, Recall: 0.3996, F1 Score: 0.2971, AUC: 0.5324, R2 Score: -0.015500, MAE: 1.7730, MSE: 4.9774
Training: Fold 3 - Total Loss: 2.3417, Cross Entropy: 1.245266, Accuracy: 0.3856, Precision: 0.2789, Recall: 0.3856, F1 Score: 0.2940, AUC: 0.5285, R2 Score: -0.006047, MAE: 1.7501, MSE: 4.8999
Training: Fold 4 - Total Loss: 2.4681, Cross Entropy: 1.237653, Accuracy: 0.4014, Precision: 0.2628, Recall: 0.4014, F1 Score: 0.2901, AUC: 0.5270, R2 Score: -0.000466, MAE: 1.8360, MSE: 5.3393
Validation: Fold 5 - Total Loss: 2.4192, Cross Entropy: 1.209606, Accuracy: 0.4014, Precision: 0.3598, Recall: 0.4014, F1 Score: 0.2460, AUC: 0.5686, R2 Score: 0.000079, MAE: 1.8127, MSE: 5.2416
Avg Latency (ms): 3.30, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27
Best model saved with Accuracy: 0.4014

Epoch 12/150
Training: Fold 1 - Total Loss: 2.4329, Cross Entropy: 1.226389, Accuracy: 0.4102, Precision: 0.2916, Recall: 0.4102, F1 Score: 0.2933, AUC: 0.5474, R2 Score: 0.000247, MAE: 1.8372, MSE: 5.2482
Training: Fold 2 - Total Loss: 2.3546, Cross Entropy: 1.229913, Accuracy: 0.4014, Precision: 0.2824, Recall: 0.4014, F1 Score: 0.2996, AUC: 0.5029, R2 Score: -0.009300, MAE: 1.7716, MSE: 4.9787
Training: Fold 3 - Total Loss: 2.3314, Cross Entropy: 1.245609, Accuracy: 0.3820, Precision: 0.2669, Recall: 0.3820, F1 Score: 0.2915, AUC: 0.5233, R2 Score: -0.003929, MAE: 1.7456, MSE: 4.8650
Training: Fold 4 - Total Loss: 2.4793, Cross Entropy: 1.237262, Accuracy: 0.4155, Precision: 0.2880, Recall: 0.4155, F1 Score: 0.3200, AUC: 0.5271, R2 Score: -0.005189, MAE: 1.8488, MSE: 5.3773
Validation: Fold 5 - Total Loss: 2.4169, Cross Entropy: 1.210903, Accuracy: 0.3803, Precision: 0.2118, Recall: 0.3803, F1 Score: 0.2265, AUC: 0.5788, R2 Score: 0.010329, MAE: 1.8095, MSE: 5.2310
Avg Latency (ms): 3.32, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4362, Cross Entropy: 1.227526, Accuracy: 0.4278, Precision: 0.3372, Recall: 0.4278, F1 Score: 0.2957, AUC: 0.5138, R2 Score: -0.004012, MAE: 1.8399, MSE: 5.2564
Training: Fold 2 - Total Loss: 2.3529, Cross Entropy: 1.225708, Accuracy: 0.3961, Precision: 0.2888, Recall: 0.3961, F1 Score: 0.2888, AUC: 0.5162, R2 Score: -0.009120, MAE: 1.7736, MSE: 4.9829
Training: Fold 3 - Total Loss: 2.3419, Cross Entropy: 1.246135, Accuracy: 0.3592, Precision: 0.2529, Recall: 0.3592, F1 Score: 0.2957, AUC: 0.5221, R2 Score: -0.012203, MAE: 1.7546, MSE: 4.8987
Training: Fold 4 - Total Loss: 2.4692, Cross Entropy: 1.233280, Accuracy: 0.4085, Precision: 0.2824, Recall: 0.4085, F1 Score: 0.3248, AUC: 0.5420, R2 Score: -0.004067, MAE: 1.8433, MSE: 5.3529
Validation: Fold 5 - Total Loss: 2.4099, Cross Entropy: 1.202140, Accuracy: 0.3873, Precision: 0.2542, Recall: 0.3873, F1 Score: 0.2397, AUC: 0.5883, R2 Score: 0.008243, MAE: 1.8123, MSE: 5.2279
Avg Latency (ms): 3.33, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 14/150
Training: Fold 1 - Total Loss: 2.4439, Cross Entropy: 1.228878, Accuracy: 0.4137, Precision: 0.3099, Recall: 0.4137, F1 Score: 0.2655, AUC: 0.5490, R2 Score: 0.005237, MAE: 1.8435, MSE: 5.2790
Training: Fold 2 - Total Loss: 2.3556, Cross Entropy: 1.229963, Accuracy: 0.3891, Precision: 0.2807, Recall: 0.3891, F1 Score: 0.2859, AUC: 0.5193, R2 Score: -0.008241, MAE: 1.7702, MSE: 4.9819
Training: Fold 3 - Total Loss: 2.3555, Cross Entropy: 1.252331, Accuracy: 0.3627, Precision: 0.2586, Recall: 0.3627, F1 Score: 0.3019, AUC: 0.4875, R2 Score: -0.009037, MAE: 1.7524, MSE: 4.9296
Training: Fold 4 - Total Loss: 2.4734, Cross Entropy: 1.236442, Accuracy: 0.3996, Precision: 0.2823, Recall: 0.3996, F1 Score: 0.3254, AUC: 0.5255, R2 Score: 0.000483, MAE: 1.8406, MSE: 5.3597
Validation: Fold 5 - Total Loss: 2.4212, Cross Entropy: 1.208514, Accuracy: 0.3732, Precision: 0.1488, Recall: 0.3732, F1 Score: 0.2127, AUC: 0.5952, R2 Score: 0.009660, MAE: 1.8175, MSE: 5.2508
Avg Latency (ms): 3.34, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 15/150
Training: Fold 1 - Total Loss: 2.4484, Cross Entropy: 1.225594, Accuracy: 0.4137, Precision: 0.3061, Recall: 0.4137, F1 Score: 0.2896, AUC: 0.5385, R2 Score: -0.008976, MAE: 1.8470, MSE: 5.3015
Training: Fold 2 - Total Loss: 2.3714, Cross Entropy: 1.230129, Accuracy: 0.3908, Precision: 0.2599, Recall: 0.3908, F1 Score: 0.2651, AUC: 0.5299, R2 Score: -0.018156, MAE: 1.7810, MSE: 5.0343
Training: Fold 3 - Total Loss: 2.3376, Cross Entropy: 1.244329, Accuracy: 0.3556, Precision: 0.2457, Recall: 0.3556, F1 Score: 0.2647, AUC: 0.5299, R2 Score: -0.005377, MAE: 1.7518, MSE: 4.8887
Training: Fold 4 - Total Loss: 2.4770, Cross Entropy: 1.244263, Accuracy: 0.4085, Precision: 0.2897, Recall: 0.4085, F1 Score: 0.3328, AUC: 0.5083, R2 Score: -0.008602, MAE: 1.8418, MSE: 5.3533
Validation: Fold 5 - Total Loss: 2.4220, Cross Entropy: 1.204025, Accuracy: 0.3944, Precision: 0.3065, Recall: 0.3944, F1 Score: 0.2426, AUC: 0.6132, R2 Score: 0.005686, MAE: 1.8122, MSE: 5.2638
Avg Latency (ms): 3.30, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 16/150
Training: Fold 1 - Total Loss: 2.4430, Cross Entropy: 1.219266, Accuracy: 0.3996, Precision: 0.2811, Recall: 0.3996, F1 Score: 0.3019, AUC: 0.5631, R2 Score: 0.002287, MAE: 1.8488, MSE: 5.2983
Training: Fold 2 - Total Loss: 2.3551, Cross Entropy: 1.228552, Accuracy: 0.3926, Precision: 0.2824, Recall: 0.3926, F1 Score: 0.3138, AUC: 0.5164, R2 Score: -0.015255, MAE: 1.7736, MSE: 4.9837
Training: Fold 3 - Total Loss: 2.3453, Cross Entropy: 1.245426, Accuracy: 0.3680, Precision: 0.2581, Recall: 0.3680, F1 Score: 0.2860, AUC: 0.5165, R2 Score: -0.011447, MAE: 1.7556, MSE: 4.9117
Training: Fold 4 - Total Loss: 2.4687, Cross Entropy: 1.234546, Accuracy: 0.3926, Precision: 0.2741, Recall: 0.3926, F1 Score: 0.3115, AUC: 0.5366, R2 Score: -0.008425, MAE: 1.8424, MSE: 5.3484
Validation: Fold 5 - Total Loss: 2.4162, Cross Entropy: 1.201175, Accuracy: 0.4155, Precision: 0.3632, Recall: 0.4155, F1 Score: 0.2726, AUC: 0.5818, R2 Score: -0.006289, MAE: 1.8167, MSE: 5.2512
Avg Latency (ms): 3.26, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27
Best model saved with Accuracy: 0.4155

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4259, Cross Entropy: 1.221055, Accuracy: 0.4085, Precision: 0.2824, Recall: 0.4085, F1 Score: 0.2606, AUC: 0.5568, R2 Score: -0.003868, MAE: 1.8347, MSE: 5.2372
Training: Fold 2 - Total Loss: 2.3651, Cross Entropy: 1.226182, Accuracy: 0.3996, Precision: 0.2871, Recall: 0.3996, F1 Score: 0.3203, AUC: 0.5250, R2 Score: 0.004890, MAE: 1.7807, MSE: 5.0225
Training: Fold 3 - Total Loss: 2.3437, Cross Entropy: 1.248030, Accuracy: 0.3644, Precision: 0.2562, Recall: 0.3644, F1 Score: 0.2981, AUC: 0.5175, R2 Score: -0.013895, MAE: 1.7521, MSE: 4.9004
Training: Fold 4 - Total Loss: 2.4574, Cross Entropy: 1.229723, Accuracy: 0.4085, Precision: 0.2847, Recall: 0.4085, F1 Score: 0.3243, AUC: 0.5474, R2 Score: -0.006287, MAE: 1.8325, MSE: 5.3220
Validation: Fold 5 - Total Loss: 2.4074, Cross Entropy: 1.203056, Accuracy: 0.3873, Precision: 0.3043, Recall: 0.3873, F1 Score: 0.2280, AUC: 0.6099, R2 Score: 0.006912, MAE: 1.8121, MSE: 5.2175
Avg Latency (ms): 3.33, Avg Memory Before (MB): 40.03, Avg Memory After (MB): 40.04, Avg Max Memory (MB): 105.27

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4437, Cross Entropy: 1.219621, Accuracy: 0.4049, Precision: 0.2495, Recall: 0.4049, F1 Score: 0.2485, AUC: 0.5435, R2 Score: -0.007236, MAE: 1.8473, MSE: 5.2999
Training: Fold 2 - Total Loss: 2.3562, Cross Entropy: 1.224238, Accuracy: 0.3944, Precision: 0.2754, Recall: 0.3944, F1 Score: 0.3015, AUC: 0.5308, R2 Score: -0.006107, MAE: 1.7755, MSE: 4.9974
Training: Fold 3 - Total Loss: 2.3440, Cross Entropy: 1.240672, Accuracy: 0.3785, Precision: 0.2714, Recall: 0.3785, F1 Score: 0.3159, AUC: 0.5216, R2 Score: -0.005851, MAE: 1.7549, MSE: 4.9185
Training: Fold 4 - Total Loss: 2.4758, Cross Entropy: 1.234157, Accuracy: 0.3856, Precision: 0.2610, Recall: 0.3856, F1 Score: 0.2989, AUC: 0.5439, R2 Score: -0.014230, MAE: 1.8427, MSE: 5.3728
Validation: Fold 5 - Total Loss: 2.4066, Cross Entropy: 1.202218, Accuracy: 0.3873, Precision: 0.2538, Recall: 0.3873, F1 Score: 0.2288, AUC: 0.5710, R2 Score: 0.005982, MAE: 1.8084, MSE: 5.2169

### RegNetY-400MF

RegNet is an automated architecture developed by **Facebook AI Research (FAIR)** that optimizes the design of deep neural networks. The **RegNetY-400MF** variant is a computationally efficient model designed for **real-time inference and deployment on edge devices**. Unlike handcrafted architectures, RegNet is **automatically searched and optimized**, leading to a **well-balanced trade-off between accuracy, speed, and resource efficiency**.

- **Paper:** Radosavovic, I., Kosaraju, R. P., Girshick, R., He, K., & Dollár, P. (2020). *Designing Network Design Spaces*. [CVPR](https://arxiv.org/abs/2003.13678).

In [ ]:
ARCH = "regnety-400mf"
main(ARCH)

====================================================================================================
Training Model: regnety-400mf
Initial Backbone Model Size: 17.61 MB
Modified Backbone Model Size: 16.07 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 28.4346, Cross Entropy: 1.544092, Accuracy: 0.1954, Precision: 0.5283, Recall: 0.1954, F1 Score: 0.0697, AUC: 0.4441, R2 Score: -16.419150, MAE: 9.2018, MSE: 91.1792
Training: Fold 2 - Total Loss: 13.8127, Cross Entropy: 1.505220, Accuracy: 0.2095, Precision: 0.6099, Recall: 0.2095, F1 Score: 0.0802, AUC: 0.4967, R2 Score: -7.544186, MAE: 6.0488, MSE: 42.5303
Training: Fold 3 - Total Loss: 4.8217, Cross Entropy: 1.499956, Accuracy: 0.2271, Precision: 0.1821, Recall: 0.2271, F1 Score: 0.1233, AUC: 0.5180, R2 Score: -1.530897, MAE: 2.9719, MSE: 12.5724
Training: Fold 4 - Total Loss: 2.6892, Cross Entropy: 1.338459, Accuracy: 0.4067, Precision: 0.2378, Recall: 0.4067, F1 Score: 0.2918, AUC: 0.4854, R2 Score: -0.078151, MAE: 1.9342, MSE: 5.8411
Validation: Fold 5 - Total Loss: 2.4844, Cross Entropy: 1.227183, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6112, R2 Score: -0.028136, MAE: 1.8323, MSE: 5.4181
Avg Latency (ms): 7.67, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 2.5274, Cross Entropy: 1.255465, Accuracy: 0.3944, Precision: 0.3436, Recall: 0.3944, F1 Score: 0.3141, AUC: 0.5198, R2 Score: -0.054094, MAE: 1.8832, MSE: 5.4951
Training: Fold 2 - Total Loss: 2.4200, Cross Entropy: 1.241110, Accuracy: 0.3926, Precision: 0.2867, Recall: 0.3926, F1 Score: 0.3311, AUC: 0.5266, R2 Score: -0.025721, MAE: 1.8146, MSE: 5.1707
Training: Fold 3 - Total Loss: 2.3689, Cross Entropy: 1.242534, Accuracy: 0.3926, Precision: 0.3059, Recall: 0.3926, F1 Score: 0.3270, AUC: 0.5492, R2 Score: -0.044732, MAE: 1.7788, MSE: 4.9971
Training: Fold 4 - Total Loss: 2.5102, Cross Entropy: 1.234293, Accuracy: 0.4173, Precision: 0.3369, Recall: 0.4173, F1 Score: 0.3452, AUC: 0.5507, R2 Score: -0.044337, MAE: 1.8684, MSE: 5.4873
Validation: Fold 5 - Total Loss: 2.4171, Cross Entropy: 1.194067, Accuracy: 0.3803, Precision: 0.2707, Recall: 0.3803, F1 Score: 0.2530, AUC: 0.6095, R2 Score: -0.003738, MAE: 1.8145, MSE: 5.2709
Avg Latency (ms): 4.33, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4688, Cross Entropy: 1.223406, Accuracy: 0.4208, Precision: 0.3566, Recall: 0.4208, F1 Score: 0.3362, AUC: 0.5571, R2 Score: -0.036693, MAE: 1.8617, MSE: 5.3746
Training: Fold 2 - Total Loss: 2.4067, Cross Entropy: 1.246034, Accuracy: 0.3926, Precision: 0.2776, Recall: 0.3926, F1 Score: 0.3182, AUC: 0.5121, R2 Score: -0.027497, MAE: 1.7998, MSE: 5.1149
Training: Fold 3 - Total Loss: 2.3947, Cross Entropy: 1.251890, Accuracy: 0.3750, Precision: 0.2688, Recall: 0.3750, F1 Score: 0.3131, AUC: 0.5196, R2 Score: -0.062033, MAE: 1.7853, MSE: 5.0612
Training: Fold 4 - Total Loss: 2.5051, Cross Entropy: 1.231401, Accuracy: 0.3996, Precision: 0.3352, Recall: 0.3996, F1 Score: 0.3460, AUC: 0.5565, R2 Score: -0.021946, MAE: 1.8673, MSE: 5.4770
Validation: Fold 5 - Total Loss: 2.4022, Cross Entropy: 1.171103, Accuracy: 0.4366, Precision: 0.3256, Recall: 0.4366, F1 Score: 0.3293, AUC: 0.6257, R2 Score: -0.006466, MAE: 1.8139, MSE: 5.2747
Avg Latency (ms): 4.29, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.4366

Epoch 4/150
Training: Fold 1 - Total Loss: 2.4679, Cross Entropy: 1.210122, Accuracy: 0.4454, Precision: 0.3911, Recall: 0.4454, F1 Score: 0.3622, AUC: 0.5722, R2 Score: -0.041731, MAE: 1.8694, MSE: 5.4027
Training: Fold 2 - Total Loss: 2.3816, Cross Entropy: 1.216096, Accuracy: 0.4384, Precision: 0.3735, Recall: 0.4384, F1 Score: 0.3743, AUC: 0.5479, R2 Score: -0.031317, MAE: 1.8005, MSE: 5.1012
Training: Fold 3 - Total Loss: 2.3556, Cross Entropy: 1.237454, Accuracy: 0.3838, Precision: 0.3022, Recall: 0.3838, F1 Score: 0.3151, AUC: 0.5591, R2 Score: -0.018538, MAE: 1.7684, MSE: 4.9645
Training: Fold 4 - Total Loss: 2.4884, Cross Entropy: 1.224764, Accuracy: 0.4208, Precision: 0.3456, Recall: 0.4208, F1 Score: 0.3634, AUC: 0.5531, R2 Score: -0.016419, MAE: 1.8621, MSE: 5.4369
Validation: Fold 5 - Total Loss: 2.3686, Cross Entropy: 1.137940, Accuracy: 0.4648, Precision: 0.3257, Recall: 0.4648, F1 Score: 0.3740, AUC: 0.6818, R2 Score: 0.019980, MAE: 1.8117, MSE: 5.2400
Avg Latency (ms): 4.05, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.4648

Epoch 5/150
Training: Fold 1 - Total Loss: 2.4434, Cross Entropy: 1.188018, Accuracy: 0.4842, Precision: 0.4185, Recall: 0.4842, F1 Score: 0.4075, AUC: 0.6086, R2 Score: -0.022780, MAE: 1.8648, MSE: 5.3727
Training: Fold 2 - Total Loss: 2.3914, Cross Entropy: 1.206472, Accuracy: 0.4296, Precision: 0.3455, Recall: 0.4296, F1 Score: 0.3667, AUC: 0.5721, R2 Score: -0.061248, MAE: 1.8083, MSE: 5.1561
Training: Fold 3 - Total Loss: 2.3590, Cross Entropy: 1.220100, Accuracy: 0.4102, Precision: 0.3323, Recall: 0.4102, F1 Score: 0.3488, AUC: 0.5752, R2 Score: -0.004474, MAE: 1.7772, MSE: 5.0164
Training: Fold 4 - Total Loss: 2.4730, Cross Entropy: 1.202287, Accuracy: 0.4718, Precision: 0.3995, Recall: 0.4718, F1 Score: 0.4111, AUC: 0.5857, R2 Score: -0.031941, MAE: 1.8591, MSE: 5.4380
Validation: Fold 5 - Total Loss: 2.3655, Cross Entropy: 1.141835, Accuracy: 0.4577, Precision: 0.3267, Recall: 0.4577, F1 Score: 0.3656, AUC: 0.6051, R2 Score: 0.007252, MAE: 1.8115, MSE: 5.2207
Avg Latency (ms): 4.27, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4597, Cross Entropy: 1.205924, Accuracy: 0.4278, Precision: 0.3128, Recall: 0.4278, F1 Score: 0.3601, AUC: 0.5659, R2 Score: -0.049356, MAE: 1.8657, MSE: 5.3853
Training: Fold 2 - Total Loss: 2.3562, Cross Entropy: 1.190949, Accuracy: 0.4577, Precision: 0.3410, Recall: 0.4577, F1 Score: 0.3904, AUC: 0.5970, R2 Score: -0.040608, MAE: 1.7965, MSE: 5.0752
Training: Fold 3 - Total Loss: 2.3448, Cross Entropy: 1.199630, Accuracy: 0.4225, Precision: 0.3322, Recall: 0.4225, F1 Score: 0.3582, AUC: 0.6006, R2 Score: -0.043062, MAE: 1.7798, MSE: 5.0169
Training: Fold 4 - Total Loss: 2.4454, Cross Entropy: 1.169980, Accuracy: 0.4542, Precision: 0.3908, Recall: 0.4542, F1 Score: 0.4001, AUC: 0.6254, R2 Score: -0.029559, MAE: 1.8563, MSE: 5.4214
Validation: Fold 5 - Total Loss: 2.3613, Cross Entropy: 1.128266, Accuracy: 0.4014, Precision: 0.2504, Recall: 0.4014, F1 Score: 0.2885, AUC: 0.6377, R2 Score: 0.017822, MAE: 1.8088, MSE: 5.2383
Avg Latency (ms): 4.59, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4371, Cross Entropy: 1.179494, Accuracy: 0.4507, Precision: 0.3337, Recall: 0.4507, F1 Score: 0.3834, AUC: 0.5829, R2 Score: -0.049093, MAE: 1.8596, MSE: 5.3714
Training: Fold 2 - Total Loss: 2.3417, Cross Entropy: 1.172484, Accuracy: 0.4454, Precision: 0.3587, Recall: 0.4454, F1 Score: 0.3841, AUC: 0.6020, R2 Score: -0.021303, MAE: 1.7956, MSE: 5.0698
Training: Fold 3 - Total Loss: 2.3153, Cross Entropy: 1.175957, Accuracy: 0.4525, Precision: 0.4170, Recall: 0.4525, F1 Score: 0.3900, AUC: 0.6008, R2 Score: -0.034975, MAE: 1.7710, MSE: 4.9738
Training: Fold 4 - Total Loss: 2.4576, Cross Entropy: 1.169828, Accuracy: 0.4437, Precision: 0.3478, Recall: 0.4437, F1 Score: 0.3857, AUC: 0.6266, R2 Score: -0.014646, MAE: 1.8685, MSE: 5.4623
Validation: Fold 5 - Total Loss: 2.3673, Cross Entropy: 1.122850, Accuracy: 0.4859, Precision: 0.3373, Recall: 0.4859, F1 Score: 0.3890, AUC: 0.6447, R2 Score: 0.000360, MAE: 1.8173, MSE: 5.2711
Avg Latency (ms): 4.45, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.4859

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4408, Cross Entropy: 1.167655, Accuracy: 0.4665, Precision: 0.4268, Recall: 0.4665, F1 Score: 0.4021, AUC: 0.6168, R2 Score: -0.041805, MAE: 1.8727, MSE: 5.4116
Training: Fold 2 - Total Loss: 2.3579, Cross Entropy: 1.183671, Accuracy: 0.4472, Precision: 0.3783, Recall: 0.4472, F1 Score: 0.3852, AUC: 0.5779, R2 Score: -0.034168, MAE: 1.7998, MSE: 5.0977
Training: Fold 3 - Total Loss: 2.3114, Cross Entropy: 1.167570, Accuracy: 0.4701, Precision: 0.4410, Recall: 0.4701, F1 Score: 0.4030, AUC: 0.6231, R2 Score: -0.034547, MAE: 1.7723, MSE: 4.9802
Training: Fold 4 - Total Loss: 2.4480, Cross Entropy: 1.156684, Accuracy: 0.4613, Precision: 0.3759, Recall: 0.4613, F1 Score: 0.4030, AUC: 0.6239, R2 Score: -0.017988, MAE: 1.8648, MSE: 5.4611
Validation: Fold 5 - Total Loss: 2.3216, Cross Entropy: 1.073017, Accuracy: 0.5282, Precision: 0.3682, Recall: 0.5282, F1 Score: 0.4317, AUC: 0.6956, R2 Score: 0.017884, MAE: 1.8094, MSE: 5.2350
Avg Latency (ms): 4.48, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.5282

Epoch 9/150
Training: Fold 1 - Total Loss: 2.4463, Cross Entropy: 1.160717, Accuracy: 0.4877, Precision: 0.4034, Recall: 0.4877, F1 Score: 0.4224, AUC: 0.6113, R2 Score: -0.044884, MAE: 1.8723, MSE: 5.4460
Training: Fold 2 - Total Loss: 2.3521, Cross Entropy: 1.161404, Accuracy: 0.4912, Precision: 0.4433, Recall: 0.4912, F1 Score: 0.4261, AUC: 0.6009, R2 Score: -0.039066, MAE: 1.8079, MSE: 5.1305
Training: Fold 3 - Total Loss: 2.3070, Cross Entropy: 1.149707, Accuracy: 0.4894, Precision: 0.4027, Recall: 0.4894, F1 Score: 0.4278, AUC: 0.6470, R2 Score: -0.030109, MAE: 1.7839, MSE: 5.0072
Training: Fold 4 - Total Loss: 2.4332, Cross Entropy: 1.144667, Accuracy: 0.4718, Precision: 0.4041, Recall: 0.4718, F1 Score: 0.4097, AUC: 0.6528, R2 Score: -0.016963, MAE: 1.8580, MSE: 5.4397
Validation: Fold 5 - Total Loss: 2.3007, Cross Entropy: 1.040115, Accuracy: 0.5070, Precision: 0.3518, Recall: 0.5070, F1 Score: 0.4147, AUC: 0.7089, R2 Score: 0.017456, MAE: 1.8182, MSE: 5.2421
Avg Latency (ms): 4.81, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 10/150
Training: Fold 1 - Total Loss: 2.4251, Cross Entropy: 1.160545, Accuracy: 0.4912, Precision: 0.3940, Recall: 0.4912, F1 Score: 0.4223, AUC: 0.6416, R2 Score: -0.011579, MAE: 1.8611, MSE: 5.3756
Training: Fold 2 - Total Loss: 2.3219, Cross Entropy: 1.144192, Accuracy: 0.4930, Precision: 0.4151, Recall: 0.4930, F1 Score: 0.4305, AUC: 0.6315, R2 Score: -0.021323, MAE: 1.7943, MSE: 5.0699
Training: Fold 3 - Total Loss: 2.3024, Cross Entropy: 1.142891, Accuracy: 0.4965, Precision: 0.4866, Recall: 0.4965, F1 Score: 0.4291, AUC: 0.6349, R2 Score: -0.024897, MAE: 1.7774, MSE: 5.0080
Training: Fold 4 - Total Loss: 2.4232, Cross Entropy: 1.116191, Accuracy: 0.5035, Precision: 0.4478, Recall: 0.5035, F1 Score: 0.4386, AUC: 0.6871, R2 Score: -0.047809, MAE: 1.8619, MSE: 5.4730
Validation: Fold 5 - Total Loss: 2.2823, Cross Entropy: 1.013560, Accuracy: 0.5282, Precision: 0.3810, Recall: 0.5282, F1 Score: 0.4393, AUC: 0.6907, R2 Score: 0.009289, MAE: 1.8093, MSE: 5.2427
Avg Latency (ms): 4.67, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 11/150
Training: Fold 1 - Total Loss: 2.3933, Cross Entropy: 1.116442, Accuracy: 0.4930, Precision: 0.4097, Recall: 0.4930, F1 Score: 0.4289, AUC: 0.6788, R2 Score: -0.036603, MAE: 1.8615, MSE: 5.3725
Training: Fold 2 - Total Loss: 2.3098, Cross Entropy: 1.106645, Accuracy: 0.5053, Precision: 0.4595, Recall: 0.5053, F1 Score: 0.4422, AUC: 0.6616, R2 Score: -0.029700, MAE: 1.8006, MSE: 5.1172
Training: Fold 3 - Total Loss: 2.2836, Cross Entropy: 1.130511, Accuracy: 0.4824, Precision: 0.4032, Recall: 0.4824, F1 Score: 0.4203, AUC: 0.6515, R2 Score: -0.027110, MAE: 1.7716, MSE: 4.9740
Training: Fold 4 - Total Loss: 2.4279, Cross Entropy: 1.109443, Accuracy: 0.5070, Precision: 0.4544, Recall: 0.5070, F1 Score: 0.4550, AUC: 0.6714, R2 Score: -0.045582, MAE: 1.8630, MSE: 5.5045
Validation: Fold 5 - Total Loss: 2.2839, Cross Entropy: 1.018276, Accuracy: 0.5423, Precision: 0.3780, Recall: 0.5423, F1 Score: 0.4452, AUC: 0.7219, R2 Score: -0.005913, MAE: 1.8236, MSE: 5.2369
Avg Latency (ms): 4.44, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.5423

Epoch 12/150
Training: Fold 1 - Total Loss: 2.3731, Cross Entropy: 1.091554, Accuracy: 0.5141, Precision: 0.4291, Recall: 0.5141, F1 Score: 0.4527, AUC: 0.6780, R2 Score: -0.022379, MAE: 1.8634, MSE: 5.3633
Training: Fold 2 - Total Loss: 2.3015, Cross Entropy: 1.093292, Accuracy: 0.5387, Precision: 0.4856, Recall: 0.5387, F1 Score: 0.4712, AUC: 0.6805, R2 Score: -0.059986, MAE: 1.8060, MSE: 5.1207
Training: Fold 3 - Total Loss: 2.2852, Cross Entropy: 1.116495, Accuracy: 0.4912, Precision: 0.4444, Recall: 0.4912, F1 Score: 0.4504, AUC: 0.6779, R2 Score: -0.038824, MAE: 1.7830, MSE: 5.0123
Training: Fold 4 - Total Loss: 2.3999, Cross Entropy: 1.094528, Accuracy: 0.5018, Precision: 0.4507, Recall: 0.5018, F1 Score: 0.4518, AUC: 0.7014, R2 Score: -0.024784, MAE: 1.8581, MSE: 5.4459
Validation: Fold 5 - Total Loss: 2.2792, Cross Entropy: 0.997127, Accuracy: 0.5282, Precision: 0.3755, Recall: 0.5282, F1 Score: 0.4386, AUC: 0.7206, R2 Score: -0.029259, MAE: 1.8115, MSE: 5.2706
Avg Latency (ms): 4.69, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 13/150
Training: Fold 1 - Total Loss: 2.3699, Cross Entropy: 1.075641, Accuracy: 0.5387, Precision: 0.4612, Recall: 0.5387, F1 Score: 0.4750, AUC: 0.7051, R2 Score: -0.028937, MAE: 1.8673, MSE: 5.3898
Training: Fold 2 - Total Loss: 2.2710, Cross Entropy: 1.054722, Accuracy: 0.5528, Precision: 0.4926, Recall: 0.5528, F1 Score: 0.4900, AUC: 0.7112, R2 Score: -0.018894, MAE: 1.8010, MSE: 5.1089
Training: Fold 3 - Total Loss: 2.2288, Cross Entropy: 1.053363, Accuracy: 0.5335, Precision: 0.4777, Recall: 0.5335, F1 Score: 0.4771, AUC: 0.7317, R2 Score: -0.057778, MAE: 1.7685, MSE: 4.9716
Training: Fold 4 - Total Loss: 2.4017, Cross Entropy: 1.080311, Accuracy: 0.5335, Precision: 0.4839, Recall: 0.5335, F1 Score: 0.4949, AUC: 0.7033, R2 Score: -0.034190, MAE: 1.8724, MSE: 5.4848
Validation: Fold 5 - Total Loss: 2.2607, Cross Entropy: 0.992259, Accuracy: 0.5141, Precision: 0.5827, Recall: 0.5141, F1 Score: 0.4268, AUC: 0.7432, R2 Score: 0.003986, MAE: 1.8114, MSE: 5.2205
Avg Latency (ms): 4.70, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 14/150
Training: Fold 1 - Total Loss: 2.3453, Cross Entropy: 1.057549, Accuracy: 0.5387, Precision: 0.4561, Recall: 0.5387, F1 Score: 0.4812, AUC: 0.7175, R2 Score: -0.026376, MAE: 1.8569, MSE: 5.3499
Training: Fold 2 - Total Loss: 2.2705, Cross Entropy: 1.059204, Accuracy: 0.5211, Precision: 0.4544, Recall: 0.5211, F1 Score: 0.4730, AUC: 0.6889, R2 Score: -0.019622, MAE: 1.7941, MSE: 5.0968
Training: Fold 3 - Total Loss: 2.2913, Cross Entropy: 1.095894, Accuracy: 0.5176, Precision: 0.4485, Recall: 0.5176, F1 Score: 0.4663, AUC: 0.7102, R2 Score: -0.033320, MAE: 1.7862, MSE: 5.0805
Training: Fold 4 - Total Loss: 2.3969, Cross Entropy: 1.074862, Accuracy: 0.5106, Precision: 0.4452, Recall: 0.5106, F1 Score: 0.4644, AUC: 0.7085, R2 Score: -0.062017, MAE: 1.8661, MSE: 5.4818
Validation: Fold 5 - Total Loss: 2.2772, Cross Entropy: 0.995486, Accuracy: 0.5915, Precision: 0.6622, Recall: 0.5915, F1 Score: 0.5036, AUC: 0.7384, R2 Score: -0.019697, MAE: 1.8192, MSE: 5.2680
Avg Latency (ms): 4.58, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.5915

Epoch 15/150
Training: Fold 1 - Total Loss: 2.3547, Cross Entropy: 1.052356, Accuracy: 0.5616, Precision: 0.4933, Recall: 0.5616, F1 Score: 0.5076, AUC: 0.7201, R2 Score: -0.041004, MAE: 1.8616, MSE: 5.3934
Training: Fold 2 - Total Loss: 2.2412, Cross Entropy: 1.027688, Accuracy: 0.5599, Precision: 0.5088, Recall: 0.5599, F1 Score: 0.5178, AUC: 0.7203, R2 Score: -0.013692, MAE: 1.7966, MSE: 5.0729
Training: Fold 3 - Total Loss: 2.2129, Cross Entropy: 1.046905, Accuracy: 0.5405, Precision: 0.4838, Recall: 0.5405, F1 Score: 0.4956, AUC: 0.7299, R2 Score: -0.008576, MAE: 1.7632, MSE: 4.9336
Training: Fold 4 - Total Loss: 2.3794, Cross Entropy: 1.054713, Accuracy: 0.5352, Precision: 0.4729, Recall: 0.5352, F1 Score: 0.4987, AUC: 0.7220, R2 Score: -0.033173, MAE: 1.8630, MSE: 5.4703
Validation: Fold 5 - Total Loss: 2.2295, Cross Entropy: 0.944450, Accuracy: 0.5845, Precision: 0.5984, Recall: 0.5845, F1 Score: 0.5117, AUC: 0.7568, R2 Score: 0.022428, MAE: 1.8081, MSE: 5.2281
Avg Latency (ms): 4.57, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 16/150
Training: Fold 1 - Total Loss: 2.3272, Cross Entropy: 1.026703, Accuracy: 0.5651, Precision: 0.4967, Recall: 0.5651, F1 Score: 0.5079, AUC: 0.7210, R2 Score: -0.018863, MAE: 1.8632, MSE: 5.3618
Training: Fold 2 - Total Loss: 2.2412, Cross Entropy: 0.998850, Accuracy: 0.5563, Precision: 0.4828, Recall: 0.5563, F1 Score: 0.5012, AUC: 0.7391, R2 Score: -0.054238, MAE: 1.8101, MSE: 5.1401
Training: Fold 3 - Total Loss: 2.2324, Cross Entropy: 1.036407, Accuracy: 0.5546, Precision: 0.4981, Recall: 0.5546, F1 Score: 0.5210, AUC: 0.7342, R2 Score: -0.025103, MAE: 1.7801, MSE: 5.0229
Training: Fold 4 - Total Loss: 2.3174, Cross Entropy: 1.001406, Accuracy: 0.5792, Precision: 0.5233, Recall: 0.5792, F1 Score: 0.5329, AUC: 0.7590, R2 Score: -0.030281, MAE: 1.8502, MSE: 5.3879
Validation: Fold 5 - Total Loss: 2.3308, Cross Entropy: 1.126671, Accuracy: 0.5423, Precision: 0.5511, Recall: 0.5423, F1 Score: 0.4607, AUC: 0.7761, R2 Score: 0.074506, MAE: 1.7983, MSE: 5.1406
Avg Latency (ms): 4.71, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19

Epoch 17/150
Training: Fold 1 - Total Loss: 2.2956, Cross Entropy: 0.995342, Accuracy: 0.5722, Precision: 0.5205, Recall: 0.5722, F1 Score: 0.5366, AUC: 0.7631, R2 Score: -0.029988, MAE: 1.8536, MSE: 5.3296
Training: Fold 2 - Total Loss: 2.2380, Cross Entropy: 1.020616, Accuracy: 0.5651, Precision: 0.5155, Recall: 0.5651, F1 Score: 0.5342, AUC: 0.7295, R2 Score: -0.021213, MAE: 1.7938, MSE: 5.0787
Training: Fold 3 - Total Loss: 2.2077, Cross Entropy: 1.030395, Accuracy: 0.5546, Precision: 0.5008, Recall: 0.5546, F1 Score: 0.5123, AUC: 0.7251, R2 Score: -0.028445, MAE: 1.7675, MSE: 4.9547
Training: Fold 4 - Total Loss: 2.3669, Cross Entropy: 1.024597, Accuracy: 0.5563, Precision: 0.5114, Recall: 0.5563, F1 Score: 0.5266, AUC: 0.7483, R2 Score: -0.033994, MAE: 1.8656, MSE: 5.4991
Validation: Fold 5 - Total Loss: 2.1747, Cross Entropy: 0.865765, Accuracy: 0.6408, Precision: 0.6456, Recall: 0.6408, F1 Score: 0.5812, AUC: 0.7993, R2 Score: 0.000139, MAE: 1.8151, MSE: 5.2288
Avg Latency (ms): 4.74, Avg Memory Before (MB): 93.33, Avg Memory After (MB): 93.33, Avg Max Memory (MB): 285.19
Best model saved with Accuracy: 0.6408

Epoch 18/150
Training: Fold 1 - Total Loss: 2.3137, Cross Entropy: 0.975275, Accuracy: 0.5880, Precision: 0.5371, Recall: 0.5880, F1 Score: 0.5526, AUC: 0.7689, R2 Score: -0.049364, MAE: 1.8744, MSE: 5.4367
Training: Fold 2 - Total Loss: 2.2167, Cross Entropy: 0.970282, Accuracy: 0.5845, Precision: 0.5258, Recall: 0.5845, F1 Score: 0.5422, AUC: 0.7662, R2 Score: -0.022633, MAE: 1.8005, MSE: 5.1249
Training: Fold 3 - Total Loss: 2.1669, Cross Entropy: 0.960544, Accuracy: 0.6039, Precision: 0.5379, Recall: 0.6039, F1 Score: 0.5543, AUC: 0.7906, R2 Score: -0.023527, MAE: 1.7716, MSE: 4.9817
Training: Fold 4 - Total Loss: 2.3452, Cross Entropy: 1.020492, Accuracy: 0.5405, Precision: 0.5033, Recall: 0.5405, F1 Score: 0.5206, AUC: 0.7425, R2 Score: -0.032035, MAE: 1.8618, MSE: 5.4362

### MNASNet-0.5

MNASNet was developed by Google as part of the **AutoML** framework to **optimize inference speed on mobile processors**. Unlike traditional CNNs, MNASNet **co-optimizes both accuracy and latency** using **neural architecture search (NAS)**, making it highly efficient for mobile applications.

- **Paper:** Tan, M., Chen, B., Pang, R., et al. (2019). *MNASNet: Platform-Aware Neural Architecture Search for Mobile*. [CVPR](https://arxiv.org/abs/1807.11626).

In [ ]:
ARCH = "mnasnet0_5"
main(ARCH)

====================================================================================================
Training Model: mnasnet0_5
Initial Backbone Model Size: 9.04 MB
Modified Backbone Model Size: 4.58 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 26.5084, Cross Entropy: 1.406275, Accuracy: 0.2887, Precision: 0.1517, Recall: 0.2887, F1 Score: 0.1636, AUC: 0.4973, R2 Score: -15.342455, MAE: 8.8847, MSE: 85.0801
Training: Fold 2 - Total Loss: 13.6912, Cross Entropy: 1.441895, Accuracy: 0.3292, Precision: 0.1084, Recall: 0.3292, F1 Score: 0.1631, AUC: 0.4538, R2 Score: -7.509303, MAE: 6.0653, MSE: 42.2729
Training: Fold 3 - Total Loss: 5.5435, Cross Entropy: 1.383584, Accuracy: 0.3345, Precision: 0.1119, Recall: 0.3345, F1 Score: 0.1677, AUC: 0.5056, R2 Score: -2.139514, MAE: 3.3790, MSE: 15.2498
Training: Fold 4 - Total Loss: 2.8663, Cross Entropy: 1.279760, Accuracy: 0.3732, Precision: 0.2758, Recall: 0.3732, F1 Score: 0.3167, AUC: 0.5099, R2 Score: -0.245124, MAE: 2.0860, MSE: 6.5682
Validation: Fold 5 - Total Loss: 34.2503, Cross Entropy: 1.373438, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4918, R2 Score: -20.466059, MAE: 10.2828, MSE: 110.9629
Avg Latency (ms): 3.88, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76
Best model saved with Accuracy: 0.3099

Epoch 2/150
Training: Fold 1 - Total Loss: 2.4917, Cross Entropy: 1.242708, Accuracy: 0.4085, Precision: 0.1668, Recall: 0.4085, F1 Score: 0.2369, AUC: 0.4914, R2 Score: -0.023551, MAE: 1.8622, MSE: 5.4059
Training: Fold 2 - Total Loss: 2.3871, Cross Entropy: 1.235366, Accuracy: 0.4014, Precision: 0.2177, Recall: 0.4014, F1 Score: 0.2348, AUC: 0.4898, R2 Score: -0.012106, MAE: 1.7924, MSE: 5.0746
Training: Fold 3 - Total Loss: 2.3501, Cross Entropy: 1.248271, Accuracy: 0.3803, Precision: 0.3109, Recall: 0.3803, F1 Score: 0.2149, AUC: 0.5172, R2 Score: 0.023761, MAE: 1.7578, MSE: 4.9212
Training: Fold 4 - Total Loss: 2.5024, Cross Entropy: 1.245422, Accuracy: 0.4173, Precision: 0.2679, Recall: 0.4173, F1 Score: 0.2556, AUC: 0.4883, R2 Score: -0.027640, MAE: 1.8551, MSE: 5.4355
Validation: Fold 5 - Total Loss: 33.4991, Cross Entropy: 1.367124, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4729, R2 Score: -19.976619, MAE: 10.1610, MSE: 108.4738
Avg Latency (ms): 1.99, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4542, Cross Entropy: 1.231314, Accuracy: 0.4067, Precision: 0.1664, Recall: 0.4067, F1 Score: 0.2362, AUC: 0.5099, R2 Score: -0.006948, MAE: 1.8515, MSE: 5.3077
Training: Fold 2 - Total Loss: 2.3871, Cross Entropy: 1.236186, Accuracy: 0.3944, Precision: 0.2695, Recall: 0.3944, F1 Score: 0.2449, AUC: 0.4777, R2 Score: -0.015072, MAE: 1.7893, MSE: 5.0724
Training: Fold 3 - Total Loss: 2.3513, Cross Entropy: 1.248359, Accuracy: 0.3750, Precision: 0.2632, Recall: 0.3750, F1 Score: 0.2827, AUC: 0.4909, R2 Score: 0.000441, MAE: 1.7553, MSE: 4.9249
Training: Fold 4 - Total Loss: 2.4688, Cross Entropy: 1.235098, Accuracy: 0.4225, Precision: 0.3166, Recall: 0.4225, F1 Score: 0.2764, AUC: 0.5445, R2 Score: -0.021654, MAE: 1.8412, MSE: 5.3473
Validation: Fold 5 - Total Loss: 32.6303, Cross Entropy: 1.361882, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5386, R2 Score: -19.409690, MAE: 10.0181, MSE: 105.5900
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 4/150
Training: Fold 1 - Total Loss: 2.4564, Cross Entropy: 1.234774, Accuracy: 0.4067, Precision: 0.1667, Recall: 0.4067, F1 Score: 0.2365, AUC: 0.5046, R2 Score: -0.022845, MAE: 1.8457, MSE: 5.3069
Training: Fold 2 - Total Loss: 2.3678, Cross Entropy: 1.230940, Accuracy: 0.3944, Precision: 0.2748, Recall: 0.3944, F1 Score: 0.2745, AUC: 0.5216, R2 Score: -0.003511, MAE: 1.7798, MSE: 5.0203
Training: Fold 3 - Total Loss: 2.3523, Cross Entropy: 1.250199, Accuracy: 0.3715, Precision: 0.2453, Recall: 0.3715, F1 Score: 0.2375, AUC: 0.4853, R2 Score: -0.017868, MAE: 1.7582, MSE: 4.9238
Training: Fold 4 - Total Loss: 2.4786, Cross Entropy: 1.244402, Accuracy: 0.4173, Precision: 0.2843, Recall: 0.4173, F1 Score: 0.2916, AUC: 0.4869, R2 Score: -0.003299, MAE: 1.8439, MSE: 5.3583
Validation: Fold 5 - Total Loss: 31.8087, Cross Entropy: 1.357431, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4875, R2 Score: -18.873460, MAE: 9.8810, MSE: 102.8618
Avg Latency (ms): 1.99, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76
Best model saved with Accuracy: 0.3873

Epoch 5/150
Training: Fold 1 - Total Loss: 2.4489, Cross Entropy: 1.233871, Accuracy: 0.3996, Precision: 0.2060, Recall: 0.3996, F1 Score: 0.2365, AUC: 0.5120, R2 Score: -0.015113, MAE: 1.8433, MSE: 5.2838
Training: Fold 2 - Total Loss: 2.3559, Cross Entropy: 1.227825, Accuracy: 0.4049, Precision: 0.2793, Recall: 0.4049, F1 Score: 0.2537, AUC: 0.5164, R2 Score: -0.004475, MAE: 1.7768, MSE: 4.9880
Training: Fold 3 - Total Loss: 2.3446, Cross Entropy: 1.250752, Accuracy: 0.3609, Precision: 0.2551, Recall: 0.3609, F1 Score: 0.2976, AUC: 0.4954, R2 Score: -0.009849, MAE: 1.7518, MSE: 4.8970
Training: Fold 4 - Total Loss: 2.4798, Cross Entropy: 1.239930, Accuracy: 0.4032, Precision: 0.2755, Recall: 0.4032, F1 Score: 0.3023, AUC: 0.5195, R2 Score: -0.003140, MAE: 1.8426, MSE: 5.3728
Validation: Fold 5 - Total Loss: 30.8852, Cross Entropy: 1.351654, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4507, R2 Score: -18.271187, MAE: 9.7247, MSE: 99.7968
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4512, Cross Entropy: 1.239113, Accuracy: 0.4085, Precision: 0.3313, Recall: 0.4085, F1 Score: 0.2400, AUC: 0.4992, R2 Score: -0.023822, MAE: 1.8444, MSE: 5.2794
Training: Fold 2 - Total Loss: 2.3706, Cross Entropy: 1.232140, Accuracy: 0.3750, Precision: 0.2694, Recall: 0.3750, F1 Score: 0.3125, AUC: 0.5315, R2 Score: -0.000844, MAE: 1.7815, MSE: 5.0270
Training: Fold 3 - Total Loss: 2.3380, Cross Entropy: 1.247094, Accuracy: 0.3697, Precision: 0.2623, Recall: 0.3697, F1 Score: 0.2574, AUC: 0.5028, R2 Score: -0.020230, MAE: 1.7520, MSE: 4.8834
Training: Fold 4 - Total Loss: 2.4705, Cross Entropy: 1.237775, Accuracy: 0.4190, Precision: 0.2833, Recall: 0.4190, F1 Score: 0.2754, AUC: 0.5135, R2 Score: -0.016127, MAE: 1.8360, MSE: 5.3468
Validation: Fold 5 - Total Loss: 30.0084, Cross Entropy: 1.347067, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4392, R2 Score: -17.699118, MAE: 9.5738, MSE: 96.8847
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4451, Cross Entropy: 1.230465, Accuracy: 0.4049, Precision: 0.2731, Recall: 0.4049, F1 Score: 0.2733, AUC: 0.5280, R2 Score: -0.010716, MAE: 1.8422, MSE: 5.2794
Training: Fold 2 - Total Loss: 2.3866, Cross Entropy: 1.235593, Accuracy: 0.3521, Precision: 0.2459, Recall: 0.3521, F1 Score: 0.2835, AUC: 0.4997, R2 Score: -0.004408, MAE: 1.7877, MSE: 5.0721
Training: Fold 3 - Total Loss: 2.3348, Cross Entropy: 1.245997, Accuracy: 0.3768, Precision: 0.2718, Recall: 0.3768, F1 Score: 0.2665, AUC: 0.5085, R2 Score: -0.010183, MAE: 1.7523, MSE: 4.8753
Training: Fold 4 - Total Loss: 2.4821, Cross Entropy: 1.241231, Accuracy: 0.4120, Precision: 0.2953, Recall: 0.4120, F1 Score: 0.3415, AUC: 0.5094, R2 Score: -0.023105, MAE: 1.8467, MSE: 5.3773
Validation: Fold 5 - Total Loss: 29.0948, Cross Entropy: 1.341832, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4851, R2 Score: -17.103443, MAE: 9.4140, MSE: 93.8516
Avg Latency (ms): 1.99, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4343, Cross Entropy: 1.230735, Accuracy: 0.4014, Precision: 0.1991, Recall: 0.4014, F1 Score: 0.2381, AUC: 0.5404, R2 Score: -0.023544, MAE: 1.8356, MSE: 5.2425
Training: Fold 2 - Total Loss: 2.3647, Cross Entropy: 1.227690, Accuracy: 0.4032, Precision: 0.2807, Recall: 0.4032, F1 Score: 0.2779, AUC: 0.5305, R2 Score: -0.005814, MAE: 1.7797, MSE: 5.0178
Training: Fold 3 - Total Loss: 2.3494, Cross Entropy: 1.246495, Accuracy: 0.3750, Precision: 0.2668, Recall: 0.3750, F1 Score: 0.2588, AUC: 0.5258, R2 Score: -0.002313, MAE: 1.7581, MSE: 4.9228
Training: Fold 4 - Total Loss: 2.4677, Cross Entropy: 1.236485, Accuracy: 0.3979, Precision: 0.2532, Recall: 0.3979, F1 Score: 0.2816, AUC: 0.5172, R2 Score: -0.008971, MAE: 1.8405, MSE: 5.3405
Validation: Fold 5 - Total Loss: 28.2693, Cross Entropy: 1.337147, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5014, R2 Score: -16.565356, MAE: 9.2673, MSE: 91.1110
Avg Latency (ms): 2.14, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 9/150
Training: Fold 1 - Total Loss: 2.4368, Cross Entropy: 1.227472, Accuracy: 0.4137, Precision: 0.3023, Recall: 0.4137, F1 Score: 0.3106, AUC: 0.5208, R2 Score: -0.000373, MAE: 1.8394, MSE: 5.2584
Training: Fold 2 - Total Loss: 2.3513, Cross Entropy: 1.222647, Accuracy: 0.3873, Precision: 0.2721, Recall: 0.3873, F1 Score: 0.2919, AUC: 0.5331, R2 Score: -0.009671, MAE: 1.7757, MSE: 4.9847
Training: Fold 3 - Total Loss: 2.3387, Cross Entropy: 1.245426, Accuracy: 0.3891, Precision: 0.2827, Recall: 0.3891, F1 Score: 0.2941, AUC: 0.5178, R2 Score: -0.003520, MAE: 1.7512, MSE: 4.8898
Training: Fold 4 - Total Loss: 2.4713, Cross Entropy: 1.236012, Accuracy: 0.4155, Precision: 0.2943, Recall: 0.4155, F1 Score: 0.3352, AUC: 0.5287, R2 Score: -0.015265, MAE: 1.8392, MSE: 5.3536
Validation: Fold 5 - Total Loss: 27.3191, Cross Entropy: 1.330837, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5045, R2 Score: -15.946574, MAE: 9.0957, MSE: 87.9584
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 10/150
Training: Fold 1 - Total Loss: 2.4624, Cross Entropy: 1.234147, Accuracy: 0.4120, Precision: 0.3001, Recall: 0.4120, F1 Score: 0.2568, AUC: 0.5272, R2 Score: -0.005121, MAE: 1.8499, MSE: 5.3284
Training: Fold 2 - Total Loss: 2.3741, Cross Entropy: 1.237190, Accuracy: 0.3451, Precision: 0.2454, Recall: 0.3451, F1 Score: 0.2851, AUC: 0.5083, R2 Score: -0.025737, MAE: 1.7857, MSE: 5.0269
Training: Fold 3 - Total Loss: 2.3634, Cross Entropy: 1.256986, Accuracy: 0.3768, Precision: 0.2696, Recall: 0.3768, F1 Score: 0.2544, AUC: 0.4711, R2 Score: -0.027389, MAE: 1.7622, MSE: 4.9450
Training: Fold 4 - Total Loss: 2.4863, Cross Entropy: 1.234653, Accuracy: 0.4085, Precision: 0.2693, Recall: 0.4085, F1 Score: 0.2850, AUC: 0.5363, R2 Score: -0.016693, MAE: 1.8490, MSE: 5.4070
Validation: Fold 5 - Total Loss: 26.4933, Cross Entropy: 1.327555, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4724, R2 Score: -15.407963, MAE: 8.9435, MSE: 85.2134
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4541, Cross Entropy: 1.225737, Accuracy: 0.4155, Precision: 0.3022, Recall: 0.4155, F1 Score: 0.3013, AUC: 0.5290, R2 Score: -0.002581, MAE: 1.8515, MSE: 5.3202
Training: Fold 2 - Total Loss: 2.3480, Cross Entropy: 1.222095, Accuracy: 0.4155, Precision: 0.3096, Recall: 0.4155, F1 Score: 0.2939, AUC: 0.5533, R2 Score: -0.003487, MAE: 1.7728, MSE: 4.9752
Training: Fold 3 - Total Loss: 2.3431, Cross Entropy: 1.245417, Accuracy: 0.3715, Precision: 0.2627, Recall: 0.3715, F1 Score: 0.3062, AUC: 0.5115, R2 Score: -0.003662, MAE: 1.7505, MSE: 4.9044
Training: Fold 4 - Total Loss: 2.4731, Cross Entropy: 1.233291, Accuracy: 0.4085, Precision: 0.2784, Recall: 0.4085, F1 Score: 0.3148, AUC: 0.5553, R2 Score: 0.002087, MAE: 1.8417, MSE: 5.3660
Validation: Fold 5 - Total Loss: 25.5975, Cross Entropy: 1.323167, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4800, R2 Score: -14.824274, MAE: 8.7755, MSE: 82.2376
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 12/150
Training: Fold 1 - Total Loss: 2.4390, Cross Entropy: 1.219567, Accuracy: 0.4085, Precision: 0.2862, Recall: 0.4085, F1 Score: 0.2924, AUC: 0.5560, R2 Score: -0.006056, MAE: 1.8460, MSE: 5.2844
Training: Fold 2 - Total Loss: 2.3526, Cross Entropy: 1.224012, Accuracy: 0.3908, Precision: 0.2802, Recall: 0.3908, F1 Score: 0.3220, AUC: 0.5487, R2 Score: -0.007374, MAE: 1.7731, MSE: 4.9860
Training: Fold 3 - Total Loss: 2.3445, Cross Entropy: 1.236762, Accuracy: 0.4278, Precision: 0.3098, Recall: 0.4278, F1 Score: 0.3349, AUC: 0.5596, R2 Score: -0.003593, MAE: 1.7580, MSE: 4.9294
Training: Fold 4 - Total Loss: 2.4667, Cross Entropy: 1.231007, Accuracy: 0.4067, Precision: 0.2778, Recall: 0.4067, F1 Score: 0.3073, AUC: 0.5331, R2 Score: -0.004222, MAE: 1.8413, MSE: 5.3499
Validation: Fold 5 - Total Loss: 24.7219, Cross Entropy: 1.317049, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5176, R2 Score: -14.254784, MAE: 8.6085, MSE: 79.3332
Avg Latency (ms): 1.99, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4379, Cross Entropy: 1.225922, Accuracy: 0.4085, Precision: 0.2917, Recall: 0.4085, F1 Score: 0.3259, AUC: 0.5419, R2 Score: 0.002814, MAE: 1.8417, MSE: 5.2658
Training: Fold 2 - Total Loss: 2.3523, Cross Entropy: 1.217237, Accuracy: 0.4208, Precision: 0.3024, Recall: 0.4208, F1 Score: 0.3349, AUC: 0.5566, R2 Score: -0.007409, MAE: 1.7756, MSE: 5.0007
Training: Fold 3 - Total Loss: 2.3320, Cross Entropy: 1.239810, Accuracy: 0.3750, Precision: 0.2671, Recall: 0.3750, F1 Score: 0.3120, AUC: 0.5395, R2 Score: -0.002386, MAE: 1.7480, MSE: 4.8803
Training: Fold 4 - Total Loss: 2.4725, Cross Entropy: 1.232739, Accuracy: 0.4067, Precision: 0.2872, Recall: 0.4067, F1 Score: 0.3297, AUC: 0.5372, R2 Score: -0.011886, MAE: 1.8434, MSE: 5.3652
Validation: Fold 5 - Total Loss: 23.9978, Cross Entropy: 1.312112, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4976, R2 Score: -13.783925, MAE: 8.4678, MSE: 76.9310
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 14/150
Training: Fold 1 - Total Loss: 2.4190, Cross Entropy: 1.215765, Accuracy: 0.4120, Precision: 0.2757, Recall: 0.4120, F1 Score: 0.2754, AUC: 0.5679, R2 Score: 0.000203, MAE: 1.8319, MSE: 5.2265
Training: Fold 2 - Total Loss: 2.3771, Cross Entropy: 1.229569, Accuracy: 0.3785, Precision: 0.2771, Recall: 0.3785, F1 Score: 0.3200, AUC: 0.5331, R2 Score: -0.018850, MAE: 1.7833, MSE: 5.0547
Training: Fold 3 - Total Loss: 2.3371, Cross Entropy: 1.234356, Accuracy: 0.4032, Precision: 0.2845, Recall: 0.4032, F1 Score: 0.3315, AUC: 0.5325, R2 Score: -0.018503, MAE: 1.7573, MSE: 4.9101
Training: Fold 4 - Total Loss: 2.4789, Cross Entropy: 1.227943, Accuracy: 0.4208, Precision: 0.2995, Recall: 0.4208, F1 Score: 0.3466, AUC: 0.5579, R2 Score: -0.012224, MAE: 1.8466, MSE: 5.3978
Validation: Fold 5 - Total Loss: 23.2091, Cross Entropy: 1.307826, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4705, R2 Score: -13.270726, MAE: 8.3117, MSE: 74.3119
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 15/150
Training: Fold 1 - Total Loss: 2.4350, Cross Entropy: 1.220916, Accuracy: 0.4190, Precision: 0.3041, Recall: 0.4190, F1 Score: 0.3126, AUC: 0.5561, R2 Score: -0.008847, MAE: 1.8387, MSE: 5.2680
Training: Fold 2 - Total Loss: 2.3437, Cross Entropy: 1.207623, Accuracy: 0.4155, Precision: 0.3004, Recall: 0.4155, F1 Score: 0.3476, AUC: 0.5691, R2 Score: -0.010190, MAE: 1.7786, MSE: 4.9944
Training: Fold 3 - Total Loss: 2.3406, Cross Entropy: 1.234628, Accuracy: 0.4137, Precision: 0.2928, Recall: 0.4137, F1 Score: 0.3421, AUC: 0.5672, R2 Score: -0.017158, MAE: 1.7562, MSE: 4.9212
Training: Fold 4 - Total Loss: 2.4544, Cross Entropy: 1.218877, Accuracy: 0.4225, Precision: 0.3048, Recall: 0.4225, F1 Score: 0.3537, AUC: 0.5559, R2 Score: -0.017406, MAE: 1.8396, MSE: 5.3372
Validation: Fold 5 - Total Loss: 22.5119, Cross Entropy: 1.304957, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5330, R2 Score: -12.816854, MAE: 8.1711, MSE: 71.9948
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 16/150
Training: Fold 1 - Total Loss: 2.4256, Cross Entropy: 1.218030, Accuracy: 0.4296, Precision: 0.3153, Recall: 0.4296, F1 Score: 0.3525, AUC: 0.5581, R2 Score: -0.007011, MAE: 1.8335, MSE: 5.2434
Training: Fold 2 - Total Loss: 2.3631, Cross Entropy: 1.214615, Accuracy: 0.4261, Precision: 0.3089, Recall: 0.4261, F1 Score: 0.3573, AUC: 0.5552, R2 Score: 0.010361, MAE: 1.7831, MSE: 5.0428
Training: Fold 3 - Total Loss: 2.3282, Cross Entropy: 1.230046, Accuracy: 0.4225, Precision: 0.2988, Recall: 0.4225, F1 Score: 0.3487, AUC: 0.5660, R2 Score: -0.017507, MAE: 1.7470, MSE: 4.8906
Training: Fold 4 - Total Loss: 2.4458, Cross Entropy: 1.219404, Accuracy: 0.4225, Precision: 0.3080, Recall: 0.4225, F1 Score: 0.3562, AUC: 0.5826, R2 Score: 0.001117, MAE: 1.8340, MSE: 5.3074
Validation: Fold 5 - Total Loss: 21.6564, Cross Entropy: 1.301530, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5419, R2 Score: -12.260057, MAE: 7.9952, MSE: 69.1511
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4350, Cross Entropy: 1.213924, Accuracy: 0.4401, Precision: 0.3212, Recall: 0.4401, F1 Score: 0.3402, AUC: 0.5744, R2 Score: -0.010332, MAE: 1.8428, MSE: 5.2842
Training: Fold 2 - Total Loss: 2.3471, Cross Entropy: 1.219051, Accuracy: 0.4208, Precision: 0.3073, Recall: 0.4208, F1 Score: 0.3552, AUC: 0.5706, R2 Score: -0.002311, MAE: 1.7726, MSE: 4.9793
Training: Fold 3 - Total Loss: 2.3245, Cross Entropy: 1.218275, Accuracy: 0.4366, Precision: 0.3098, Recall: 0.4366, F1 Score: 0.3620, AUC: 0.5807, R2 Score: -0.014797, MAE: 1.7506, MSE: 4.9057
Training: Fold 4 - Total Loss: 2.4780, Cross Entropy: 1.222984, Accuracy: 0.4577, Precision: 0.3312, Recall: 0.4577, F1 Score: 0.3841, AUC: 0.5584, R2 Score: -0.013030, MAE: 1.8469, MSE: 5.4064
Validation: Fold 5 - Total Loss: 21.0233, Cross Entropy: 1.295346, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4471, R2 Score: -11.849830, MAE: 7.8631, MSE: 67.0551
Avg Latency (ms): 1.98, Avg Memory Before (MB): 49.66, Avg Memory After (MB): 49.66, Avg Max Memory (MB): 125.76

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4189, Cross Entropy: 1.194358, Accuracy: 0.4349, Precision: 0.3116, Recall: 0.4349, F1 Score: 0.3583, AUC: 0.5968, R2 Score: -0.018804, MAE: 1.8410, MSE: 5.2760
Training: Fold 2 - Total Loss: 2.3490, Cross Entropy: 1.202250, Accuracy: 0.4525, Precision: 0.3322, Recall: 0.4525, F1 Score: 0.3831, AUC: 0.5925, R2 Score: -0.001597, MAE: 1.7817, MSE: 5.0248
Training: Fold 3 - Total Loss: 2.3180, Cross Entropy: 1.222215, Accuracy: 0.4085, Precision: 0.2931, Recall: 0.4085, F1 Score: 0.3409, AUC: 0.5639, R2 Score: -0.000750, MAE: 1.7489, MSE: 4.8749
Training: Fold 4 - Total Loss: 2.4451, Cross Entropy: 1.200624, Accuracy: 0.4560, Precision: 0.3305, Recall: 0.4560, F1 Score: 0.3832, AUC: 0.5968, R2 Score: -0.015062, MAE: 1.8417, MSE: 5.3490

### ConvNeXt-Tiny

ConvNeXt is a **modernized version of ResNet**, integrating **design elements from vision transformers** while maintaining the efficiency of convolutional networks. The **ConvNeXt-Tiny** variant is a **lightweight** version optimized for efficiency while maintaining strong generalization capabilities.

- **Paper:** Liu, Z., Mao, H., Wu, C. Y., et al. (2022). *A ConvNet for the 2020s*. [CVPR](https://arxiv.org/abs/2201.03545).

In [ ]:
ARCH = "convnext-tiny"
main(ARCH)

====================================================================================================
Training Model: convnext-tiny
Initial Backbone Model Size: 114.41 MB
Modified Backbone Model Size: 111.72 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 13.0689, Cross Entropy: 1.444394, Accuracy: 0.2306, Precision: 0.3209, Recall: 0.2306, F1 Score: 0.2139, AUC: 0.4937, R2 Score: -6.821100, MAE: 5.3394, MSE: 40.1928
Training: Fold 2 - Total Loss: 3.3022, Cross Entropy: 1.279375, Accuracy: 0.3979, Precision: 0.2641, Recall: 0.3979, F1 Score: 0.2794, AUC: 0.4807, R2 Score: -0.680023, MAE: 2.2595, MSE: 8.0222
Training: Fold 3 - Total Loss: 3.0185, Cross Entropy: 1.276230, Accuracy: 0.3363, Precision: 0.2935, Recall: 0.3363, F1 Score: 0.2813, AUC: 0.4684, R2 Score: -0.497007, MAE: 2.1205, MSE: 7.0837
Training: Fold 4 - Total Loss: 2.7571, Cross Entropy: 1.252378, Accuracy: 0.4225, Precision: 0.2937, Recall: 0.4225, F1 Score: 0.2987, AUC: 0.4990, R2 Score: -0.235684, MAE: 2.0002, MSE: 6.2681
Validation: Fold 5 - Total Loss: 2.7014, Cross Entropy: 1.236463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5492, R2 Score: -0.135439, MAE: 1.9595, MSE: 6.1196
Avg Latency (ms): 13.37, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 2.6321, Cross Entropy: 1.239836, Accuracy: 0.3838, Precision: 0.2665, Recall: 0.3838, F1 Score: 0.3006, AUC: 0.5229, R2 Score: -0.173920, MAE: 1.9632, MSE: 5.8808
Training: Fold 2 - Total Loss: 2.4992, Cross Entropy: 1.255665, Accuracy: 0.3908, Precision: 0.2713, Recall: 0.3908, F1 Score: 0.2874, AUC: 0.4663, R2 Score: -0.117713, MAE: 1.8564, MSE: 5.4008
Training: Fold 3 - Total Loss: 2.3772, Cross Entropy: 1.259026, Accuracy: 0.3609, Precision: 0.2949, Recall: 0.3609, F1 Score: 0.2841, AUC: 0.4987, R2 Score: -0.059897, MAE: 1.7759, MSE: 4.9862
Training: Fold 4 - Total Loss: 2.5361, Cross Entropy: 1.264316, Accuracy: 0.4067, Precision: 0.2846, Recall: 0.4067, F1 Score: 0.3220, AUC: 0.4819, R2 Score: -0.043301, MAE: 1.8544, MSE: 5.5035
Validation: Fold 5 - Total Loss: 2.4516, Cross Entropy: 1.237405, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5795, R2 Score: -0.010031, MAE: 1.8177, MSE: 5.2848
Avg Latency (ms): 13.18, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4868, Cross Entropy: 1.251844, Accuracy: 0.3803, Precision: 0.2748, Recall: 0.3803, F1 Score: 0.3167, AUC: 0.4701, R2 Score: -0.045343, MAE: 1.8564, MSE: 5.3683
Training: Fold 2 - Total Loss: 2.4082, Cross Entropy: 1.250544, Accuracy: 0.4085, Precision: 0.2928, Recall: 0.4085, F1 Score: 0.3053, AUC: 0.4868, R2 Score: -0.016806, MAE: 1.7930, MSE: 5.1094
Training: Fold 3 - Total Loss: 2.4253, Cross Entropy: 1.264767, Accuracy: 0.3574, Precision: 0.2530, Recall: 0.3574, F1 Score: 0.2949, AUC: 0.4845, R2 Score: -0.073628, MAE: 1.7906, MSE: 5.1332
Training: Fold 4 - Total Loss: 2.6419, Cross Entropy: 1.260410, Accuracy: 0.3680, Precision: 0.2453, Recall: 0.3680, F1 Score: 0.2799, AUC: 0.4726, R2 Score: -0.112137, MAE: 1.9234, MSE: 5.8653
Validation: Fold 5 - Total Loss: 2.4773, Cross Entropy: 1.239865, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6001, R2 Score: -0.066953, MAE: 1.8603, MSE: 5.3648
Avg Latency (ms): 13.22, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 4/150
Training: Fold 1 - Total Loss: 2.5580, Cross Entropy: 1.256814, Accuracy: 0.3768, Precision: 0.2607, Recall: 0.3768, F1 Score: 0.2874, AUC: 0.5045, R2 Score: -0.081034, MAE: 1.8956, MSE: 5.5942
Training: Fold 2 - Total Loss: 2.4249, Cross Entropy: 1.243457, Accuracy: 0.3979, Precision: 0.2725, Recall: 0.3979, F1 Score: 0.2841, AUC: 0.4755, R2 Score: -0.072625, MAE: 1.8092, MSE: 5.1816
Training: Fold 3 - Total Loss: 2.4443, Cross Entropy: 1.265234, Accuracy: 0.3662, Precision: 0.2592, Recall: 0.3662, F1 Score: 0.2999, AUC: 0.4826, R2 Score: -0.068478, MAE: 1.8300, MSE: 5.1956
Training: Fold 4 - Total Loss: 2.5793, Cross Entropy: 1.247648, Accuracy: 0.3873, Precision: 0.2700, Recall: 0.3873, F1 Score: 0.3125, AUC: 0.5132, R2 Score: -0.083739, MAE: 1.9106, MSE: 5.6867
Validation: Fold 5 - Total Loss: 2.4481, Cross Entropy: 1.240553, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5898, R2 Score: -0.010025, MAE: 1.8139, MSE: 5.2658
Avg Latency (ms): 13.21, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 5/150
Training: Fold 1 - Total Loss: 2.5088, Cross Entropy: 1.257875, Accuracy: 0.4014, Precision: 0.2636, Recall: 0.4014, F1 Score: 0.2571, AUC: 0.4615, R2 Score: -0.045771, MAE: 1.8746, MSE: 5.4278
Training: Fold 2 - Total Loss: 2.4061, Cross Entropy: 1.243286, Accuracy: 0.3891, Precision: 0.2712, Recall: 0.3891, F1 Score: 0.3007, AUC: 0.5102, R2 Score: -0.038551, MAE: 1.7977, MSE: 5.1193
Training: Fold 3 - Total Loss: 2.3702, Cross Entropy: 1.259448, Accuracy: 0.3891, Precision: 0.2739, Recall: 0.3891, F1 Score: 0.3063, AUC: 0.4907, R2 Score: -0.012233, MAE: 1.7650, MSE: 4.9620
Training: Fold 4 - Total Loss: 2.5325, Cross Entropy: 1.250874, Accuracy: 0.4261, Precision: 0.3087, Recall: 0.4261, F1 Score: 0.2981, AUC: 0.5020, R2 Score: -0.055647, MAE: 1.8862, MSE: 5.5229
Validation: Fold 5 - Total Loss: 2.4794, Cross Entropy: 1.242924, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5986, R2 Score: -0.061479, MAE: 1.8614, MSE: 5.3646
Avg Latency (ms): 13.22, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 6/150
Training: Fold 1 - Total Loss: 2.5471, Cross Entropy: 1.253555, Accuracy: 0.3996, Precision: 0.2897, Recall: 0.3996, F1 Score: 0.3289, AUC: 0.4862, R2 Score: -0.070151, MAE: 1.8882, MSE: 5.5654
Training: Fold 2 - Total Loss: 2.4083, Cross Entropy: 1.247076, Accuracy: 0.4102, Precision: 0.2898, Recall: 0.4102, F1 Score: 0.3069, AUC: 0.4825, R2 Score: -0.028120, MAE: 1.7987, MSE: 5.1178
Training: Fold 3 - Total Loss: 2.3722, Cross Entropy: 1.262363, Accuracy: 0.3433, Precision: 0.3123, Recall: 0.3433, F1 Score: 0.2789, AUC: 0.4792, R2 Score: -0.035326, MAE: 1.7670, MSE: 4.9617
Training: Fold 4 - Total Loss: 2.4979, Cross Entropy: 1.251012, Accuracy: 0.4137, Precision: 0.2938, Recall: 0.4137, F1 Score: 0.2808, AUC: 0.5051, R2 Score: -0.020900, MAE: 1.8470, MSE: 5.4072
Validation: Fold 5 - Total Loss: 2.4775, Cross Entropy: 1.240305, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6037, R2 Score: -0.012624, MAE: 1.8184, MSE: 5.3644
Avg Latency (ms): 13.28, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4676, Cross Entropy: 1.242342, Accuracy: 0.3680, Precision: 0.2728, Recall: 0.3680, F1 Score: 0.3132, AUC: 0.5259, R2 Score: -0.008674, MAE: 1.8554, MSE: 5.3266
Training: Fold 2 - Total Loss: 2.4022, Cross Entropy: 1.246801, Accuracy: 0.3856, Precision: 0.2697, Recall: 0.3856, F1 Score: 0.3070, AUC: 0.5169, R2 Score: -0.024774, MAE: 1.7878, MSE: 5.0980
Training: Fold 3 - Total Loss: 2.4035, Cross Entropy: 1.273197, Accuracy: 0.3521, Precision: 0.2427, Recall: 0.3521, F1 Score: 0.2802, AUC: 0.4889, R2 Score: -0.023232, MAE: 1.7785, MSE: 5.0408
Training: Fold 4 - Total Loss: 2.5225, Cross Entropy: 1.258854, Accuracy: 0.4102, Precision: 0.2806, Recall: 0.4102, F1 Score: 0.2982, AUC: 0.4904, R2 Score: -0.037232, MAE: 1.8525, MSE: 5.4711
Validation: Fold 5 - Total Loss: 2.5858, Cross Entropy: 1.246975, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6013, R2 Score: -0.059428, MAE: 1.8883, MSE: 5.7098
Avg Latency (ms): 13.29, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4950, Cross Entropy: 1.255108, Accuracy: 0.3662, Precision: 0.2631, Recall: 0.3662, F1 Score: 0.3035, AUC: 0.5097, R2 Score: -0.039828, MAE: 1.8684, MSE: 5.3879
Training: Fold 2 - Total Loss: 2.4121, Cross Entropy: 1.251317, Accuracy: 0.4067, Precision: 0.2952, Recall: 0.4067, F1 Score: 0.3239, AUC: 0.4952, R2 Score: -0.032368, MAE: 1.8054, MSE: 5.1206
Training: Fold 3 - Total Loss: 2.3946, Cross Entropy: 1.265859, Accuracy: 0.3363, Precision: 0.2285, Recall: 0.3363, F1 Score: 0.2599, AUC: 0.4980, R2 Score: -0.037168, MAE: 1.7797, MSE: 5.0283
Training: Fold 4 - Total Loss: 2.5137, Cross Entropy: 1.273270, Accuracy: 0.3715, Precision: 0.2649, Recall: 0.3715, F1 Score: 0.3069, AUC: 0.4913, R2 Score: -0.033183, MAE: 1.8428, MSE: 5.4080
Validation: Fold 5 - Total Loss: 2.4881, Cross Entropy: 1.241578, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6070, R2 Score: -0.017333, MAE: 1.8231, MSE: 5.3966
Avg Latency (ms): 13.27, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 9/150
Training: Fold 1 - Total Loss: 2.5212, Cross Entropy: 1.258033, Accuracy: 0.3750, Precision: 0.2671, Recall: 0.3750, F1 Score: 0.3077, AUC: 0.4777, R2 Score: -0.052918, MAE: 1.8860, MSE: 5.4687
Training: Fold 2 - Total Loss: 2.4886, Cross Entropy: 1.245090, Accuracy: 0.3873, Precision: 0.2595, Recall: 0.3873, F1 Score: 0.2763, AUC: 0.4996, R2 Score: -0.087561, MAE: 1.8655, MSE: 5.3902
Training: Fold 3 - Total Loss: 2.3750, Cross Entropy: 1.258648, Accuracy: 0.3732, Precision: 0.2664, Recall: 0.3732, F1 Score: 0.3095, AUC: 0.4969, R2 Score: -0.035761, MAE: 1.7717, MSE: 4.9799
Training: Fold 4 - Total Loss: 2.5396, Cross Entropy: 1.251635, Accuracy: 0.3996, Precision: 0.2592, Recall: 0.3996, F1 Score: 0.2820, AUC: 0.4774, R2 Score: -0.068254, MAE: 1.8789, MSE: 5.5447
Validation: Fold 5 - Total Loss: 2.4633, Cross Entropy: 1.241212, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6039, R2 Score: -0.007409, MAE: 1.8132, MSE: 5.3148
Avg Latency (ms): 13.24, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 10/150
Training: Fold 1 - Total Loss: 2.5072, Cross Entropy: 1.253241, Accuracy: 0.3908, Precision: 0.2372, Recall: 0.3908, F1 Score: 0.2633, AUC: 0.4621, R2 Score: -0.040796, MAE: 1.8690, MSE: 5.4332
Training: Fold 2 - Total Loss: 2.4045, Cross Entropy: 1.247118, Accuracy: 0.3609, Precision: 0.2417, Recall: 0.3609, F1 Score: 0.2751, AUC: 0.4763, R2 Score: -0.023211, MAE: 1.8003, MSE: 5.1050
Training: Fold 3 - Total Loss: 2.4420, Cross Entropy: 1.273633, Accuracy: 0.3204, Precision: 0.2548, Recall: 0.3204, F1 Score: 0.2703, AUC: 0.4893, R2 Score: -0.067081, MAE: 1.8064, MSE: 5.1682
Training: Fold 4 - Total Loss: 2.5345, Cross Entropy: 1.257119, Accuracy: 0.3856, Precision: 0.2534, Recall: 0.3856, F1 Score: 0.2834, AUC: 0.4832, R2 Score: -0.026610, MAE: 1.8753, MSE: 5.5152
Validation: Fold 5 - Total Loss: 2.4371, Cross Entropy: 1.236207, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6168, R2 Score: -0.016446, MAE: 1.8264, MSE: 5.2393
Avg Latency (ms): 13.28, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 11/150
Training: Fold 1 - Total Loss: 2.5049, Cross Entropy: 1.239385, Accuracy: 0.3961, Precision: 0.2806, Recall: 0.3961, F1 Score: 0.3068, AUC: 0.5059, R2 Score: -0.056749, MAE: 1.8891, MSE: 5.4578
Training: Fold 2 - Total Loss: 2.5010, Cross Entropy: 1.259089, Accuracy: 0.3504, Precision: 0.2489, Recall: 0.3504, F1 Score: 0.2859, AUC: 0.4674, R2 Score: -0.068334, MAE: 1.8410, MSE: 5.3990
Training: Fold 3 - Total Loss: 2.4502, Cross Entropy: 1.269923, Accuracy: 0.3644, Precision: 0.2515, Recall: 0.3644, F1 Score: 0.2622, AUC: 0.4725, R2 Score: -0.073430, MAE: 1.8256, MSE: 5.2043
Training: Fold 4 - Total Loss: 2.5376, Cross Entropy: 1.248120, Accuracy: 0.4137, Precision: 0.2774, Recall: 0.4137, F1 Score: 0.2673, AUC: 0.5020, R2 Score: -0.032901, MAE: 1.8715, MSE: 5.5462
Validation: Fold 5 - Total Loss: 2.5313, Cross Entropy: 1.240001, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6022, R2 Score: -0.035547, MAE: 1.8505, MSE: 5.5443
Avg Latency (ms): 13.30, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 12/150
Training: Fold 1 - Total Loss: 2.5138, Cross Entropy: 1.255188, Accuracy: 0.3592, Precision: 0.2607, Recall: 0.3592, F1 Score: 0.3009, AUC: 0.4658, R2 Score: -0.050279, MAE: 1.8684, MSE: 5.4505
Training: Fold 2 - Total Loss: 2.4167, Cross Entropy: 1.256472, Accuracy: 0.3785, Precision: 0.2686, Recall: 0.3785, F1 Score: 0.3065, AUC: 0.4770, R2 Score: -0.036292, MAE: 1.7966, MSE: 5.1238
Training: Fold 3 - Total Loss: 2.4248, Cross Entropy: 1.282817, Accuracy: 0.3627, Precision: 0.3566, Recall: 0.3627, F1 Score: 0.2724, AUC: 0.4614, R2 Score: -0.065479, MAE: 1.7973, MSE: 5.0894
Training: Fold 4 - Total Loss: 2.5565, Cross Entropy: 1.247740, Accuracy: 0.4014, Precision: 0.2772, Recall: 0.4014, F1 Score: 0.3118, AUC: 0.5371, R2 Score: -0.058508, MAE: 1.8892, MSE: 5.6102
Validation: Fold 5 - Total Loss: 2.4568, Cross Entropy: 1.242889, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6166, R2 Score: -0.005981, MAE: 1.8116, MSE: 5.2891
Avg Latency (ms): 13.29, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4936, Cross Entropy: 1.246095, Accuracy: 0.3873, Precision: 0.2794, Recall: 0.3873, F1 Score: 0.3156, AUC: 0.5236, R2 Score: -0.022618, MAE: 1.8736, MSE: 5.4045
Training: Fold 2 - Total Loss: 2.4073, Cross Entropy: 1.249804, Accuracy: 0.3944, Precision: 0.2630, Recall: 0.3944, F1 Score: 0.2532, AUC: 0.5026, R2 Score: -0.024357, MAE: 1.7996, MSE: 5.1082
Training: Fold 3 - Total Loss: 2.3716, Cross Entropy: 1.263428, Accuracy: 0.3574, Precision: 0.4756, Recall: 0.3574, F1 Score: 0.3007, AUC: 0.4997, R2 Score: -0.020500, MAE: 1.7680, MSE: 4.9573
Training: Fold 4 - Total Loss: 2.5149, Cross Entropy: 1.246485, Accuracy: 0.4102, Precision: 0.2546, Recall: 0.4102, F1 Score: 0.2609, AUC: 0.4958, R2 Score: -0.033849, MAE: 1.8827, MSE: 5.4745
Validation: Fold 5 - Total Loss: 2.4475, Cross Entropy: 1.236321, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6197, R2 Score: -0.031494, MAE: 1.8398, MSE: 5.2736
Avg Latency (ms): 13.26, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 14/150
Training: Fold 1 - Total Loss: 2.4727, Cross Entropy: 1.240796, Accuracy: 0.4085, Precision: 0.2928, Recall: 0.4085, F1 Score: 0.3073, AUC: 0.4983, R2 Score: -0.021249, MAE: 1.8638, MSE: 5.3470
Training: Fold 2 - Total Loss: 2.4200, Cross Entropy: 1.241178, Accuracy: 0.3803, Precision: 0.2756, Recall: 0.3803, F1 Score: 0.3175, AUC: 0.5242, R2 Score: -0.043359, MAE: 1.8113, MSE: 5.1705
Training: Fold 3 - Total Loss: 2.3636, Cross Entropy: 1.263419, Accuracy: 0.3768, Precision: 0.2576, Recall: 0.3768, F1 Score: 0.2911, AUC: 0.4985, R2 Score: -0.022925, MAE: 1.7609, MSE: 4.9307
Training: Fold 4 - Total Loss: 2.5042, Cross Entropy: 1.245006, Accuracy: 0.3838, Precision: 0.2660, Recall: 0.3838, F1 Score: 0.3063, AUC: 0.5205, R2 Score: -0.047626, MAE: 1.8601, MSE: 5.4423
Validation: Fold 5 - Total Loss: 2.4568, Cross Entropy: 1.240134, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6245, R2 Score: -0.038803, MAE: 1.8462, MSE: 5.2958
Avg Latency (ms): 13.24, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 15/150
Training: Fold 1 - Total Loss: 2.5550, Cross Entropy: 1.258580, Accuracy: 0.3820, Precision: 0.2534, Recall: 0.3820, F1 Score: 0.2790, AUC: 0.4853, R2 Score: -0.071459, MAE: 1.9019, MSE: 5.5799
Training: Fold 2 - Total Loss: 2.4342, Cross Entropy: 1.247256, Accuracy: 0.3644, Precision: 0.2488, Recall: 0.3644, F1 Score: 0.2839, AUC: 0.5142, R2 Score: -0.046078, MAE: 1.8236, MSE: 5.2039
Training: Fold 3 - Total Loss: 2.3893, Cross Entropy: 1.271032, Accuracy: 0.3292, Precision: 0.2398, Recall: 0.3292, F1 Score: 0.2711, AUC: 0.4694, R2 Score: -0.033134, MAE: 1.7749, MSE: 4.9985
Training: Fold 4 - Total Loss: 2.4956, Cross Entropy: 1.244556, Accuracy: 0.4208, Precision: 0.2997, Recall: 0.4208, F1 Score: 0.2600, AUC: 0.5198, R2 Score: -0.040891, MAE: 1.8436, MSE: 5.4147
Validation: Fold 5 - Total Loss: 2.5081, Cross Entropy: 1.234879, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6138, R2 Score: -0.025967, MAE: 1.8370, MSE: 5.4789
Avg Latency (ms): 13.29, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 16/150
Training: Fold 1 - Total Loss: 2.4863, Cross Entropy: 1.256992, Accuracy: 0.3644, Precision: 0.2739, Recall: 0.3644, F1 Score: 0.3105, AUC: 0.4752, R2 Score: -0.035171, MAE: 1.8659, MSE: 5.3548
Training: Fold 2 - Total Loss: 2.4016, Cross Entropy: 1.242689, Accuracy: 0.3944, Precision: 0.2630, Recall: 0.3944, F1 Score: 0.2532, AUC: 0.4895, R2 Score: -0.030450, MAE: 1.7982, MSE: 5.1058
Training: Fold 3 - Total Loss: 2.4129, Cross Entropy: 1.265241, Accuracy: 0.3521, Precision: 0.2456, Recall: 0.3521, F1 Score: 0.2813, AUC: 0.4594, R2 Score: -0.061516, MAE: 1.8025, MSE: 5.0907
Training: Fold 4 - Total Loss: 2.5231, Cross Entropy: 1.248067, Accuracy: 0.4014, Precision: 0.2673, Recall: 0.4014, F1 Score: 0.2842, AUC: 0.4945, R2 Score: -0.038745, MAE: 1.8757, MSE: 5.4980
Validation: Fold 5 - Total Loss: 2.5701, Cross Entropy: 1.242740, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6188, R2 Score: -0.052480, MAE: 1.8784, MSE: 5.6672
Avg Latency (ms): 13.27, Avg Memory Before (MB): 460.85, Avg Memory After (MB): 460.85, Avg Max Memory (MB): 788.61

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4934, Cross Entropy: 1.244934, Accuracy: 0.3732, Precision: 0.2573, Recall: 0.3732, F1 Score: 0.2852, AUC: 0.4899, R2 Score: -0.040012, MAE: 1.8659, MSE: 5.4064
Training: Fold 2 - Total Loss: 2.3795, Cross Entropy: 1.239490, Accuracy: 0.3820, Precision: 0.2711, Recall: 0.3820, F1 Score: 0.2996, AUC: 0.4834, R2 Score: -0.017075, MAE: 1.7805, MSE: 5.0394
Training: Fold 3 - Total Loss: 2.3903, Cross Entropy: 1.260712, Accuracy: 0.3574, Precision: 0.2325, Recall: 0.3574, F1 Score: 0.2477, AUC: 0.5106, R2 Score: -0.033409, MAE: 1.7775, MSE: 5.0261
Training: Fold 4 - Total Loss: 2.5179, Cross Entropy: 1.255036, Accuracy: 0.3926, Precision: 0.2831, Recall: 0.3926, F1 Score: 0.3287, AUC: 0.4924, R2 Score: -0.031012, MAE: 1.8566, MSE: 5.4647
Validation: Fold 5 - Total Loss: 2.4670, Cross Entropy: 1.247194, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6176, R2 Score: -0.043090, MAE: 1.8507, MSE: 5.3131
Avg Latency (ms): 13.32, Avg Memory Before (MB): 460.26, Avg Memory After (MB): 460.26, Avg Max Memory (MB): 788.02

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4661, Cross Entropy: 1.256360, Accuracy: 0.3486, Precision: 0.2432, Recall: 0.3486, F1 Score: 0.2797, AUC: 0.4861, R2 Score: -0.036000, MAE: 1.8453, MSE: 5.2888
Training: Fold 2 - Total Loss: 2.4090, Cross Entropy: 1.251434, Accuracy: 0.3803, Precision: 0.2454, Recall: 0.3803, F1 Score: 0.2616, AUC: 0.4732, R2 Score: -0.045417, MAE: 1.8014, MSE: 5.1100
Training: Fold 3 - Total Loss: 2.3663, Cross Entropy: 1.257401, Accuracy: 0.3574, Precision: 0.2561, Recall: 0.3574, F1 Score: 0.2979, AUC: 0.5021, R2 Score: -0.023477, MAE: 1.7600, MSE: 4.9536
Training: Fold 4 - Total Loss: 2.5213, Cross Entropy: 1.247483, Accuracy: 0.4173, Precision: 0.2936, Recall: 0.4173, F1 Score: 0.2608, AUC: 0.5045, R2 Score: -0.026232, MAE: 1.8749, MSE: 5.4937
Validation: Fold 5 - Total Loss: 2.4408, Cross Entropy: 1.237634, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6263, R2 Score: -0.002802, MAE: 1.8137, MSE: 5.2481

### GhostNetV2

GhostNet introduces **"ghost modules"**, which create additional feature maps using cheap operations instead of standard convolutions. This results in **significant reductions in computation and memory usage**, making GhostNet **highly efficient for mobile vision applications**.

- **Paper:** Han, K., Wang, Y., Tian, Q., et al. (2020). *GhostNet: More Features from Cheap Operations*. [CVPR](https://arxiv.org/abs/1911.11907).

In [ ]:
ARCH = "ghostnetv2"
main(ARCH)

====================================================================================================
Training Model: ghostnetv2
Initial Backbone Model Size: 25.11 MB
Modified Backbone Model Size: 20.64 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 26.7549, Cross Entropy: 1.354562, Accuracy: 0.3433, Precision: 0.3548, Recall: 0.3433, F1 Score: 0.2806, AUC: 0.4983, R2 Score: -15.470448, MAE: 8.8830, MSE: 86.0224
Training: Fold 2 - Total Loss: 6.5150, Cross Entropy: 1.254313, Accuracy: 0.3486, Precision: 0.2864, Recall: 0.3486, F1 Score: 0.2503, AUC: 0.5453, R2 Score: -2.732768, MAE: 3.5733, MSE: 18.7900
Training: Fold 3 - Total Loss: 3.0013, Cross Entropy: 1.281157, Accuracy: 0.3521, Precision: 0.1974, Recall: 0.3521, F1 Score: 0.2199, AUC: 0.5040, R2 Score: -0.411048, MAE: 2.0945, MSE: 7.0149
Training: Fold 4 - Total Loss: 2.6731, Cross Entropy: 1.255884, Accuracy: 0.4120, Precision: 0.3968, Recall: 0.4120, F1 Score: 0.3521, AUC: 0.4791, R2 Score: -0.114446, MAE: 1.9724, MSE: 5.9798
Validation: Fold 5 - Total Loss: 2.5762, Cross Entropy: 1.235958, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5404, R2 Score: -0.049100, MAE: 1.8847, MSE: 5.7033
Avg Latency (ms): 9.48, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.22
Best model saved with Accuracy: 0.3873

Epoch 2/150
Training: Fold 1 - Total Loss: 2.5327, Cross Entropy: 1.245377, Accuracy: 0.4085, Precision: 0.3029, Recall: 0.4085, F1 Score: 0.2697, AUC: 0.5066, R2 Score: -0.050494, MAE: 1.8868, MSE: 5.5365
Training: Fold 2 - Total Loss: 2.4490, Cross Entropy: 1.248710, Accuracy: 0.3345, Precision: 0.2393, Recall: 0.3345, F1 Score: 0.2779, AUC: 0.4735, R2 Score: -0.044997, MAE: 1.8358, MSE: 5.2497
Training: Fold 3 - Total Loss: 2.4097, Cross Entropy: 1.256241, Accuracy: 0.3803, Precision: 0.2641, Recall: 0.3803, F1 Score: 0.2883, AUC: 0.5060, R2 Score: -0.036041, MAE: 1.7952, MSE: 5.1012
Training: Fold 4 - Total Loss: 2.5155, Cross Entropy: 1.248177, Accuracy: 0.4155, Precision: 0.2891, Recall: 0.4155, F1 Score: 0.2902, AUC: 0.4939, R2 Score: -0.035947, MAE: 1.8643, MSE: 5.4724
Validation: Fold 5 - Total Loss: 2.4290, Cross Entropy: 1.228232, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5923, R2 Score: 0.023104, MAE: 1.8035, MSE: 5.2307
Avg Latency (ms): 5.82, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 3/150
Training: Fold 1 - Total Loss: 2.4922, Cross Entropy: 1.237292, Accuracy: 0.3944, Precision: 0.2791, Recall: 0.3944, F1 Score: 0.3138, AUC: 0.5043, R2 Score: -0.037219, MAE: 1.8731, MSE: 5.4203
Training: Fold 2 - Total Loss: 2.4016, Cross Entropy: 1.239019, Accuracy: 0.3680, Precision: 0.2544, Recall: 0.3680, F1 Score: 0.2844, AUC: 0.4985, R2 Score: -0.003577, MAE: 1.8022, MSE: 5.1144
Training: Fold 3 - Total Loss: 2.3956, Cross Entropy: 1.257504, Accuracy: 0.3574, Precision: 0.2454, Recall: 0.3574, F1 Score: 0.2848, AUC: 0.5083, R2 Score: -0.028789, MAE: 1.7894, MSE: 5.0511
Training: Fold 4 - Total Loss: 2.5221, Cross Entropy: 1.244200, Accuracy: 0.4173, Precision: 0.2792, Recall: 0.4173, F1 Score: 0.2900, AUC: 0.5111, R2 Score: -0.042397, MAE: 1.8685, MSE: 5.5040
Validation: Fold 5 - Total Loss: 2.4666, Cross Entropy: 1.224998, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5906, R2 Score: -0.010248, MAE: 1.8219, MSE: 5.3638
Avg Latency (ms): 5.81, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 4/150
Training: Fold 1 - Total Loss: 2.4942, Cross Entropy: 1.249084, Accuracy: 0.4137, Precision: 0.3108, Recall: 0.4137, F1 Score: 0.2815, AUC: 0.5008, R2 Score: -0.026253, MAE: 1.8641, MSE: 5.3994
Training: Fold 2 - Total Loss: 2.4179, Cross Entropy: 1.242250, Accuracy: 0.3838, Precision: 0.2830, Recall: 0.3838, F1 Score: 0.3254, AUC: 0.4957, R2 Score: -0.046609, MAE: 1.8162, MSE: 5.1611
Training: Fold 3 - Total Loss: 2.4087, Cross Entropy: 1.253261, Accuracy: 0.4049, Precision: 0.3543, Recall: 0.4049, F1 Score: 0.3173, AUC: 0.5124, R2 Score: -0.032254, MAE: 1.7992, MSE: 5.1046
Training: Fold 4 - Total Loss: 2.5047, Cross Entropy: 1.238377, Accuracy: 0.4261, Precision: 0.2974, Recall: 0.4261, F1 Score: 0.3061, AUC: 0.5261, R2 Score: -0.039009, MAE: 1.8646, MSE: 5.4596
Validation: Fold 5 - Total Loss: 2.4195, Cross Entropy: 1.224252, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5921, R2 Score: 0.005131, MAE: 1.8113, MSE: 5.2083
Avg Latency (ms): 5.81, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 5/150
Training: Fold 1 - Total Loss: 2.5016, Cross Entropy: 1.233315, Accuracy: 0.4173, Precision: 0.3003, Recall: 0.4173, F1 Score: 0.3336, AUC: 0.5304, R2 Score: -0.037267, MAE: 1.8756, MSE: 5.4610
Training: Fold 2 - Total Loss: 2.4112, Cross Entropy: 1.246873, Accuracy: 0.3961, Precision: 0.2606, Recall: 0.3961, F1 Score: 0.2685, AUC: 0.5071, R2 Score: -0.024841, MAE: 1.8093, MSE: 5.1280
Training: Fold 3 - Total Loss: 2.3965, Cross Entropy: 1.253606, Accuracy: 0.3732, Precision: 0.2725, Recall: 0.3732, F1 Score: 0.3091, AUC: 0.5095, R2 Score: -0.054958, MAE: 1.7851, MSE: 5.0633
Training: Fold 4 - Total Loss: 2.5271, Cross Entropy: 1.257589, Accuracy: 0.3996, Precision: 0.2532, Recall: 0.3996, F1 Score: 0.2744, AUC: 0.4888, R2 Score: -0.042229, MAE: 1.8651, MSE: 5.4891
Validation: Fold 5 - Total Loss: 2.4536, Cross Entropy: 1.217168, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5699, R2 Score: -0.002995, MAE: 1.8160, MSE: 5.3387
Avg Latency (ms): 6.40, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4844, Cross Entropy: 1.233231, Accuracy: 0.4225, Precision: 0.3090, Recall: 0.4225, F1 Score: 0.3555, AUC: 0.5200, R2 Score: -0.003294, MAE: 1.8639, MSE: 5.4037
Training: Fold 2 - Total Loss: 2.3991, Cross Entropy: 1.229726, Accuracy: 0.3944, Precision: 0.2711, Recall: 0.3944, F1 Score: 0.2898, AUC: 0.5247, R2 Score: -0.039110, MAE: 1.8073, MSE: 5.1277
Training: Fold 3 - Total Loss: 2.3813, Cross Entropy: 1.245150, Accuracy: 0.3768, Precision: 0.2605, Recall: 0.3768, F1 Score: 0.2984, AUC: 0.5116, R2 Score: -0.065453, MAE: 1.7870, MSE: 5.0324
Training: Fold 4 - Total Loss: 2.5184, Cross Entropy: 1.231514, Accuracy: 0.4155, Precision: 0.2906, Recall: 0.4155, F1 Score: 0.3259, AUC: 0.5450, R2 Score: -0.027400, MAE: 1.8758, MSE: 5.5210
Validation: Fold 5 - Total Loss: 2.4700, Cross Entropy: 1.206627, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6217, R2 Score: -0.019049, MAE: 1.8280, MSE: 5.4177
Avg Latency (ms): 5.90, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4931, Cross Entropy: 1.225855, Accuracy: 0.4085, Precision: 0.2863, Recall: 0.4085, F1 Score: 0.3090, AUC: 0.5581, R2 Score: -0.040687, MAE: 1.8660, MSE: 5.4499
Training: Fold 2 - Total Loss: 2.4407, Cross Entropy: 1.237300, Accuracy: 0.3891, Precision: 0.2763, Recall: 0.3891, F1 Score: 0.3153, AUC: 0.5173, R2 Score: -0.032114, MAE: 1.8232, MSE: 5.2486
Training: Fold 3 - Total Loss: 2.3758, Cross Entropy: 1.243359, Accuracy: 0.3908, Precision: 0.2746, Recall: 0.3908, F1 Score: 0.3178, AUC: 0.5324, R2 Score: -0.038143, MAE: 1.7805, MSE: 5.0183
Training: Fold 4 - Total Loss: 2.5337, Cross Entropy: 1.243878, Accuracy: 0.3961, Precision: 0.4615, Recall: 0.3961, F1 Score: 0.2942, AUC: 0.5426, R2 Score: -0.046568, MAE: 1.8675, MSE: 5.5431
Validation: Fold 5 - Total Loss: 2.4622, Cross Entropy: 1.201891, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6062, R2 Score: -0.008448, MAE: 1.8240, MSE: 5.4031
Avg Latency (ms): 5.82, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4729, Cross Entropy: 1.226658, Accuracy: 0.4032, Precision: 0.2923, Recall: 0.4032, F1 Score: 0.3378, AUC: 0.5532, R2 Score: -0.028647, MAE: 1.8630, MSE: 5.3807
Training: Fold 2 - Total Loss: 2.3888, Cross Entropy: 1.219425, Accuracy: 0.3961, Precision: 0.2736, Recall: 0.3961, F1 Score: 0.3097, AUC: 0.5628, R2 Score: -0.018476, MAE: 1.8000, MSE: 5.1174
Training: Fold 3 - Total Loss: 2.4015, Cross Entropy: 1.244007, Accuracy: 0.3944, Precision: 0.2807, Recall: 0.3944, F1 Score: 0.3261, AUC: 0.5331, R2 Score: -0.067008, MAE: 1.7926, MSE: 5.1025
Training: Fold 4 - Total Loss: 2.5150, Cross Entropy: 1.233248, Accuracy: 0.4102, Precision: 0.2869, Recall: 0.4102, F1 Score: 0.3335, AUC: 0.5464, R2 Score: -0.046003, MAE: 1.8710, MSE: 5.5059
Validation: Fold 5 - Total Loss: 2.4570, Cross Entropy: 1.196308, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.6120, R2 Score: -0.014942, MAE: 1.8261, MSE: 5.3988
Avg Latency (ms): 5.79, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 9/150
Training: Fold 1 - Total Loss: 2.5307, Cross Entropy: 1.224190, Accuracy: 0.4208, Precision: 0.3775, Recall: 0.4208, F1 Score: 0.3376, AUC: 0.5586, R2 Score: -0.043617, MAE: 1.8948, MSE: 5.5792
Training: Fold 2 - Total Loss: 2.4255, Cross Entropy: 1.221141, Accuracy: 0.4032, Precision: 0.2900, Recall: 0.4032, F1 Score: 0.3348, AUC: 0.5431, R2 Score: -0.049951, MAE: 1.8308, MSE: 5.2356
Training: Fold 3 - Total Loss: 2.3725, Cross Entropy: 1.241886, Accuracy: 0.3750, Precision: 0.2647, Recall: 0.3750, F1 Score: 0.3082, AUC: 0.5372, R2 Score: -0.026524, MAE: 1.7809, MSE: 5.0107
Training: Fold 4 - Total Loss: 2.5111, Cross Entropy: 1.222056, Accuracy: 0.4261, Precision: 0.3016, Recall: 0.4261, F1 Score: 0.3349, AUC: 0.5699, R2 Score: -0.041195, MAE: 1.8756, MSE: 5.5189
Validation: Fold 5 - Total Loss: 2.4061, Cross Entropy: 1.180063, Accuracy: 0.4366, Precision: 0.3007, Recall: 0.4366, F1 Score: 0.3495, AUC: 0.6140, R2 Score: 0.003265, MAE: 1.8092, MSE: 5.2669
Avg Latency (ms): 5.83, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52
Best model saved with Accuracy: 0.4366

Epoch 10/150
Training: Fold 1 - Total Loss: 2.4700, Cross Entropy: 1.224054, Accuracy: 0.4173, Precision: 0.3053, Recall: 0.4173, F1 Score: 0.3522, AUC: 0.5472, R2 Score: -0.020781, MAE: 1.8648, MSE: 5.3773
Training: Fold 2 - Total Loss: 2.4146, Cross Entropy: 1.220803, Accuracy: 0.4032, Precision: 0.2778, Recall: 0.4032, F1 Score: 0.3161, AUC: 0.5566, R2 Score: -0.064302, MAE: 1.8192, MSE: 5.2000
Training: Fold 3 - Total Loss: 2.3831, Cross Entropy: 1.225204, Accuracy: 0.4261, Precision: 0.3256, Recall: 0.4261, F1 Score: 0.3568, AUC: 0.5811, R2 Score: -0.024141, MAE: 1.8029, MSE: 5.0848
Training: Fold 4 - Total Loss: 2.5130, Cross Entropy: 1.210580, Accuracy: 0.4208, Precision: 0.2897, Recall: 0.4208, F1 Score: 0.3204, AUC: 0.5929, R2 Score: -0.047372, MAE: 1.8824, MSE: 5.5521
Validation: Fold 5 - Total Loss: 2.3793, Cross Entropy: 1.168315, Accuracy: 0.4859, Precision: 0.3422, Recall: 0.4859, F1 Score: 0.4011, AUC: 0.6409, R2 Score: 0.037071, MAE: 1.8060, MSE: 5.2050
Avg Latency (ms): 5.85, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52
Best model saved with Accuracy: 0.4859

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4648, Cross Entropy: 1.192252, Accuracy: 0.4525, Precision: 0.3338, Recall: 0.4525, F1 Score: 0.3842, AUC: 0.6067, R2 Score: -0.051381, MAE: 1.8722, MSE: 5.4341
Training: Fold 2 - Total Loss: 2.3734, Cross Entropy: 1.201733, Accuracy: 0.4384, Precision: 0.3172, Recall: 0.4384, F1 Score: 0.3652, AUC: 0.5671, R2 Score: -0.025922, MAE: 1.7991, MSE: 5.1072
Training: Fold 3 - Total Loss: 2.3851, Cross Entropy: 1.221984, Accuracy: 0.4278, Precision: 0.4141, Recall: 0.4278, F1 Score: 0.3582, AUC: 0.5594, R2 Score: -0.041780, MAE: 1.7971, MSE: 5.0989
Training: Fold 4 - Total Loss: 2.4846, Cross Entropy: 1.197890, Accuracy: 0.4542, Precision: 0.3217, Recall: 0.4542, F1 Score: 0.3689, AUC: 0.6117, R2 Score: -0.036282, MAE: 1.8644, MSE: 5.4868
Validation: Fold 5 - Total Loss: 2.3978, Cross Entropy: 1.175488, Accuracy: 0.4014, Precision: 0.2694, Recall: 0.4014, F1 Score: 0.2658, AUC: 0.6429, R2 Score: 0.025343, MAE: 1.8159, MSE: 5.2498
Avg Latency (ms): 6.14, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 12/150
Training: Fold 1 - Total Loss: 2.4676, Cross Entropy: 1.219011, Accuracy: 0.4489, Precision: 0.3301, Recall: 0.4489, F1 Score: 0.3804, AUC: 0.5633, R2 Score: -0.049281, MAE: 1.8679, MSE: 5.3810
Training: Fold 2 - Total Loss: 2.3851, Cross Entropy: 1.190650, Accuracy: 0.4349, Precision: 0.3169, Recall: 0.4349, F1 Score: 0.3659, AUC: 0.5916, R2 Score: -0.043541, MAE: 1.8130, MSE: 5.1723
Training: Fold 3 - Total Loss: 2.3513, Cross Entropy: 1.204945, Accuracy: 0.4155, Precision: 0.3463, Recall: 0.4155, F1 Score: 0.3435, AUC: 0.5919, R2 Score: -0.034050, MAE: 1.7753, MSE: 5.0260
Training: Fold 4 - Total Loss: 2.4971, Cross Entropy: 1.193714, Accuracy: 0.4701, Precision: 0.4374, Recall: 0.4701, F1 Score: 0.4064, AUC: 0.5985, R2 Score: -0.057709, MAE: 1.8796, MSE: 5.5384
Validation: Fold 5 - Total Loss: 2.4053, Cross Entropy: 1.140715, Accuracy: 0.4718, Precision: 0.3243, Recall: 0.4718, F1 Score: 0.3832, AUC: 0.6515, R2 Score: 0.019311, MAE: 1.8234, MSE: 5.3561
Avg Latency (ms): 6.16, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4505, Cross Entropy: 1.187241, Accuracy: 0.4507, Precision: 0.3277, Recall: 0.4507, F1 Score: 0.3746, AUC: 0.6112, R2 Score: -0.026875, MAE: 1.8645, MSE: 5.3982
Training: Fold 2 - Total Loss: 2.3799, Cross Entropy: 1.192588, Accuracy: 0.4489, Precision: 0.3681, Recall: 0.4489, F1 Score: 0.3807, AUC: 0.5924, R2 Score: -0.040779, MAE: 1.8088, MSE: 5.1502
Training: Fold 3 - Total Loss: 2.3779, Cross Entropy: 1.197887, Accuracy: 0.4507, Precision: 0.3395, Recall: 0.4507, F1 Score: 0.3778, AUC: 0.5943, R2 Score: -0.074469, MAE: 1.8045, MSE: 5.1313
Training: Fold 4 - Total Loss: 2.4773, Cross Entropy: 1.195258, Accuracy: 0.4525, Precision: 0.3743, Recall: 0.4525, F1 Score: 0.3791, AUC: 0.5989, R2 Score: -0.039723, MAE: 1.8652, MSE: 5.4688
Validation: Fold 5 - Total Loss: 2.3792, Cross Entropy: 1.129660, Accuracy: 0.4437, Precision: 0.3086, Recall: 0.4437, F1 Score: 0.3640, AUC: 0.6312, R2 Score: 0.006346, MAE: 1.8112, MSE: 5.2947
Avg Latency (ms): 6.15, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 14/150
Training: Fold 1 - Total Loss: 2.4411, Cross Entropy: 1.176313, Accuracy: 0.4771, Precision: 0.3618, Recall: 0.4771, F1 Score: 0.4092, AUC: 0.6107, R2 Score: -0.017223, MAE: 1.8625, MSE: 5.3922
Training: Fold 2 - Total Loss: 2.3557, Cross Entropy: 1.180710, Accuracy: 0.4296, Precision: 0.3129, Recall: 0.4296, F1 Score: 0.3619, AUC: 0.6085, R2 Score: -0.051466, MAE: 1.8017, MSE: 5.0973
Training: Fold 3 - Total Loss: 2.3623, Cross Entropy: 1.226136, Accuracy: 0.4349, Precision: 0.4261, Recall: 0.4349, F1 Score: 0.3662, AUC: 0.5817, R2 Score: -0.006833, MAE: 1.7756, MSE: 5.0134
Training: Fold 4 - Total Loss: 2.5441, Cross Entropy: 1.189043, Accuracy: 0.4225, Precision: 0.3528, Recall: 0.4225, F1 Score: 0.3649, AUC: 0.6082, R2 Score: -0.069602, MAE: 1.9167, MSE: 5.7059
Validation: Fold 5 - Total Loss: 2.3932, Cross Entropy: 1.086563, Accuracy: 0.4718, Precision: 0.3265, Recall: 0.4718, F1 Score: 0.3850, AUC: 0.6635, R2 Score: -0.021761, MAE: 1.8311, MSE: 5.4421
Avg Latency (ms): 6.15, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 15/150
Training: Fold 1 - Total Loss: 2.4397, Cross Entropy: 1.158167, Accuracy: 0.4894, Precision: 0.3664, Recall: 0.4894, F1 Score: 0.4176, AUC: 0.6417, R2 Score: -0.036771, MAE: 1.8708, MSE: 5.4300
Training: Fold 2 - Total Loss: 2.3556, Cross Entropy: 1.188153, Accuracy: 0.4331, Precision: 0.5236, Recall: 0.4331, F1 Score: 0.3725, AUC: 0.5779, R2 Score: -0.028834, MAE: 1.7924, MSE: 5.0798
Training: Fold 3 - Total Loss: 2.3335, Cross Entropy: 1.189469, Accuracy: 0.4736, Precision: 0.3620, Recall: 0.4736, F1 Score: 0.3991, AUC: 0.6104, R2 Score: -0.046759, MAE: 1.7759, MSE: 5.0030
Training: Fold 4 - Total Loss: 2.4921, Cross Entropy: 1.166377, Accuracy: 0.4665, Precision: 0.5455, Recall: 0.4665, F1 Score: 0.3983, AUC: 0.6180, R2 Score: -0.035208, MAE: 1.8741, MSE: 5.5854
Validation: Fold 5 - Total Loss: 2.3398, Cross Entropy: 1.056155, Accuracy: 0.5000, Precision: 0.3676, Recall: 0.5000, F1 Score: 0.4181, AUC: 0.6687, R2 Score: -0.038188, MAE: 1.8479, MSE: 5.3351
Avg Latency (ms): 6.47, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52
Best model saved with Accuracy: 0.5000

Epoch 16/150
Training: Fold 1 - Total Loss: 2.4431, Cross Entropy: 1.167883, Accuracy: 0.4542, Precision: 0.3784, Recall: 0.4542, F1 Score: 0.3835, AUC: 0.6324, R2 Score: -0.059511, MAE: 1.8597, MSE: 5.4187
Training: Fold 2 - Total Loss: 2.3619, Cross Entropy: 1.172111, Accuracy: 0.4630, Precision: 0.3901, Recall: 0.4630, F1 Score: 0.3930, AUC: 0.6051, R2 Score: -0.020651, MAE: 1.8024, MSE: 5.1381
Training: Fold 3 - Total Loss: 2.3375, Cross Entropy: 1.176596, Accuracy: 0.4472, Precision: 0.4268, Recall: 0.4472, F1 Score: 0.3731, AUC: 0.6217, R2 Score: -0.034012, MAE: 1.7793, MSE: 5.0463
Training: Fold 4 - Total Loss: 2.4421, Cross Entropy: 1.150758, Accuracy: 0.4789, Precision: 0.3763, Recall: 0.4789, F1 Score: 0.4116, AUC: 0.6465, R2 Score: -0.039370, MAE: 1.8620, MSE: 5.4551
Validation: Fold 5 - Total Loss: 2.3017, Cross Entropy: 1.052292, Accuracy: 0.4789, Precision: 0.3329, Recall: 0.4789, F1 Score: 0.3927, AUC: 0.6653, R2 Score: 0.028859, MAE: 1.8171, MSE: 5.2170
Avg Latency (ms): 6.14, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4248, Cross Entropy: 1.173044, Accuracy: 0.4613, Precision: 0.4083, Recall: 0.4613, F1 Score: 0.3990, AUC: 0.6192, R2 Score: -0.022861, MAE: 1.8603, MSE: 5.3456
Training: Fold 2 - Total Loss: 2.3501, Cross Entropy: 1.132354, Accuracy: 0.4771, Precision: 0.4710, Recall: 0.4771, F1 Score: 0.4118, AUC: 0.6300, R2 Score: -0.010370, MAE: 1.8188, MSE: 5.1916
Training: Fold 3 - Total Loss: 2.3210, Cross Entropy: 1.154222, Accuracy: 0.4718, Precision: 0.4902, Recall: 0.4718, F1 Score: 0.3996, AUC: 0.6413, R2 Score: -0.001946, MAE: 1.7833, MSE: 5.0434
Training: Fold 4 - Total Loss: 2.4541, Cross Entropy: 1.139608, Accuracy: 0.4454, Precision: 0.3358, Recall: 0.4454, F1 Score: 0.3811, AUC: 0.6589, R2 Score: -0.018899, MAE: 1.8783, MSE: 5.5212
Validation: Fold 5 - Total Loss: 2.4019, Cross Entropy: 1.068106, Accuracy: 0.4789, Precision: 0.3344, Recall: 0.4789, F1 Score: 0.3938, AUC: 0.6720, R2 Score: -0.017706, MAE: 1.8449, MSE: 5.5140
Avg Latency (ms): 6.16, Avg Memory Before (MB): 110.17, Avg Memory After (MB): 110.17, Avg Max Memory (MB): 284.52

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4290, Cross Entropy: 1.142991, Accuracy: 0.4754, Precision: 0.3649, Recall: 0.4754, F1 Score: 0.4091, AUC: 0.6457, R2 Score: -0.043808, MAE: 1.8731, MSE: 5.4297
Training: Fold 2 - Total Loss: 2.3277, Cross Entropy: 1.144115, Accuracy: 0.4683, Precision: 0.5488, Recall: 0.4683, F1 Score: 0.3996, AUC: 0.6447, R2 Score: -0.029642, MAE: 1.8000, MSE: 5.0895
Training: Fold 3 - Total Loss: 2.3662, Cross Entropy: 1.156412, Accuracy: 0.4912, Precision: 0.3936, Recall: 0.4912, F1 Score: 0.4146, AUC: 0.6320, R2 Score: -0.058727, MAE: 1.8065, MSE: 5.1892
Training: Fold 4 - Total Loss: 2.4592, Cross Entropy: 1.139192, Accuracy: 0.4877, Precision: 0.4338, Recall: 0.4877, F1 Score: 0.4202, AUC: 0.6633, R2 Score: -0.044949, MAE: 1.8735, MSE: 5.5393

### TinyNet-A

TinyNet is designed for **extreme efficiency**, balancing depth, width, and resolution to **optimize model size without sacrificing accuracy**.

- **Paper:** Han, K., Wang, Y., Zhang, Q., et al. (2020). *Model Rubik’s Cube: Twisting Resolution, Depth and Width for TinyNets*. [NeurIPS](https://arxiv.org/abs/2109.15027).

In [ ]:
ARCH = "tinynet-a"
main(ARCH)

====================================================================================================
Training Model: tinynet-a
Initial Backbone Model Size: 25.08 MB
Modified Backbone Model Size: 20.62 MB


Epoch 1/150
Training: Fold 1 - Total Loss: 31.7151, Cross Entropy: 1.387451, Accuracy: 0.2553, Precision: 0.2998, Recall: 0.2553, F1 Score: 0.2014, AUC: 0.4901, R2 Score: -18.529001, MAE: 9.8346, MSE: 102.4798
Training: Fold 2 - Total Loss: 25.4817, Cross Entropy: 1.324259, Accuracy: 0.3926, Precision: 0.3320, Recall: 0.3926, F1 Score: 0.3157, AUC: 0.5203, R2 Score: -15.363057, MAE: 8.6639, MSE: 81.8492
Training: Fold 3 - Total Loss: 18.2706, Cross Entropy: 1.291424, Accuracy: 0.3961, Precision: 0.2907, Recall: 0.3961, F1 Score: 0.3297, AUC: 0.5501, R2 Score: -10.802015, MAE: 7.1993, MSE: 57.8888
Training: Fold 4 - Total Loss: 12.1253, Cross Entropy: 1.277189, Accuracy: 0.4137, Precision: 0.3065, Recall: 0.4137, F1 Score: 0.3506, AUC: 0.5361, R2 Score: -5.966382, MAE: 5.5952, MSE: 37.4376
Validation: Fold 5 - Total Loss: 7.1703, Cross Entropy: 1.205830, Accuracy: 0.4789, Precision: 0.3417, Recall: 0.4789, F1 Score: 0.3934, AUC: 0.5893, R2 Score: -2.852503, MAE: 3.9906, MSE: 21.0874
Avg Latency (ms): 5.30, Avg Memory Before (MB): 111.96, Avg Memory After (MB): 111.96, Avg Max Memory (MB): 440.51
Best model saved with Accuracy: 0.4789

Epoch 2/150
Training: Fold 1 - Total Loss: 6.8581, Cross Entropy: 1.250222, Accuracy: 0.4173, Precision: 0.3098, Recall: 0.4173, F1 Score: 0.3553, AUC: 0.5329, R2 Score: -2.785022, MAE: 3.9004, MSE: 19.9431
Training: Fold 2 - Total Loss: 3.9501, Cross Entropy: 1.237578, Accuracy: 0.4120, Precision: 0.3012, Recall: 0.4120, F1 Score: 0.3479, AUC: 0.5343, R2 Score: -1.110048, MAE: 2.6782, MSE: 10.2793
Training: Fold 3 - Total Loss: 2.8853, Cross Entropy: 1.245601, Accuracy: 0.3996, Precision: 0.2811, Recall: 0.3996, F1 Score: 0.3256, AUC: 0.5466, R2 Score: -0.340072, MAE: 2.0976, MSE: 6.7111
Training: Fold 4 - Total Loss: 2.7159, Cross Entropy: 1.225628, Accuracy: 0.4331, Precision: 0.3093, Recall: 0.4331, F1 Score: 0.3588, AUC: 0.5598, R2 Score: -0.170661, MAE: 1.9909, MSE: 6.1934
Validation: Fold 5 - Total Loss: 2.5406, Cross Entropy: 1.196261, Accuracy: 0.4718, Precision: 0.3315, Recall: 0.4718, F1 Score: 0.3697, AUC: 0.6047, R2 Score: -0.008313, MAE: 1.8857, MSE: 5.6775
Avg Latency (ms): 5.31, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 3/150
Training: Fold 1 - Total Loss: 2.7036, Cross Entropy: 1.229082, Accuracy: 0.4208, Precision: 0.3039, Recall: 0.4208, F1 Score: 0.3352, AUC: 0.5437, R2 Score: -0.194543, MAE: 1.9969, MSE: 6.1442
Training: Fold 2 - Total Loss: 2.6647, Cross Entropy: 1.227881, Accuracy: 0.4278, Precision: 0.3094, Recall: 0.4278, F1 Score: 0.3546, AUC: 0.5306, R2 Score: -0.226977, MAE: 1.9530, MSE: 6.0172
Training: Fold 3 - Total Loss: 2.4485, Cross Entropy: 1.239197, Accuracy: 0.3996, Precision: 0.2785, Recall: 0.3996, F1 Score: 0.3169, AUC: 0.5537, R2 Score: -0.081598, MAE: 1.8312, MSE: 5.2700
Training: Fold 4 - Total Loss: 2.6520, Cross Entropy: 1.235292, Accuracy: 0.4278, Precision: 0.2995, Recall: 0.4278, F1 Score: 0.3335, AUC: 0.5300, R2 Score: -0.073858, MAE: 1.9434, MSE: 5.9578
Validation: Fold 5 - Total Loss: 2.4507, Cross Entropy: 1.214483, Accuracy: 0.3944, Precision: 0.2697, Recall: 0.3944, F1 Score: 0.2969, AUC: 0.5488, R2 Score: -0.023854, MAE: 1.8230, MSE: 5.3351
Avg Latency (ms): 5.29, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 4/150
Training: Fold 1 - Total Loss: 2.5744, Cross Entropy: 1.226150, Accuracy: 0.4542, Precision: 0.3434, Recall: 0.4542, F1 Score: 0.3639, AUC: 0.5324, R2 Score: -0.119896, MAE: 1.9176, MSE: 5.7203
Training: Fold 2 - Total Loss: 2.4973, Cross Entropy: 1.227812, Accuracy: 0.3838, Precision: 0.2709, Recall: 0.3838, F1 Score: 0.3063, AUC: 0.5435, R2 Score: -0.090430, MAE: 1.8521, MSE: 5.4594
Training: Fold 3 - Total Loss: 2.5456, Cross Entropy: 1.254638, Accuracy: 0.3908, Precision: 0.2735, Recall: 0.3908, F1 Score: 0.3164, AUC: 0.4964, R2 Score: -0.147221, MAE: 1.8793, MSE: 5.5577
Training: Fold 4 - Total Loss: 2.6080, Cross Entropy: 1.227514, Accuracy: 0.4384, Precision: 0.3120, Recall: 0.4384, F1 Score: 0.3528, AUC: 0.5628, R2 Score: -0.042175, MAE: 1.9288, MSE: 5.8292
Validation: Fold 5 - Total Loss: 2.4732, Cross Entropy: 1.205965, Accuracy: 0.4296, Precision: 0.3109, Recall: 0.4296, F1 Score: 0.3243, AUC: 0.5714, R2 Score: -0.036785, MAE: 1.8441, MSE: 5.4302
Avg Latency (ms): 5.29, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 5/150
Training: Fold 1 - Total Loss: 2.5803, Cross Entropy: 1.221803, Accuracy: 0.4243, Precision: 0.3147, Recall: 0.4243, F1 Score: 0.3308, AUC: 0.5627, R2 Score: -0.122887, MAE: 1.9238, MSE: 5.7500
Training: Fold 2 - Total Loss: 2.4493, Cross Entropy: 1.224187, Accuracy: 0.4049, Precision: 0.2921, Recall: 0.4049, F1 Score: 0.3309, AUC: 0.5385, R2 Score: -0.066773, MAE: 1.8490, MSE: 5.3078
Training: Fold 3 - Total Loss: 2.4006, Cross Entropy: 1.234950, Accuracy: 0.4102, Precision: 0.2896, Recall: 0.4102, F1 Score: 0.3242, AUC: 0.5434, R2 Score: -0.064653, MAE: 1.8016, MSE: 5.1203
Training: Fold 4 - Total Loss: 2.5274, Cross Entropy: 1.232252, Accuracy: 0.4278, Precision: 0.3024, Recall: 0.4278, F1 Score: 0.3476, AUC: 0.5469, R2 Score: -0.044285, MAE: 1.8780, MSE: 5.5494
Validation: Fold 5 - Total Loss: 2.4855, Cross Entropy: 1.198621, Accuracy: 0.4437, Precision: 0.3204, Recall: 0.4437, F1 Score: 0.3511, AUC: 0.6120, R2 Score: -0.049321, MAE: 1.8472, MSE: 5.4881
Avg Latency (ms): 5.33, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 6/150
Training: Fold 1 - Total Loss: 2.4702, Cross Entropy: 1.227339, Accuracy: 0.4261, Precision: 0.3146, Recall: 0.4261, F1 Score: 0.3406, AUC: 0.5141, R2 Score: -0.069670, MAE: 1.8671, MSE: 5.3702
Training: Fold 2 - Total Loss: 2.4048, Cross Entropy: 1.224397, Accuracy: 0.4437, Precision: 0.3253, Recall: 0.4437, F1 Score: 0.3573, AUC: 0.5213, R2 Score: -0.012065, MAE: 1.8057, MSE: 5.1589
Training: Fold 3 - Total Loss: 2.4107, Cross Entropy: 1.247476, Accuracy: 0.3979, Precision: 0.2799, Recall: 0.3979, F1 Score: 0.3157, AUC: 0.5445, R2 Score: -0.086425, MAE: 1.7993, MSE: 5.1250
Training: Fold 4 - Total Loss: 2.4915, Cross Entropy: 1.230622, Accuracy: 0.4208, Precision: 0.2967, Recall: 0.4208, F1 Score: 0.3413, AUC: 0.5539, R2 Score: -0.031633, MAE: 1.8624, MSE: 5.4335
Validation: Fold 5 - Total Loss: 2.4407, Cross Entropy: 1.216793, Accuracy: 0.3944, Precision: 0.2670, Recall: 0.3944, F1 Score: 0.3009, AUC: 0.5425, R2 Score: -0.000662, MAE: 1.8173, MSE: 5.2964
Avg Latency (ms): 5.35, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 7/150
Training: Fold 1 - Total Loss: 2.4785, Cross Entropy: 1.217878, Accuracy: 0.4401, Precision: 0.3212, Recall: 0.4401, F1 Score: 0.3503, AUC: 0.5540, R2 Score: -0.062126, MAE: 1.8710, MSE: 5.4200
Training: Fold 2 - Total Loss: 2.3888, Cross Entropy: 1.223021, Accuracy: 0.4085, Precision: 0.2893, Recall: 0.4085, F1 Score: 0.3193, AUC: 0.5451, R2 Score: -0.049362, MAE: 1.8002, MSE: 5.1089
Training: Fold 3 - Total Loss: 2.3796, Cross Entropy: 1.240406, Accuracy: 0.3996, Precision: 0.2842, Recall: 0.3996, F1 Score: 0.3284, AUC: 0.5282, R2 Score: -0.042745, MAE: 1.7835, MSE: 5.0379
Training: Fold 4 - Total Loss: 2.4952, Cross Entropy: 1.222978, Accuracy: 0.4542, Precision: 0.3232, Recall: 0.4542, F1 Score: 0.3727, AUC: 0.5518, R2 Score: -0.020641, MAE: 1.8671, MSE: 5.4636
Validation: Fold 5 - Total Loss: 2.4606, Cross Entropy: 1.210127, Accuracy: 0.3944, Precision: 0.2801, Recall: 0.3944, F1 Score: 0.2971, AUC: 0.5841, R2 Score: -0.035910, MAE: 1.8298, MSE: 5.3784
Avg Latency (ms): 5.30, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 8/150
Training: Fold 1 - Total Loss: 2.4918, Cross Entropy: 1.219251, Accuracy: 0.4349, Precision: 0.3191, Recall: 0.4349, F1 Score: 0.3439, AUC: 0.5429, R2 Score: -0.036704, MAE: 1.8749, MSE: 5.4612
Training: Fold 2 - Total Loss: 2.3833, Cross Entropy: 1.222594, Accuracy: 0.4331, Precision: 0.3169, Recall: 0.4331, F1 Score: 0.3491, AUC: 0.5449, R2 Score: -0.034923, MAE: 1.7966, MSE: 5.0914
Training: Fold 3 - Total Loss: 2.3709, Cross Entropy: 1.222136, Accuracy: 0.4577, Precision: 0.3266, Recall: 0.4577, F1 Score: 0.3752, AUC: 0.5543, R2 Score: -0.065262, MAE: 1.7853, MSE: 5.0515
Training: Fold 4 - Total Loss: 2.4792, Cross Entropy: 1.216284, Accuracy: 0.4613, Precision: 0.3299, Recall: 0.4613, F1 Score: 0.3820, AUC: 0.5833, R2 Score: -0.013573, MAE: 1.8513, MSE: 5.4261
Validation: Fold 5 - Total Loss: 2.4165, Cross Entropy: 1.179969, Accuracy: 0.4507, Precision: 0.3162, Recall: 0.4507, F1 Score: 0.3620, AUC: 0.5820, R2 Score: -0.020079, MAE: 1.8206, MSE: 5.3019
Avg Latency (ms): 5.29, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 9/150
Training: Fold 1 - Total Loss: 2.4556, Cross Entropy: 1.209526, Accuracy: 0.4489, Precision: 0.3300, Recall: 0.4489, F1 Score: 0.3637, AUC: 0.5716, R2 Score: -0.026958, MAE: 1.8588, MSE: 5.3633
Training: Fold 2 - Total Loss: 2.3710, Cross Entropy: 1.221045, Accuracy: 0.4137, Precision: 0.2934, Recall: 0.4137, F1 Score: 0.3302, AUC: 0.5535, R2 Score: -0.001837, MAE: 1.7885, MSE: 5.0543
Training: Fold 3 - Total Loss: 2.3910, Cross Entropy: 1.236809, Accuracy: 0.4032, Precision: 0.2839, Recall: 0.4032, F1 Score: 0.3227, AUC: 0.5468, R2 Score: -0.064879, MAE: 1.7993, MSE: 5.0841
Training: Fold 4 - Total Loss: 2.5060, Cross Entropy: 1.231114, Accuracy: 0.4173, Precision: 0.2962, Recall: 0.4173, F1 Score: 0.3442, AUC: 0.5409, R2 Score: -0.026003, MAE: 1.8580, MSE: 5.4808
Validation: Fold 5 - Total Loss: 2.4350, Cross Entropy: 1.188569, Accuracy: 0.4718, Precision: 0.3398, Recall: 0.4718, F1 Score: 0.3823, AUC: 0.6008, R2 Score: -0.013320, MAE: 1.8239, MSE: 5.3432
Avg Latency (ms): 5.30, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 10/150
Training: Fold 1 - Total Loss: 2.4672, Cross Entropy: 1.210269, Accuracy: 0.4366, Precision: 0.3179, Recall: 0.4366, F1 Score: 0.3599, AUC: 0.5663, R2 Score: -0.020215, MAE: 1.8662, MSE: 5.4000
Training: Fold 2 - Total Loss: 2.3837, Cross Entropy: 1.219817, Accuracy: 0.4155, Precision: 0.2970, Recall: 0.4155, F1 Score: 0.3367, AUC: 0.5632, R2 Score: -0.029675, MAE: 1.7943, MSE: 5.0993
Training: Fold 3 - Total Loss: 2.3720, Cross Entropy: 1.231765, Accuracy: 0.4190, Precision: 0.2985, Recall: 0.4190, F1 Score: 0.3437, AUC: 0.5451, R2 Score: -0.030957, MAE: 1.7859, MSE: 5.0326
Training: Fold 4 - Total Loss: 2.4898, Cross Entropy: 1.222572, Accuracy: 0.4296, Precision: 0.3054, Recall: 0.4296, F1 Score: 0.3547, AUC: 0.5595, R2 Score: -0.044919, MAE: 1.8595, MSE: 5.4465
Validation: Fold 5 - Total Loss: 2.4326, Cross Entropy: 1.203241, Accuracy: 0.3873, Precision: 0.2596, Recall: 0.3873, F1 Score: 0.2964, AUC: 0.5462, R2 Score: -0.012318, MAE: 1.8222, MSE: 5.3013
Avg Latency (ms): 5.30, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 11/150
Training: Fold 1 - Total Loss: 2.4488, Cross Entropy: 1.213372, Accuracy: 0.4366, Precision: 0.3163, Recall: 0.4366, F1 Score: 0.3470, AUC: 0.5792, R2 Score: -0.011591, MAE: 1.8476, MSE: 5.3313
Training: Fold 2 - Total Loss: 2.3605, Cross Entropy: 1.217169, Accuracy: 0.4313, Precision: 0.3134, Recall: 0.4313, F1 Score: 0.3604, AUC: 0.5570, R2 Score: -0.029760, MAE: 1.7835, MSE: 5.0284
Training: Fold 3 - Total Loss: 2.3433, Cross Entropy: 1.228297, Accuracy: 0.4225, Precision: 0.3005, Recall: 0.4225, F1 Score: 0.3486, AUC: 0.5519, R2 Score: -0.028492, MAE: 1.7610, MSE: 4.9451
Training: Fold 4 - Total Loss: 2.4791, Cross Entropy: 1.224186, Accuracy: 0.4278, Precision: 0.3052, Recall: 0.4278, F1 Score: 0.3532, AUC: 0.5602, R2 Score: -0.026807, MAE: 1.8499, MSE: 5.4072
Validation: Fold 5 - Total Loss: 2.4089, Cross Entropy: 1.189757, Accuracy: 0.4366, Precision: 0.3074, Recall: 0.4366, F1 Score: 0.3397, AUC: 0.5982, R2 Score: -0.005520, MAE: 1.8194, MSE: 5.2534
Avg Latency (ms): 5.29, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 12/150
Training: Fold 1 - Total Loss: 2.4566, Cross Entropy: 1.210590, Accuracy: 0.4401, Precision: 0.3186, Recall: 0.4401, F1 Score: 0.3567, AUC: 0.5620, R2 Score: -0.025475, MAE: 1.8635, MSE: 5.3641
Training: Fold 2 - Total Loss: 2.3614, Cross Entropy: 1.208198, Accuracy: 0.4454, Precision: 0.3226, Recall: 0.4454, F1 Score: 0.3717, AUC: 0.5545, R2 Score: -0.030739, MAE: 1.7914, MSE: 5.0522
Training: Fold 3 - Total Loss: 2.3478, Cross Entropy: 1.230612, Accuracy: 0.4384, Precision: 0.3107, Recall: 0.4384, F1 Score: 0.3595, AUC: 0.5477, R2 Score: -0.006027, MAE: 1.7651, MSE: 4.9547
Training: Fold 4 - Total Loss: 2.4975, Cross Entropy: 1.220390, Accuracy: 0.4155, Precision: 0.2938, Recall: 0.4155, F1 Score: 0.3395, AUC: 0.5567, R2 Score: -0.013226, MAE: 1.8685, MSE: 5.4774
Validation: Fold 5 - Total Loss: 2.4305, Cross Entropy: 1.179033, Accuracy: 0.4577, Precision: 0.3202, Recall: 0.4577, F1 Score: 0.3688, AUC: 0.6003, R2 Score: -0.021934, MAE: 1.8269, MSE: 5.3505
Avg Latency (ms): 5.30, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 13/150
Training: Fold 1 - Total Loss: 2.4588, Cross Entropy: 1.206603, Accuracy: 0.4437, Precision: 0.3217, Recall: 0.4437, F1 Score: 0.3668, AUC: 0.5757, R2 Score: -0.013990, MAE: 1.8639, MSE: 5.3804
Training: Fold 2 - Total Loss: 2.3650, Cross Entropy: 1.214414, Accuracy: 0.4190, Precision: 0.3034, Recall: 0.4190, F1 Score: 0.3507, AUC: 0.5787, R2 Score: 0.006147, MAE: 1.7923, MSE: 5.0497
Training: Fold 3 - Total Loss: 2.3412, Cross Entropy: 1.225169, Accuracy: 0.4032, Precision: 0.2849, Recall: 0.4032, F1 Score: 0.3333, AUC: 0.5645, R2 Score: -0.021299, MAE: 1.7655, MSE: 4.9454
Training: Fold 4 - Total Loss: 2.4750, Cross Entropy: 1.229170, Accuracy: 0.4049, Precision: 0.2869, Recall: 0.4049, F1 Score: 0.3341, AUC: 0.5447, R2 Score: -0.020984, MAE: 1.8490, MSE: 5.3820
Validation: Fold 5 - Total Loss: 2.4141, Cross Entropy: 1.186220, Accuracy: 0.4718, Precision: 0.3367, Recall: 0.4718, F1 Score: 0.3755, AUC: 0.5981, R2 Score: 0.001318, MAE: 1.8226, MSE: 5.2791
Avg Latency (ms): 5.29, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 14/150
Training: Fold 1 - Total Loss: 2.4541, Cross Entropy: 1.217567, Accuracy: 0.4419, Precision: 0.3189, Recall: 0.4419, F1 Score: 0.3615, AUC: 0.5497, R2 Score: -0.042054, MAE: 1.8554, MSE: 5.3395
Training: Fold 2 - Total Loss: 2.3818, Cross Entropy: 1.211882, Accuracy: 0.4190, Precision: 0.3049, Recall: 0.4190, F1 Score: 0.3523, AUC: 0.5764, R2 Score: -0.024806, MAE: 1.7962, MSE: 5.1117
Training: Fold 3 - Total Loss: 2.3618, Cross Entropy: 1.221170, Accuracy: 0.4225, Precision: 0.2989, Recall: 0.4225, F1 Score: 0.3484, AUC: 0.5816, R2 Score: -0.000154, MAE: 1.7752, MSE: 5.0232
Training: Fold 4 - Total Loss: 2.4623, Cross Entropy: 1.203580, Accuracy: 0.4489, Precision: 0.3217, Recall: 0.4489, F1 Score: 0.3732, AUC: 0.5982, R2 Score: -0.017192, MAE: 1.8531, MSE: 5.3994
Validation: Fold 5 - Total Loss: 2.3823, Cross Entropy: 1.163673, Accuracy: 0.4930, Precision: 0.3561, Recall: 0.4930, F1 Score: 0.3933, AUC: 0.6164, R2 Score: 0.037834, MAE: 1.8135, MSE: 5.2258
Avg Latency (ms): 5.28, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23
Best model saved with Accuracy: 0.4930

Epoch 15/150
Training: Fold 1 - Total Loss: 2.4538, Cross Entropy: 1.205412, Accuracy: 0.4225, Precision: 0.3060, Recall: 0.4225, F1 Score: 0.3491, AUC: 0.5778, R2 Score: -0.023462, MAE: 1.8566, MSE: 5.3667
Training: Fold 2 - Total Loss: 2.3555, Cross Entropy: 1.197619, Accuracy: 0.4648, Precision: 0.3400, Recall: 0.4648, F1 Score: 0.3927, AUC: 0.5847, R2 Score: -0.008550, MAE: 1.7899, MSE: 5.0571
Training: Fold 3 - Total Loss: 2.3418, Cross Entropy: 1.225659, Accuracy: 0.4366, Precision: 0.3085, Recall: 0.4366, F1 Score: 0.3590, AUC: 0.5694, R2 Score: -0.011450, MAE: 1.7644, MSE: 4.9461
Training: Fold 4 - Total Loss: 2.4736, Cross Entropy: 1.211332, Accuracy: 0.4331, Precision: 0.3153, Recall: 0.4331, F1 Score: 0.3649, AUC: 0.5766, R2 Score: -0.028162, MAE: 1.8545, MSE: 5.4188
Validation: Fold 5 - Total Loss: 2.4051, Cross Entropy: 1.163736, Accuracy: 0.4718, Precision: 0.3282, Recall: 0.4718, F1 Score: 0.3864, AUC: 0.6092, R2 Score: -0.000380, MAE: 1.8250, MSE: 5.3015
Avg Latency (ms): 5.33, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 16/150
Training: Fold 1 - Total Loss: 2.4376, Cross Entropy: 1.208898, Accuracy: 0.4472, Precision: 0.3237, Recall: 0.4472, F1 Score: 0.3645, AUC: 0.5636, R2 Score: -0.000613, MAE: 1.8504, MSE: 5.3044
Training: Fold 2 - Total Loss: 2.3667, Cross Entropy: 1.212063, Accuracy: 0.4736, Precision: 0.3446, Recall: 0.4736, F1 Score: 0.3963, AUC: 0.5520, R2 Score: -0.022424, MAE: 1.7883, MSE: 5.0608
Training: Fold 3 - Total Loss: 2.3274, Cross Entropy: 1.224260, Accuracy: 0.4102, Precision: 0.2896, Recall: 0.4102, F1 Score: 0.3384, AUC: 0.5685, R2 Score: 0.004858, MAE: 1.7545, MSE: 4.9014
Training: Fold 4 - Total Loss: 2.4834, Cross Entropy: 1.213805, Accuracy: 0.4349, Precision: 0.3211, Recall: 0.4349, F1 Score: 0.3682, AUC: 0.5651, R2 Score: -0.035701, MAE: 1.8623, MSE: 5.4459
Validation: Fold 5 - Total Loss: 2.4045, Cross Entropy: 1.200763, Accuracy: 0.4085, Precision: 0.2750, Recall: 0.4085, F1 Score: 0.3236, AUC: 0.5681, R2 Score: 0.036540, MAE: 1.8253, MSE: 5.2134
Avg Latency (ms): 5.29, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 17/150
Training: Fold 1 - Total Loss: 2.4481, Cross Entropy: 1.196420, Accuracy: 0.4736, Precision: 0.3480, Recall: 0.4736, F1 Score: 0.3968, AUC: 0.5720, R2 Score: -0.009375, MAE: 1.8565, MSE: 5.3686
Training: Fold 2 - Total Loss: 2.3683, Cross Entropy: 1.210791, Accuracy: 0.4419, Precision: 0.3217, Recall: 0.4419, F1 Score: 0.3705, AUC: 0.5694, R2 Score: -0.017540, MAE: 1.7950, MSE: 5.0691
Training: Fold 3 - Total Loss: 2.3450, Cross Entropy: 1.230940, Accuracy: 0.3961, Precision: 0.2781, Recall: 0.3961, F1 Score: 0.3252, AUC: 0.5719, R2 Score: -0.009623, MAE: 1.7631, MSE: 4.9446
Training: Fold 4 - Total Loss: 2.4623, Cross Entropy: 1.200246, Accuracy: 0.4331, Precision: 0.3168, Recall: 0.4331, F1 Score: 0.3658, AUC: 0.5930, R2 Score: -0.019895, MAE: 1.8508, MSE: 5.4072
Validation: Fold 5 - Total Loss: 2.3786, Cross Entropy: 1.152527, Accuracy: 0.4789, Precision: 0.3336, Recall: 0.4789, F1 Score: 0.3859, AUC: 0.6083, R2 Score: -0.002262, MAE: 1.8139, MSE: 5.2393
Avg Latency (ms): 5.30, Avg Memory Before (MB): 112.47, Avg Memory After (MB): 112.47, Avg Max Memory (MB): 441.23

Epoch 18/150
Training: Fold 1 - Total Loss: 2.4474, Cross Entropy: 1.194171, Accuracy: 0.4507, Precision: 0.3274, Recall: 0.4507, F1 Score: 0.3708, AUC: 0.5664, R2 Score: -0.026132, MAE: 1.8568, MSE: 5.3717
Training: Fold 2 - Total Loss: 2.3677, Cross Entropy: 1.215984, Accuracy: 0.4225, Precision: 0.3075, Recall: 0.4225, F1 Score: 0.3555, AUC: 0.5612, R2 Score: -0.007480, MAE: 1.7911, MSE: 5.0550
Training: Fold 3 - Total Loss: 2.3534, Cross Entropy: 1.214416, Accuracy: 0.4454, Precision: 0.3164, Recall: 0.4454, F1 Score: 0.3697, AUC: 0.5770, R2 Score: -0.027281, MAE: 1.7757, MSE: 5.0109
Training: Fold 4 - Total Loss: 2.4669, Cross Entropy: 1.198251, Accuracy: 0.4472, Precision: 0.3296, Recall: 0.4472, F1 Score: 0.3787, AUC: 0.5858, R2 Score: -0.003353, MAE: 1.8565, MSE: 5.4269
Validation: Fold 5 - Total Loss: 2.3887, Cross Entropy: 1.159652, Accuracy: 0.4437, Precision: 0.3064, Recall: 0.4437, F1 Score: 0.3616, AUC: 0.6013, R2 Score: 0.002048, MAE: 1.8137, MSE: 5.2563

## Running Inference on All 12 Models:

In [ ]:
for arch in models_list:
    # Define loss functions
    cross_entropy_loss = torch.nn.CrossEntropyLoss()  # Multi-class classification loss
    mse_loss = torch.nn.MSELoss()  # Regression loss
    mae_loss = torch.nn.L1Loss()  # Regression loss

    test_metrics_list = []
    print("="*100)
    print(f"{arch}")
    model = MultiModel(arch).to(device)
    pretrained_model_path = f"{weights_dir}/pytorch/model_best_accuracy_{arch}_{signature}.pth"
    model.load_state_dict(torch.load(pretrained_model_path))
    print(f"Loaded {pretrained_model_path}")

    # === Testing PHASE ===
    test_metrics, test_stats = eval(test_loader, model, cross_entropy_loss, mse_loss, mae_loss)
    print(
        f"Testing: Total Loss: {test_metrics[0]:.4f}, Cross Entropy: {test_metrics[1]:4f}, Accuracy: {test_metrics[2]:.4f}, "
        f"Precision: {test_metrics[3]:.4f}, Recall: {test_metrics[4]:.4f}, F1 Score: {test_metrics[5]:.4f}, AUC: {test_metrics[6]:.4f}, "
        f"R2 Score: {test_metrics[7]:4f}, MAE: {test_metrics[8]:.4f}, MSE: {test_metrics[9]:.4f}"
    )
    print(
        f"Avg Latency (ms): {test_stats[0]:.2f}, Avg Memory Before (MB): {test_stats[1]:.2f}, "
        f"Avg Memory After (MB): {test_stats[2]:.2f}, Avg Max Memory (MB): {test_stats[3]:.2f}"
    )

    # Store validation metrics
    test_metrics_list.append(
        {
            "total_loss": test_metrics[0],
            "cross_entropy_loss": test_metrics[1],
            "accuracy": test_metrics[2],
            "precision": test_metrics[3],
            "recall": test_metrics[4],
            "f1_score": test_metrics[5],
            "auc": test_metrics[6],
            "r2_score": test_metrics[7],
            "mae_loss": test_metrics[8],
            "mse_loss": test_metrics[9],
            "latency": test_stats[0],
            "malloc_before": test_stats[1],
            "malloc_after": test_stats[2],
            "max_malloc": test_stats[3],
        }
    )

    keys = test_metrics_list[0].keys()
    with open(f"{metrics_dir}/pytorch/testing_metrics_{arch}_{signature}.csv", 'w', newline='') as output_file:
        dict_writer = csv.DictWriter(output_file, keys)
        dict_writer.writeheader()
        dict_writer.writerows(test_metrics_list)

====================================================================================================
mobilenetv2
Initial Backbone Model Size: 14.24 MB
Modified Backbone Model Size: 9.78 MB

Loaded weights/pytorch/model_best_accuracy_mobilenetv2_BENCHMARK.pth
Testing: Total Loss: 1.8283, Cross Entropy: 0.394130, Accuracy: 0.8310, Precision: 0.8402, Recall: 0.8310, F1 Score: 0.8343, AUC: 0.9383, R2 Score: -0.060051, MAE: 1.8835, MSE: 5.1747
Avg Latency (ms): 3.91, Avg Memory Before (MB): 121.37, Avg Memory After (MB): 121.38, Avg Max Memory (MB): 406.24
====================================================================================================
resnet18
Initial Backbone Model Size: 46.83 MB
Modified Backbone Model Size: 45.04 MB

Loaded weights/pytorch/model_best_accuracy_resnet18_BENCHMARK.pth
Testing: Total Loss: 1.7934, Cross Entropy: 0.399043, Accuracy: 0.8310, Precision: 0.8725, Recall: 0.8310, F1 Score: 0.8409, AUC: 0.9489, R2 Score: 0.011767, MAE: 1.8640, MSE: 5.0471
Avg Latency (ms): 3.19, Avg Memory Before (MB): 155.70, Avg Memory After (MB): 155.70, Avg Max Memory (MB): 329.65
====================================================================================================
densenet121
Initial Backbone Model Size: 32.47 MB
Modified Backbone Model Size: 28.90 MB

Loaded weights/pytorch/model_best_accuracy_densenet121_BENCHMARK.pth
Testing: Total Loss: 1.7154, Cross Entropy: 0.294897, Accuracy: 0.8662, Precision: 0.8818, Recall: 0.8662, F1 Score: 0.8717, AUC: 0.9656, R2 Score: -0.008836, MAE: 1.8613, MSE: 5.0300
Avg Latency (ms): 11.53, Avg Memory Before (MB): 140.24, Avg Memory After (MB): 140.24, Avg Max Memory (MB): 413.14
====================================================================================================
vgg16
Initial Backbone Model Size: 553.44 MB
Modified Backbone Model Size: 71.72 MB

Loaded weights/pytorch/model_best_accuracy_vgg16_BENCHMARK.pth
Testing: Total Loss: 1.6979, Cross Entropy: 0.270658, Accuracy: 0.8803, Precision: 0.8943, Recall: 0.8803, F1 Score: 0.8857, AUC: 0.9641, R2 Score: 0.074591, MAE: 1.8603, MSE: 5.0282
Avg Latency (ms): 22.03, Avg Memory Before (MB): 181.52, Avg Memory After (MB): 181.52, Avg Max Memory (MB): 1225.36
====================================================================================================
vit-tiny
Initial Backbone Model Size: 22.92 MB
Modified Backbone Model Size: 22.25 MB

Loaded weights/pytorch/model_best_accuracy_vit-tiny_BENCHMARK.pth
Testing: Total Loss: 1.7953, Cross Entropy: 0.418297, Accuracy: 0.7958, Precision: 0.8250, Recall: 0.7958, F1 Score: 0.7990, AUC: 0.9412, R2 Score: 0.023398, MAE: 1.8577, MSE: 5.0083
Avg Latency (ms): 4.56, Avg Memory Before (MB): 133.41, Avg Memory After (MB): 133.42, Avg Max Memory (MB): 183.24
====================================================================================================
efficientnet-b0
Initial Backbone Model Size: 21.43 MB
Modified Backbone Model Size: 16.96 MB

Loaded weights/pytorch/model_best_accuracy_efficientnet-b0_BENCHMARK.pth
Testing: Total Loss: 1.7755, Cross Entropy: 0.366077, Accuracy: 0.8099, Precision: 0.8400, Recall: 0.8099, F1 Score: 0.8166, AUC: 0.9509, R2 Score: -0.011131, MAE: 1.8662, MSE: 5.0643
Avg Latency (ms): 4.84, Avg Memory Before (MB): 128.21, Avg Memory After (MB): 128.21, Avg Max Memory (MB): 412.68
====================================================================================================
shufflenetv2-0.5x
Initial Backbone Model Size: 5.59 MB
Modified Backbone Model Size: 2.02 MB

Loaded weights/pytorch/model_best_accuracy_shufflenetv2-0.5x_BENCHMARK.pth
Testing: Total Loss: 2.2062, Cross Entropy: 0.998384, Accuracy: 0.5915, Precision: 0.5777, Recall: 0.5915, F1 Score: 0.5836, AUC: 0.7015, R2 Score: 0.011907, MAE: 1.8597, MSE: 5.0243
Avg Latency (ms): 2.85, Avg Memory Before (MB): 114.16, Avg Memory After (MB): 114.16, Avg Max Memory (MB): 179.39
====================================================================================================
regnety-400mf
Initial Backbone Model Size: 17.61 MB
Modified Backbone Model Size: 16.07 MB

Loaded weights/pytorch/model_best_accuracy_regnety-400mf_BENCHMARK.pth
Testing: Total Loss: 1.7385, Cross Entropy: 0.339785, Accuracy: 0.8451, Precision: 0.8455, Recall: 0.8451, F1 Score: 0.8450, AUC: 0.9522, R2 Score: 0.029007, MAE: 1.8554, MSE: 5.0021
Avg Latency (ms): 3.96, Avg Memory Before (MB): 127.53, Avg Memory After (MB): 127.53, Avg Max Memory (MB): 318.79
====================================================================================================
mnasnet0_5
Initial Backbone Model Size: 9.04 MB
Modified Backbone Model Size: 4.58 MB

Loaded weights/pytorch/model_best_accuracy_mnasnet0_5_BENCHMARK.pth
Testing: Total Loss: 31.8855, Cross Entropy: 1.343342, Accuracy: 0.4577, Precision: 0.2095, Recall: 0.4577, F1 Score: 0.2875, AUC: 0.4405, R2 Score: -19.195934, MAE: 9.9071, MSE: 103.1506
Avg Latency (ms): 2.10, Avg Memory Before (MB): 116.59, Avg Memory After (MB): 116.60, Avg Max Memory (MB): 192.70
====================================================================================================
convnext-tiny
Initial Backbone Model Size: 114.41 MB
Modified Backbone Model Size: 111.72 MB

Loaded weights/pytorch/model_best_accuracy_convnext-tiny_BENCHMARK.pth
Testing: Total Loss: 2.3581, Cross Entropy: 1.023373, Accuracy: 0.5282, Precision: 0.4872, Recall: 0.5282, F1 Score: 0.4970, AUC: 0.7252, R2 Score: -0.076256, MAE: 1.9383, MSE: 5.4724
Avg Latency (ms): 12.88, Avg Memory Before (MB): 219.75, Avg Memory After (MB): 219.75, Avg Max Memory (MB): 547.50
====================================================================================================
ghostnetv2
Initial Backbone Model Size: 25.11 MB
Modified Backbone Model Size: 20.64 MB

Loaded weights/pytorch/model_best_accuracy_ghostnetv2_BENCHMARK.pth
Testing: Total Loss: 1.7927, Cross Entropy: 0.382896, Accuracy: 0.8239, Precision: 0.8506, Recall: 0.8239, F1 Score: 0.8346, AUC: 0.9424, R2 Score: -0.018696, MAE: 1.8690, MSE: 5.0821
Avg Latency (ms): 5.88, Avg Memory Before (MB): 131.89, Avg Memory After (MB): 131.89, Avg Max Memory (MB): 306.24
====================================================================================================
tinynet-a
Initial Backbone Model Size: 25.08 MB
Modified Backbone Model Size: 20.62 MB

Loaded weights/pytorch/model_best_accuracy_tinynet-a_BENCHMARK.pth
Testing: Total Loss: 1.7422, Cross Entropy: 0.307840, Accuracy: 0.8662, Precision: 0.8841, Recall: 0.8662, F1 Score: 0.8724, AUC: 0.9607, R2 Score: -0.069940, MAE: 1.8698, MSE: 5.0891
Avg Latency (ms): 5.41, Avg Memory Before (MB): 131.69, Avg Memory After (MB): 131.69, Avg Max Memory (MB): 460.24